- Makefile
- README.md
- pkg/cli/cli.go
- pkg/cli/install.go
- pkg/cli/kubeconfig.go
- pkg/cli/root.go
- pkg/cli/start.go
- pkg/cli/stop.go
- pkg/config/config.go
- pkg/constants/constants.go
- pkg/install/install.go
> feat: branded install, start and stop commands

- cmd/helmvm/install.go
- pkg/addons/custom/custom.go
- pkg/config/config.go
- pkg/config/host.go
after introducing the token based authentication and the localhost installation without ssh some bugs remained. these were caught while developing the integration test suite for the project.
- the configuration overwrite question logic was inverted.
- we need to also create the namespace when installing custom helm.
- forcing the init script creation.
> bug: fixing some installation related bugs

- .github/workflows/pull-request.yaml
- .github/workflows/release-prod.yaml
- Makefile
- cmd/helmvm/install.go
- cmd/helmvm/main.go
- cmd/helmvm/upgrade.go
- cmd/helmvm/version.go
- pkg/addons/adminconsole/adminconsole.go
- pkg/addons/applier.go
- pkg/addons/custom/custom.go
- pkg/addons/openebs/openebs.go
add command to show current binary version.
sample output:
```
$ helmvm version
+--------------+---------------+
| COMPONENT    | VERSION       |
+--------------+---------------+
| Installer    | v0.0.0        |
| Kubernetes   | v1.27.2+k0s.0 |
| AdminConsole | v1.100.1      |
| OpenEBS      | v3.7.0        |
+--------------+---------------+
$
```
> feat: add version command

- README.md
documenting `--infra` under the experimental features section.
> chore: bringing infra flag doc back

- cmd/helmvm/upgrade.go
users shouldn't be able to run `helmvm node upgrade` when they are using a centralized config. on a centralized config all nodes are upgraded with a single `helmvm apply` or `helmvm install` command. this commit blocks users from attempting to upgrade nodes individually until they have added other nodes to the cluster using `join` commands.
> feat: block individual node upgrades when using centralized config

- cmd/helmvm/bundle.go
- cmd/helmvm/install.go
- pkg/addons/applier.go
- pkg/config/host.go
- pkg/infra/infra.go
- pkg/preflights/preflights.go
- pkg/progressbar/progressbar.go
- pkg/progressbar/progressbar_test.go
adds unit tests on progressbar package and simplifies its usage by providing a proper close and a new closef functions.
> chore: adding unit tests for progressbar package

- cmd/helmvm/bundle.go
- cmd/helmvm/install.go
- pkg/addons/adminconsole/adminconsole.go
- pkg/addons/applier.go
- pkg/addons/custom/custom.go
- pkg/addons/openebs/openebs.go
- pkg/config/host.go
- pkg/infra/infra.go
- pkg/infra/infra_test.go
- pkg/preflights/preflights.go
- pkg/progressbar/options.go
- pkg/progressbar/progressbar.go
- pkg/progressbar/progressbar_test.go
this pr adds more visible feedback to the users while the installation is taking place. this introduces no functional change, we only added some spinning while installing add-ons and improved the messages being written to the screen.
> feat: improve feedback to user

- Makefile
> chore: allow build on mac os environment

- e2e/scripts/addons-only.sh
- e2e/scripts/embed-and-install.sh
- e2e/scripts/embedded-preflight.sh
- e2e/scripts/install-with-disabled-addons.sh
- e2e/scripts/interactive-multi-node-install.exp
- e2e/scripts/multi-node-install.sh
- e2e/scripts/single-node-install.sh
- e2e/scripts/wait-for-ready-nodes.sh
sending helmvm metrics during github workflows to staging endpoint.
> chore(tests): using staging metrics endpoint

- .github/workflows/pull-request.yaml
* Remove unneded files on ubuntu runners
* Add du commands for better storage debugging
> Free up some storage on pull requests to build

- pkg/addons/adminconsole/customize.go
include installer version to the cluster configuration configmap.
> feat: include installer version to the cluster configuration configmap

- .github/workflows/pull-request.yaml
both jobs were cleaning runner disk space.
> chore: unify two ci jobs doing the same thing

- e2e/scripts/interactive-multi-node-install.exp
- pkg/config/config.go
removes the load balancer configuration from the configuration wizard.
> feat: remove load balancer configuration

- pkg/addons/custom/custom.go
- pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
- pkg/addons/openebs/openebs.go
- pkg/defaults/defaults.go
- pkg/defaults/provider.go
- pkg/hembed/hembed.go
- pkg/logging/logging.go
- pkg/preflights/output.go
- pkg/preflights/preflights.go
- pkg/progressbar/options.go
- pkg/prompts/prompts.go
- pkg/ssh/ssh.go
my editor shows me alert across multiple files due to missing comments or invalid types and variable names. this pr fixes all of them.
> chore: getting rid of linting complains

- Makefile
removed unused entries and adjusting indentation.
> chore: cosmetic changes to makefile

- README.md
- e2e/scripts/addons-only.sh
- e2e/scripts/embed-and-install.sh
- e2e/scripts/embedded-preflight.sh
- e2e/scripts/install-with-disabled-addons.sh
- e2e/scripts/multi-node-install.sh
- e2e/scripts/single-node-install.sh
- e2e/scripts/wait-for-ready-nodes.sh
- pkg/defaults/provider.go
Reverts replicatedhq/helmvm#130
> Revert "Remove the '.' from helmvm folder name"

- cmd/helmvm/join.go
> bug: disable konnectivity-server on join

- pkg/addons/adminconsole/adminconsole.go
Progress Bar will no longer show the errors from the isReady functions until a timeout occurs.
> bug: cleanup progress bar output

- Makefile
> embed a custom build of k0s 1.28.4

- .github/workflows/e2e.yaml
- e2e/kots-release/config.yaml
- e2e/scripts/unsupported-overrides.sh
- e2e/unsupported-overrides_test.go
- pkg/config/config.go
fix the unsupported overrides feature and adds an e2e test for it.
> feat: fix unsupported overrides and add e2e test

- e2e/scripts/embed-and-install.sh
- e2e/scripts/embedded-preflight.sh
- e2e/scripts/install-with-disabled-addons.sh
- e2e/scripts/single-node-install.sh
- e2e/scripts/unsupported-overrides.sh
- e2e/scripts/wait-for-ready-nodes.sh
- pkg/defaults/provider.go
inside the .config we should be using binary-name and not .binary-name.
> feat: use binary-name instead of .binary-name

- e2e/scripts/unsupported-overrides.sh
add an extra unsupported override during e2e tests.
> feat(e2e): make sure we can override worker profiles

- pkg/addons/adminconsole/adminconsole.go
The kotsadm helm chart handles this nicely already.
> feat: unprotect kotsadm password 

- cmd/embedded-cluster/install.go
- e2e/scripts/unsupported-overrides.sh
- pkg/config/config.go
fixes the unsupported overrides being overwritten. adds a more complete end to end test case.
> feat: fixes unsupported overrides for extensions

- pkg/addons/adminconsole/adminconsole.go
- pkg/metrics/reporter.go
Also, protect against races in clusterID function
> feat: provide clusterID to kotsadm

- .gitignore
- Makefile
better than keeping them in the root of the project.
> feat: save release files to output directory

- e2e/install_test.go
- e2e/scripts/check-app-and-cluster-status.js
- e2e/scripts/install-puppeteer.sh
- e2e/scripts/puppeteer.sh
access kots through web and make sure the app is ready and the cluster is up to date.
> feat: checking cluster and app state during ci

- cmd/embedded-cluster/node.go
- cmd/embedded-cluster/reset.go
- go.mod
TODO: 
removing binaries and extra files can be looked at later along with the other efforts towards that task.
> feat: reset command

- e2e/cluster/cluster.go
I have seen this failure a few times in some of our CI runs. Try 5 times before giving up.
> feat: retry if unable to access the internet

- .github/workflows/e2e.yaml
- e2e/install_test.go
- e2e/scripts/generate-controller-join-token.js
- e2e/scripts/generate-worker-join-token.js
- Create scripts to generate worker and controller join token through Kots web interface.
- Create e2e test that deploys a multi-node cluster (3 controllers + 1 worker).
> feat: e2e tests for multi node clusters

- scripts/cache-files.sh
publishes the release tgz file into a s3 bucket.
> feat: publish releases to the s3 bucket

- .github/workflows/release-dev.yaml
>Error: Unable to download artifact(s): Artifact not found for name: embedded-release-onmerge
10
> fix on-merge tests

- cmd/embedded-cluster/install.go
- cmd/embedded-cluster/main.go
- cmd/embedded-cluster/reset.go
- cmd/embedded-cluster/shell.go
- cmd/embedded-cluster/version.go
polishing cli arguments and help messages
> feat: polishing cli arguments and help messages

- cmd/embedded-cluster/join.go
- cmd/embedded-cluster/node.go
- cmd/embedded-cluster/reset.go
also fix running 'node join help'/'node reset help' as non-root
> feat: remove node start, stop, list commands

- pkg/metrics/reporter.go
This will change our reporting to no longer tie multiple installs on the same instance together, but that's something we want to do anyways
> feat: remove cluster ID file

- cmd/embedded-cluster/install.go
- pkg/addons/adminconsole/adminconsole.go
- pkg/addons/applier.go
- pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
- pkg/spinner/options.go
- pkg/spinner/spinner.go
- pkg/spinner/spinner_test.go
- only print "running preflights" if preflights exist.
- rename progressbar to spinner (it does not indicate progress neither is a bar).
> feat: only print "running preflights" if preflights exist

- cmd/embedded-cluster/version.go
- e2e/version_test.go
application, cluster config, channel release, and host preflights
> add a hidden command that prints the embedded data

- pkg/logging/logging.go
the default logrus hook should be used, even when running as a regular user.
> bug: still use default logger with regular user

- e2e/scripts/collect-support-bundle.sh
check if we have some expected files and directories inside the generated support bundle.
> feat: check if support bundle contains expected files

- .github/actions/e2e/action.yml
- .github/workflows/pull-request.yaml
- .github/workflows/release-dev.yaml
- e2e/install_test.go
- e2e/scripts/single-node-airgap-install.sh
- e2e/scripts/vandoor-prepare.sh
This ensures that the airgap flag works with an airgap bundle, but does not yet validate that:
1. the app installs (because it doesn't)
2. that things work without an internet connection (because we're not disabling that yet)
> test airgap in CI

- Makefile
- pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
this was already done for admin-console
> allow compiling embedded-cluster with overridden operator image

- Makefile
- pkg/addons/adminconsole/adminconsole.go
- pkg/helpers/command.go
- pkg/spinner/spinner.go
- pkg/spinner/spinner_test.go
provide users with more feedback during the finalizing step of the installation. shows the images being pushed.
> feat: improve finalizing step feedback

- pkg/goods/support/host-support-bundle.yaml
> chore: collect k0scontroller systemd logs

- .github/workflows/pull-request.yaml
This way we can add a branch protection rule that requires that all tests pass
> add a validate-success job to the PR workflow

- pkg/addons/applier.go
Reverts replicatedhq/embedded-cluster#621
Coredns takes so long to come up that it makes many of the following spinners redundant
> Revert "feat: wait for coredns and metrics-server"

- .github/workflows/pull-request.yaml
- .github/workflows/release-dev.yaml
- .github/workflows/release-prod.yaml
- Dockerfile
- Makefile
build and publish local-artifact-mirror image.
> feat: build and publish local-artifact-mirror image

- .github/workflows/pull-request.yaml
- .github/workflows/release-dev.yaml
- cmd/embedded-cluster/join.go
- cmd/embedded-cluster/uninstall.go
- cmd/local-artifact-mirror/pull.go
- pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
- pkg/kubeutils/kubeutils.go
- pkg/kubeutils/scheme.go
unify calls to AddToScheme since all clients using global scheme.Scheme
> fix: add to k8s scheme once in init

- .github/workflows/mirror-helm-charts.yaml
> chore: fix github action yaml

- pkg/preflights/host-preflight.yaml
> feat: Use filesystem specific checks for host preflights

- cmd/embedded-cluster/install.go
- pkg/preflights/host-preflight.yaml
Didn't change any of the host preflights, just reordered them and changed some names and messages.
Changed the spinner output when host preflights fail/warn, and wrapped the error one less time when host preflights didn't succeed.
> Update wording for host preflights

- pkg/goods/support/host-support-bundle.yaml
bringing in some of the relevant collectors from https://github.com/replicatedhq/troubleshoot-specs/blob/main/host/default.yaml
> get apiserver & etcd certificates and their http health checks

- .github/workflows/image-deps-updater.yaml
- .github/workflows/update-addons.yaml
- Makefile
- cmd/buildtools/addon.go
- cmd/buildtools/k0s.go
- cmd/buildtools/main.go
- cmd/buildtools/openebs.go
- cmd/buildtools/registry.go
- cmd/buildtools/seaweedfs.go
- cmd/buildtools/utils.go
- cmd/buildtools/velero.go
Manual workflow runs:
https://github.com/replicatedhq/embedded-cluster/actions/runs/10063827939
https://github.com/replicatedhq/embedded-cluster/actions/runs/10063882917
PRs created by running the workflow manually
https://github.com/replicatedhq/embedded-cluster/pull/812
https://github.com/replicatedhq/embedded-cluster/pull/811
> feat: use chainguard for OpenEBS images - feedback

- .github/workflows/image-scan.yaml
Fixes https://github.com/replicatedhq/embedded-cluster/actions/runs/10113369321
> fix: failed to upload sarif file permission denied

- cmd/buildtools/openebs.go
- cmd/buildtools/registry.go
- cmd/buildtools/seaweedfs.go
- cmd/buildtools/utils.go
- cmd/buildtools/velero.go
fixes error
```
failed to mirror velero chart: pull chart velero: download chart: repo vmware-tanzu not found
```
> fix(ci): add back helm repos for client pull

- .github/workflows/automated-prs-manager.yaml
Logic mostly taken from https://github.com/replicatedhq/kots/blob/main/.github/workflows/automated-prs-manager.yaml
> Add automated PRs manager

- .github/workflows/release-prod.yaml
- Makefile
it is included in metadata here
https://github.com/replicatedhq/embedded-cluster/blob/main/pkg/addons/embeddedclusteroperator/static/metadata.yaml#L12
> chore: utils image is no longer built on merge

- pkg/config/images.go
- pkg/config/images_test.go
This image was not proxied
https://github.com/replicatedhq/embedded-cluster/actions/runs/10149241622/job/28063895250
> feat: proxy envoy image

- .github/actions/scan-image/action.yml
- .github/actions/scan-image/image_id.sh
- .github/workflows/image-scan.yaml
> fix(ci): cves are not closed in code scanning alerts

- .github/actions/e2e/action.yml
- e2e/install_test.go
collect everything even in case of success.
> chore: always collect e2e support bundles and recordings

- .github/workflows/ci.yaml
- e2e/install_test.go
add an e2e test with 5 controller nodes in an airgap environment.
> chore: add an e2e test with 5 airgapped nodes

- .github/actions/e2e/action.yml
- .github/actions/git-sha/action.yml
- .github/workflows/ci.yaml
Make the pr commit app version sha match the commit sha.
> fix: make git sha match commit

- .github/actions/e2e/action.yml
- .github/workflows/ci.yaml
- e2e/install_test.go
- e2e/restore_test.go
- e2e/scripts/check-airgap-installation-state.sh
- e2e/scripts/check-airgap-post-ha-state.sh
- e2e/scripts/check-installation-state.sh
- e2e/scripts/check-post-ha-state.sh
- e2e/utils.go
Checks k8s version is as expected after installation and prior to upgrade
> chore(ci): add pre-upgrade k0s verison check to e2e tests

- chainguard.mk
we were hiding the error behind a pipe.
> bug: return failure if unable to push lam image

- pkg/goods/materializer.go
> chore: fix host-support-bundle.yaml permissions

- cmd/buildtools/registry.go
- pkg/addons/registry/static/metadata.yaml
- pkg/addons/registry/static/values-ha.yaml
- pkg/addons/registry/static/values.yaml
Build instructions can be found in [SC-110090](https://app.shortcut.com/replicated/story/110090)
> Build one-off registry 2.8.3 image with apko

- pkg/preflights/host-preflight.yaml
ensure that resolv.conf does not include `nameserver 127.0.0.1` or `nameserver localhost`
> resolv.conf preflight

- pkg/preflights/host-preflight.yaml
Some examples:
This table doesn't work at all and will be fixed later.
> Make preflight messages more specific and actionable

- common.mk
- operator/Makefile
https://github.com/replicatedhq/embedded-cluster/actions/runs/10605716612/job/29395154982
```release-note
```
> fix(ci): operator release fails with "build/chart: No such file or directory

- .github/workflows/ci.yaml
- .github/workflows/release-prod.yaml
- scripts/cache-files.sh
> fix(ci): operator release fails with "buildtools: No such file or directory"

- .github/workflows/ci.yaml
- .github/workflows/release-prod.yaml
- operator/Makefile
- scripts/cache-files.sh
- scripts/create-previous-k0s-release.sh
- scripts/create-upgrade-release.sh
https://github.com/replicatedhq/embedded-cluster/actions/runs/10606162341/job/29396444713
```release-note
```
> fix(ci): operator release fails with "chart not found"

- .github/workflows/release-prod.yaml
https://github.com/replicatedhq/embedded-cluster/actions/runs/10619959546/job/29438806565
```release-note
```
> fix(ci): operator release fails with "unbound variables"

- e2e/cluster/cluster.go
We are seeing a lot of flakes in our test where outbound requests fail. Im hoping that this makes things a little better.
```release-note
```
> fix(e2e): wait for internet to succeed multiple times

- .github/workflows/ci.yaml
- e2e/cluster/cluster.go
- e2e/proxy_test.go
- e2e/scripts/install-and-configure-squid.sh
- e2e/utils.go
- operator/charts/embedded-cluster-operator/templates/embedded-cluster-operator-deployment.yaml
- operator/charts/embedded-cluster-operator/values.yaml
- operator/charts/embedded-cluster-operator/values.yaml.tmpl
- pkg/addons/adminconsole/static/metadata.yaml
- pkg/addons/applier.go
- pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
implement e2e test for mitm proxy installations.
> chore: implement e2e for mitm proxy installations

- README.md
Adds details around how to setup a development environment for Embedded Cluster.
[SC-111503](https://app.shortcut.com/replicated/story/111503)
NONE
```release-note
NONE
```
NONE
> Add development section to README.md

- README.md
Updates the README for developing kotsadm web / api components
NONE
```release-note
NONE
```
NONE
> Update kotsadm dev readme

- .github/actions/e2e/action.yml
- .github/actions/setup-melange/action.yml
- .github/workflows/ci.yaml
- .github/workflows/image-scan.yaml
- .github/workflows/release-prod.yaml
> chore(ci): do not setup go twice

- Makefile
- fio/Dockerfile
> chore(ci): cache fio builds

- scripts/ci-build-bin.sh
NONE
```release-note
NONE
```
NONE
> Fix arm64 upgrades for dev env

- README.md
> Update Dev requirements

- README.md
NONE
```release-note
NONE
```
NONE
> Separate command blocks in dev README

- README.md
NONE
```release-note
NONE
```
NONE
> Update dev SSH README

- .gitignore
This provides a local gitignored directory for local dev files such as licenses and environment setup files.
```release-note
```
> add local-dev dir to gitignore

- cmd/buildtools/k0s.go
> fix(ci): build fails with no component found for metrics-server

- e2e/install_test.go
This should speed up the end of tests by a few minutes, particularly the 5 node upgrade test
```release-note
```
> generate after-completion support bundles in parallel

- dagger/localartifactmirror.go
- dagger/operator.go
> fix(ci): apko login mounting wrong auth dir

- README.md
Documents the ability to manage kotsadm web packages in the dev env
[SC-112746](https://app.shortcut.com/replicated/story/112746)
NONE
```release-note
NONE
```
NONE
> Document ability to manage kotsadm web packages in the dev env

- Makefile
> chore(dev): rebuild release

- Makefile
> chore: Bump troubleshoot version

- pkg/addons/adminconsole/static/metadata.yaml
Updates admin console chart to 1.117.3-build.1
NONE
```release-note
NONE
```
NONE
> update admin console chart to 1.117.3-build.1

- cmd/embedded-cluster/reset.go
- pkg/preflights/host-preflight.yaml
> Minor wording tweaks for consistency

- .github/workflows/distros.yaml
- dev/distros/Makefile
Build both amd64 and arm64 distro images
NONE
```release-note
NONE
```
NONE
> build arm64 distro images

- Makefile
> fix(ci): indicate patched k0s with ec suffix

- dev/distros/dockerfiles/almalinux-8.Dockerfile
- dev/distros/dockerfiles/debian-bookworm.Dockerfile
- dev/distros/dockerfiles/ubuntu-jammy.Dockerfile
Installs the `expect` package as part of the dev/test images.
NONE
```release-note
NONE
```
NONE
> install expect package in dev/test images

- .github/workflows/release-k0s-patch.yaml
Checkout and build k0s from tags and push to staging bucket for use in release.
```release-note
```
> chore(ci): automate k0s patches

- .github/workflows/release-k0s-patch.yaml
- Makefile
> fix(ci): correct bucket for upload k0s binaries

- dev/distros/entrypoint.sh
Disables unnecessary flaky systemd services
NONE
```release-note
NONE
```
NONE
> Disable unnecessary flaky systemd services

- operator/charts/embedded-cluster-operator/templates/embedded-cluster-logs-collector.yaml
This fixes the host k0scontroller and k0sworker collector daemonsets.
```release-note
```
> Fix the k0scontroller and k0sworker logs collector

- operator/charts/embedded-cluster-operator/templates/embedded-cluster-logs-collector.yaml
- pkg/goods/support/host-support-bundle.tmpl.yaml
> collect local-artifact-mirror service logs

- e2e/scripts/check-airgap-installation-state.sh
- e2e/scripts/check-airgap-post-ha-state.sh
- e2e/scripts/check-installation-state.sh
- e2e/scripts/check-post-ha-state.sh
- e2e/scripts/check-postupgrade-state.sh
- e2e/scripts/common.sh
> chore(ci): check pods not crashlooping in e2e tests

- e2e/airgap.go
retry airgap download in e2e tests on failure
https://github.com/replicatedhq/embedded-cluster/actions/runs/11448543871/job/31852821185?pr=1356
```release-note
```
> chore(ci): improve airgap bundle download resilience in e2e tests with retry

- .github/workflows/ci.yaml
- .github/workflows/dependencies.yaml
https://github.com/replicatedhq/embedded-cluster/actions/runs/11452427312/job/31863302993?pr=1329
```
touch pkg/goods/bins/local-artifact-mirror
curl: (22) The requested URL returned error: 403
curl: (22) The requested URL returned error: 403
curl: (22) The requested URL returned error: 403
curl: (22) The requested URL returned error: 403
curl: (22) The requested URL returned error: 403
curl: (22) The requested URL returned error: 403
curl: (22) The requested URL returned error: 403
curl: (22) The requested URL returned error: 403
curl: (22) The requested URL returned error: 403
curl: (22) The requested URL returned error: 403
curl: (22) The requested URL returned error: 403
curl: (22) The requested URL returned error: 403
make output/bins/fio--amd64
```
```release-note
```
> fix(ci): avoid github rate limits

- cmd/embedded-cluster/provider.go
- cmd/embedded-cluster/reset.go
- cmd/embedded-cluster/shell.go
- pkg/defaults/provider.go
Follow up to [this](https://github.com/replicatedhq/embedded-cluster/pull/1356)
[sc-114572]
```release-note
```
> fix: worker reset fails with incorrect data directory

- .github/workflows/ci.yaml
- e2e/install_test.go
- e2e/scripts/check-airgap-installation-state.sh
- e2e/scripts/check-airgap-post-ha-state.sh
- e2e/scripts/check-installation-state.sh
- e2e/scripts/check-post-ha-state.sh
> chore(ci): re-promote 1.8.0 release each time

- operator/deploy/melange.tmpl.yaml
- operator/pkg/charts/charts.go
- operator/pkg/charts/charts_test.go
- pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
> fix operator binary metadata path

- operator/deploy/melange.tmpl.yaml
- operator/pkg/charts/charts.go
- operator/pkg/charts/charts_test.go
> fix mismatch between admin console and embedded cluster versions

- operator/pkg/upgrade/installation.go
> update error message for repeated installation status failures

- cmd/embedded-cluster/support_bundle.go
we should use --kubeconfig flag instead.
> chore: stop using environment

- cmd/embedded-cluster/network.go
- cmd/embedded-cluster/proxy.go
- pkg/preflights/host-preflight.yaml
Makes some host preflight wording consistent. Updates the CIDR messages.
NONE
```release-note
NONE
```
NONE
> update some wording

- cmd/embedded-cluster/support_bundle.go
NONE
```release-note
NONE
```
NONE
> Update support bundle wording

- cmd/embedded-cluster/admin_console.go
NONE
```release-note
NONE
```
NONE
> Show password as argument in usage

- .github/actions/e2e/action.yml
- .github/workflows/ci.yaml
- e2e/install_test.go
- e2e/kots-release-install-stable/cluster-config.yaml
- e2e/kots-release-install-stable/config.yaml
- e2e/kots-release-install-stable/deployment-2.yaml
- e2e/kots-release-install-stable/deployment.yaml
- e2e/kots-release-install-stable/k8s-app.yaml
- e2e/kots-release-install-stable/kots-app.yaml
- e2e/kots-release-install-stable/kots-lint-config.yaml
- e2e/kots-release-install-stable/preflight.yaml
- e2e/kots-release-install-stable/troubleshoot.yaml
- e2e/utils.go
Adds the following tests that test an upgrade from the previous stable version to the version built for the pull request:
TestSingleNodeUpgradePreviousStable
TestMultiNodeAirgapUpgradePreviousStable
```release-note
```
> chore(ci): e2e test previous stable release

- cmd/local-artifact-mirror/artifact.go
- operator/pkg/artifacts/artifacts.go
We should be reusing the transport so connections can be reused.
```release-note
```
> fix: possibly leaking connections

- .github/actions/e2e/action.yml
- .github/workflows/ci.yaml
- .github/workflows/release-prod.yaml
- e2e/install_test.go
- e2e/proxy_test.go
- e2e/restore_test.go
- e2e/scripts/check-postupgrade-state.sh
- e2e/utils.go
This PR adds airgap testing of tagged releases, including installation, node joins, and upgrades from the previous embedded cluster version.
```release-note
```
> automated postrelease testing

- dev/distros/entrypoint.sh
> fix(ci): e2e test fails ntp preflight

- e2e/cluster/docker/cluster.go
- e2e/cluster/docker/container.go
- e2e/cluster/lxd/cluster.go
- e2e/scripts/collect-support-bundle-cluster.sh
Fallback support bundle fails in airgap
https://github.com/replicatedhq/embedded-cluster/actions/runs/11705855885/job/32602343269?pr=1461#step:4:8986
```release-note
```
> fix(ci): collect fallback cluster support bundle in airgap

- pkg/preflights/host-preflight.yaml
Reverts replicatedhq/embedded-cluster#1449
> Revert "feat: add preflight for ip forwarding"

- .github/workflows/release-prod.yaml
> promote the current EC version to the stable channel on release

- README.md
> Mention SeaweedFS in readme

- e2e/kots-release-install/cluster-config.yaml
- e2e/kots-release-upgrade/cluster-config.yaml
- e2e/scripts/airgap-prepare.sh
- e2e/scripts/check-postupgrade-state.sh
> bump chart version of ingress-nginx to 4.11.3/4.12.0-beta.0

- Makefile
- go.mod
- go.sum
bumps troubleshoot to include a fix for URIs in specs
```release-note
```
> [chore] bump troubleshoot

- cmd/installer/cli/join_runpreflights.go
Related to - https://github.com/replicatedhq/embedded-cluster/pull/1567 - right now when running `join run-preflights` we're checking for the presence of `*cidr` flags which isn't something we do for the regular `join` command. This fixes that logic to match what we do on `join`:
- https://github.com/replicatedhq/embedded-cluster/blob/cbdc74fd4756a409cad10a49c4989fe786f0b243/cmd/installer/cli/join.go#L159-L171
https://app.shortcut.com/replicated/story/116682/join-run-preflights-cmd-is-currently-broken-due-to-missing-flags
The plan is to have a `dryrun` test for join commands which has been built in - https://github.com/replicatedhq/embedded-cluster/pull/1554 - as a follow up once we land that PR in.
```release-note
NONE
```
NONE
> fix(cli): join run-preflights should not use cidr flags but on instaled state

- cmd/installer/cli/install.go
- cmd/installer/cli/install2.go
- pkg/preflights/run.go
some refactoring of install2 command to make it a little more readable and testable
> refactor install2

- cmd/installer/cli/adminconsole_resetpassword.go
- cmd/installer/cli/install.go
- cmd/installer/cli/install2.go
- cmd/installer/cli/join.go
- cmd/installer/cli/join_runpreflights.go
- cmd/installer/cli/materialize.go
- cmd/installer/cli/reset.go
- cmd/installer/cli/restore.go
- cmd/installer/cli/shell.go
- cmd/installer/cli/supportbundle.go
- cmd/installer/cli/update.go
- cmd/installer/cli/version.go
- cmd/installer/cli/version_embeddeddata.go
- cmd/installer/cli/version_listimages.go
- cmd/installer/cli/version_metadata.go
With this PR:
```
marc@lab01:~$ sudo ./my-app install2 --license ./license.yaml
? Set the Admin Console password (minimum 6 characters): ********
? Confirm the Admin Console password: ********
✗  2 host preflights failed
•  IP forwarding must be enabled. To enable it, edit /etc/sysctl.conf, add or uncomment the line 'net.ipv4.ip_forward=1', and run 'sudo
sysctl -p'.
•  Network communication between the pods network CIDR 10.244.0.0/17 and the services network CIDR 10.244.128.0/17 is currently disrupted
on this node. This issue may prevent pods from properly interacting with services. To resolve this, please review and adjust the
firewall configuration on this node to ensure it allows traffic between these network CIDRs.
Please address these issues and try again. …
```
> Clean up error output in cobra

- cmd/installer/cli/install.go
- cmd/installer/cli/install2.go
Make some wording updates to the help texts for a few flags
NONE
```release-note
NONE
```
NONE
> Update some flags' help texts

- cmd/buildtools/velero.go
https://github.com/replicatedhq/embedded-cluster/actions/runs/12301523074
```release-note
```
> chore(ci): fix velero 1.15 addon update

- .github/actions/e2e/action.yml
> chore(ci): free disk space on large runners

- .github/dependabot.yml
> chore(ci): add utils and dagger gomods to dependabot.yml

- .github/dependabot.yml
Cleans this up
```release-note
```
> chore(ci): group some dependabot gomod deps

- operator/charts/embedded-cluster-operator/troubleshoot/cluster-support-bundle.yaml
Story details: https://app.shortcut.com/replicated/story/117738
> feat: [sc-117738] detect "plugin/forward: no nameservers found" from support bundles

- cmd/installer/cli/restore.go
> Make restore fail messages more user-facing

- cmd/manager/start.go
- pkg/manager/install.go
- tests/integration/manager/Makefile
- tests/integration/manager/install_test.go
> fix(ci): fix manager integration test

- pkg/release/addon.go
> update addon2 image metadata when relevant

- cmd/installer/cli/install2.go
- e2e/scripts/single-node-install2.sh
This was a feature of install1 that was implemented after install2 was forked from it.
```release-note
```
> copy license file to data dir in install2 like install1

- cmd/installer/cli/install.go
- cmd/installer/cli/install2.go
- operator/controllers/installation_controller.go
- pkg/addons2/embeddedclusteroperator/prepare.go
- pkg/helm/client.go
- pkg/helm/client_test.go
- pkg/kubeutils/kubeutils.go
> move all installs to v2

- pkg/spinner/spinner.go
- pkg/spinner/spinner_test.go
Makes CI output easier to read
```release-note
```
> chore: no spinner if no terminal

- cmd/installer/cli/install.go
- cmd/installer/cli/join.go
- cmd/installer/cli/join2.go
> replace join with join2

- cmd/buildtools/embeddedclusteroperator.go
- e2e/cluster/docker/utils.go
- e2e/utils.go
- pkg/addons2/seaweedfs/types.go
> chore: remove dead code

- pkg/kubeutils/kubeutils.go
> chore(ci): fix TestGetInstallation migrate data dirs

- operator/charts/embedded-cluster-operator/troubleshoot/cluster-support-bundle.yaml
We are moving the upgrade job to the kotsadm namespace. We need this for debugging.
```release-note
```
> feat(v2): upgrade job support bundle

- operator/pkg/artifacts/registry.go
- pkg/addons2/adminconsole/adminconsole.go
- pkg/addons2/adminconsole/install.go
- pkg/addons2/adminconsole/upgrade.go
- pkg/addons2/embeddedclusteroperator/embeddedclusteroperator.go
- pkg/addons2/embeddedclusteroperator/install.go
- pkg/addons2/embeddedclusteroperator/upgrade.go
- pkg/addons2/registry/install.go
- pkg/addons2/registry/registry.go
- pkg/addons2/registry/upgrade.go
- pkg/addons2/seaweedfs/install.go
- pkg/addons2/seaweedfs/seaweedfs.go
- pkg/addons2/seaweedfs/upgrade.go
- pkg/helm/client.go
- pkg/helm/images.go
- pkg/helm/mock_client.go
> feat(v2): support for restore

- e2e/scripts/check-postupgrade-state.sh
> check chart contents directly instead of using k0s chart object

- cmd/installer/cli/restore2.go
- e2e/install_test.go
- e2e/restore_test.go
- e2e/scripts/restore-multi-node-airgap-phase2.exp
- e2e/scripts/restore-multi-node-phase2.exp
- pkg/addons2/highavailability.go
> feat(v2): restore ha

- cmd/buildtools/adminconsole.go
- cmd/buildtools/embeddedclusteroperator.go
- cmd/buildtools/metadata.go
- cmd/buildtools/openebs.go
- cmd/buildtools/registry.go
- cmd/buildtools/seaweedfs.go
- cmd/buildtools/utils.go
- cmd/buildtools/velero.go
- cmd/installer/cli/install2.go
- cmd/installer/cli/join2.go
- cmd/installer/cli/restore2.go
- operator/pkg/cli/upgrade_job.go
- operator/pkg/upgrade/upgrade.go
- pkg/addons2/highavailability.go
- pkg/addons2/install.go
- pkg/addons2/upgrade.go
- pkg/dryrun/dryrun.go
- pkg/extensions/install.go
- pkg/helm/client.go
- pkg/helm/interface.go
- tests/dryrun/install_test.go
> chore(v2): mock helm client factory

- operator/pkg/cli/migratev2/installation.go
- operator/pkg/cli/migratev2/migrate.go
- operator/pkg/upgrade/upgrade.go
- pkg/addons2/upgrade.go
- pkg/extensions/upgrade.go
Simplify code by not relying on defer and recover.
```release-note
```
> chore(v2): refactor defers

- cmd/installer/cli/adminconsole_resetpassword.go
Pixee had to reset the Admin Console password but didn't want the password in their terminal history. Now, if you don't provide the password on the command line, you'll be prompted for one.
https://github.com/user-attachments/assets/0b519ab2-142f-4191-8282-64e77f43e1f8
https://app.shortcut.com/replicated/story/118848/prompt-for-password-if-not-provided-to-admin-console-reset-password-so-that-the-password-isn-t-in-terminal-history
NONE
```release-note
If you don't provide a new Admin Console password to `admin-console reset-password`, you'll be prompted for one. This prevents the password from ending up in your terminal history.
```
NONE
> Prompt for admin console password if not provided

- .github/workflows/release-prod.yaml
- e2e/install_test.go
> fix onrelease ci process

- cmd/installer/cli/install.go
> feat(v2): add back config values file validation

- cmd/installer/cli/install.go
> fix(v2): air gap with space

- deploy/images/seaweedfs/apko.tmpl.yaml
> fix(seaweedfs): new seaweedfs-bucket-hook requires wget

- pkg/addons/registry/static/metadata.yaml
update the registry image with one we built a one-off of to fix cves
```release-note
NONE
```
NONE
> update registry image to fix cves

- deploy/images/seaweedfs/apko.tmpl.yaml
> fix(seaweedfs): busybox wget required

- .github/workflows/image-deps-updater.yaml
- .github/workflows/update-addons.yaml
- deploy/images/seaweedfs/apko.tmpl.yaml
Due to flakiness in newest version
```release-note
```
> fix(seaweedfs): pin to version 3.79

- .github/workflows/image-deps-updater.yaml
- .github/workflows/update-addons.yaml
NONE
```release-note
NONE
```
NONE
> Pin seaweedfs to 3.79

- cmd/installer/cli/install.go
> remove 'Types created!' line

- .github/workflows/release-prod.yaml
- e2e/scripts/common.sh
- e2e/scripts/vandoor-prepare.sh
Possibly make CI more resilient to network blips and staging deploys
```release-note
```
> chore(ci): retry network requests

- pkg/config/config.go
- pkg/helpers/systemd/dbus.go
```release-note
Fixes an issue when installing on Amazon Linux 2 and other older Linux distributions that causes the installation to timeout waiting for storage to be ready.
```
> fix: support for amazon linux 2

- pkg/preflights/host-preflight.yaml
Make SELinux and sysctl preflights actionable, clear, and concise.
NONE
```release-note
NONE
```
NONE
> Update wording for some host preflights

- cmd/installer/cli/materialize.go
> embedded-cluster materialize should not be listed in the help output

- e2e/cluster/docker/cluster.go
- e2e/cluster/lxd/cluster.go
Speed up e2e tests
```release-note
```
> chore(ci): concurrent node create

- e2e/scripts/join-ha.exp
> add eof handling and extra timeout to enable-ha expect script

- kinds/apis/v1beta1/config_types.go
- operator/charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
- operator/config/crd/bases/embeddedcluster.replicated.com_configs.yaml
- operator/config/crd/bases/embeddedcluster.replicated.com_installations.yaml
- pkg/addons/adminconsole/adminconsole.go
- pkg/addons/adminconsole/values.go
- pkg/addons/highavailability.go
- pkg/addons/install.go
- pkg/addons/upgrade.go
Passes custom domains as admin console chart values.
```release-note
```
> feat(adminconsole): support for custom domains

- operator/Makefile
- operator/schemas/config-embeddedcluster-v1beta1.json
> feat(customdomains): update json schema

- e2e/kots-release-install-failing-preflights/cluster-config.yaml
- e2e/kots-release-install-legacydr/cluster-config.yaml
- e2e/kots-release-install-stable/cluster-config.yaml
- e2e/kots-release-install-warning-preflights/cluster-config.yaml
- e2e/kots-release-install/cluster-config.yaml
- e2e/kots-release-upgrade/cluster-config.yaml
- e2e/proxy_test.go
- e2e/restore_test.go
- e2e/scripts/install-and-configure-squid.sh
> feat(customdomains): use proxy service for charts

- dagger/go.mod
- dev/dockerfiles/local-artifact-mirror/Dockerfile.ttlsh
- dev/dockerfiles/operator/Dockerfile.local
- dev/dockerfiles/operator/Dockerfile.ttlsh
- kinds/go.mod
- utils/go.mod
Fixes the dev build by using go 1.24 across the project
NONE
```release-note
NONE
```
NONE
> Use go 1.24

- scripts/ci-embed-release.sh
> embed default domains in CI test releases

- e2e/scripts/enable-squid-whitelist.sh
- e2e/scripts/install-and-configure-squid.sh
> chore(proxy): fix bad squid conf

- e2e/kots-release-install-stable/nginx-app-helm-v1beta2.yaml
> Fix previous-stable ci test

- e2e/proxy_test.go
- e2e/restore_test.go
- e2e/scripts/enable-squid-whitelist.sh
Fail if TCP_DENIED in squid access logs
```release-note
```
> chore(customdomains): fail on TCP_DENIED

- cmd/installer/cli/install.go
- cmd/installer/cli/join.go
- cmd/installer/cli/signal.go
- cmd/installer/cli/signal_test.go
Report failures on ctrl+c
```release-note
```
> feat: handle ctrl+c in reporting

- .github/workflows/ci.yaml
- .github/workflows/image-deps-updater.yaml
- .github/workflows/release-prod.yaml
> use ubuntu-latest not ubuntu-20.04

- pkg/config/config.go
> sort the node role labels to make tests consistent

- cmd/installer/cli/install.go
- cmd/installer/cli/join.go
- cmd/installer/cli/metrics.go
- cmd/installer/cli/signal.go
- cmd/installer/cli/signal_test.go
- pkg/metrics/reporter.go
- pkg/metrics/types/types.go
> fix: ctrl+c handler should not report failure event

- cmd/installer/cli/reset.go
> don't error on reset when nothing was wrong, continued

- go.mod
- kinds/go.mod
- tests/dryrun/Dockerfile
- utils/go.mod
Fixes issue with CI
```
/usr/bin/tar: ../../../go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.1.linux-amd64/src/internal/trace/internal/oldtrace/testdata/stress_1_11_good: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.1.linux-amd64/src/internal/trace/internal/oldtrace/testdata/user_task_region_1_19_good: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.1.linux-amd64/src/internal/trace/internal/oldtrace/testdata/stress_start_stop_1_11_good: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.1.linux-amd64/src/internal/trace/internal/oldtrace/testdata/stress_start_stop_1_21_good: Cannot open: File exists
/usr/bin/tar: …
```
> chore: update go to 1.24.1

- cmd/installer/cli/adminconsole_resetpassword.go
better leverage cobra
```release-note
```
> chore: cli reset-password command should use cobra validation

- cmd/local-artifact-mirror/artifact.go
- cmd/local-artifact-mirror/cli.go
- cmd/local-artifact-mirror/main.go
- cmd/local-artifact-mirror/pull.go
- cmd/local-artifact-mirror/pull_binaries.go
- cmd/local-artifact-mirror/pull_helmcharts.go
- cmd/local-artifact-mirror/pull_images.go
- cmd/local-artifact-mirror/pull_images_test.go
- cmd/local-artifact-mirror/root.go
- cmd/local-artifact-mirror/serve.go
- cmd/local-artifact-mirror/serve_test.go
- cmd/local-artifact-mirror/testing.go
- e2e/install_test.go
- pkg/helpers/fs.go
- pkg/kubeutils/installation.go
- unifies flags and config logic
- adds some unit tests
```release-note
```
> chore: lam improvements

- e2e/install_test.go
- e2e/restore_test.go
- e2e/shared.go
- e2e/unsupported-overrides_test.go
E2E tests code refactoring and cleanup
```release-note
NONE
```
NONE
> E2E tests refactoring and cleanup

- pkg/addons/adminconsole/values.go
- tests/dryrun/install_test.go
Mount the k0s data directory into the kots deployment.
[SC-122568](https://app.shortcut.com/replicated/story/122568)
Yes
```release-note
NONE
```
NONE
> Mount the k0s data directory into the kots deployment

- pkg/airgap/materialize.go
- pkg/airgap/version.go
- pkg/tgzutils/tgz.go
Leaking resources
```release-note
```
> chore: close gzip readers

- cmd/installer/cli/join.go
- cmd/installer/cli/reset.go
- cmd/installer/cli/restore.go
- cmd/installer/cli/shell.go
- cmd/installer/cli/supportbundle.go
- cmd/installer/cli/update.go
small updates to the command help texts, and fixes an issue where we printed out %s
> improve cli help text

- e2e/cluster/cmx/cluster.go
> chore(ci): cmx log node and network id for debugging purposes

- .github/workflows/ci.yaml
Fixes running TestFiveNodesAirgapUpgrade on merge
```release-note
NONE
```
NONE
> Fix running TestFiveNodesAirgapUpgrade

- .github/actions/e2e-cmx-setup/action.yml
- .github/actions/e2e/action.yml
- .github/workflows/ci.yaml
- .github/workflows/release-prod.yaml
- e2e/cluster/cmx/cluster.go
> chore(ci): use new replicated vm create --ssh-public-key flag

- cmd/installer/cli/install.go
> chore: remove unused code

- e2e/cluster/cmx/cluster.go
This is to avoid a race condition in CMX where the network bridge isn't added to all nodes when creating nodes in parallel.
Yes
```release-note
NONE
```
NONE
> Create CMX nodes sequentially

- cmd/installer/cli/install.go
> chore: rename flag to --manager-experience

- cmd/installer/cli/cidr.go
- e2e/cluster/cmx/cluster.go
- e2e/cluster/docker/cluster.go
- e2e/cluster/lxd/cluster.go
- e2e/install_test.go
- e2e/proxy_test.go
- e2e/restore_test.go
- operator/pkg/artifacts/upgrade_test.go
- pkg/addons/embeddedclusteroperator/crds_test.go
- pkg/kubeutils/ensure_test.go
- correct playwright errors and stdout/stderr
- better cleanup of cmx node and network
- tests too verbose
- remove unused code
```release-note
```
> chore: various fixes

- pkg/addons/install.go
- pkg/addons/upgrade.go
- pkg/addons/velero/integration/hostcabundle_test.go
- pkg/addons/velero/integration/k0ssubdir_test.go
- pkg/addons/velero/static/metadata.yaml
- pkg/addons/velero/static/values.tpl.yaml
- pkg/addons/velero/values.go
- pkg/addons/velero/values_test.go
- pkg/addons/velero/velero.go
- tests/dryrun/install_test.go
[sc-124201]
```release-note
```
> chore(velero): update version to 1.16

- Makefile
> Bump e2e test timeouts to 70m

- e2e/playwright/tests/deploy-upgrade/test.spec.ts
Fixes some flakiness on upgrade tests due to short timeouts.
```release-note
NONE
```
NONE
> Increase preflight initial load timeout on upgrade

- e2e/cluster/cmx/cluster.go
Waits for SSH to be available on CMX node before running ssh commands.
```release-note
NONE
```
> Wait for SSH to be available on CMX node

- e2e/cluster/cmx/cluster.go
Log stdout and stderr if ssh isn't available for easier debuggability.
```release-note
NONE
```
NONE
> Log stdout and stderr if ssh isn't available

- api/api.go
- api/controllers/install/installation.go
- api/internal/managers/installation/store.go
- api/internal/managers/preflight/hostpreflight.go
- cmd/installer/cli/api.go
- cmd/installer/cli/api_test.go
- cmd/installer/cli/install.go
- operator/charts/embedded-cluster-operator/Chart.yaml
- pkg/helpers/fs_test.go
Addresses some of the feedback from this this PR: https://github.com/replicatedhq/embedded-cluster/pull/2234
NONE
```release-note
NONE
```
NONE
> Address feedback from new API preflights PR

- api/integration/install_test.go
> chore(ci): fix flakey test TestConfigureInstallation

- .github/dependabot.yml
> chore(ci): add pacakge-ecosystem npm for web and playwright directories

- cmd/installer/cli/enable_ha.go
- cmd/installer/cli/install.go
- cmd/installer/cli/join.go
- cmd/installer/cli/restore.go
- operator/pkg/upgrade/upgrade.go
- pkg/addons/highavailability.go
- pkg/addons/highavailability_test.go
- pkg/addons/install.go
- pkg/addons/install_test.go
- pkg/addons/interface.go
- pkg/addons/mock.go
- pkg/addons/upgrade.go
- pkg/addons/upgrade_test.go
- pkg/addons/util.go
- pkg/addons/util_test.go
- pkg/dryrun/dryrun.go
- pkg/dryrun/kubeutils.go
- pkg/dryrun/types/types.go
- pkg/kubeutils/client.go
- pkg/kubeutils/interface.go
- tests/integration/kind/registry/ha_test.go
Creates an interface for the addons package to make it easier to consume and test in the API.
Part of [SC-124778](https://app.shortcut.com/replicated/story/124778)
```release-note
NONE
```
NONE
> Create an interface for the addons package

- cmd/installer/cli/api.go
- cmd/installer/cli/install.go
- pkg-new/cloudutils/cloudutils.go
- pkg-new/cloudutils/interface.go
- pkg-new/cloudutils/mock.go
- pkg-new/cloudutils/publicip.go
- pkg-new/cloudutils/publicip_test.go
- pkg/netutils/ips.go
- pkg/netutils/ips_test.go
> chore: pkg-new cloudutils.TryDiscoverPublicIP

- web/src/components/wizard/SetupStep.tsx
- web/src/contexts/AuthContext.tsx
https://app.shortcut.com/replicated/story/124918/ui-should-handle-401-errors
https://www.loom.com/share/99fa2cabb817490bb4f0744a66fe39f3?sid=739b41cb-10ed-4b76-8392-86c187c88271
```release-note
```
> Fix 401 bug 

- web/src/components/wizard/SetupStep.tsx
- web/src/components/wizard/tests/SetupStep.test.tsx
Expand them automatically if an error is present in there but it's currently collapsed.
https://www.loom.com/share/d4844f2fb94b4f3fabfc2bd5d771dc8a?sid=090a7850-a7a2-4835-9669-2ae2714c7610
> Collapse advanced settings by default

- api/integration/install_test.go
- cmd/installer/cli/install.go
https://www.loom.com/share/46ac290812464bd8a329dfce7c599f0d?sid=1561ab7b-4257-4583-aba7-fb268ecada64
> prompt if manager will use self-signed cert

- api/api.go
- api/handlers.go
- api/routes.go
Un-export certain API types and functions
No
```release-note
NONE
```
NONE
> Unexport certain API types and functions

- cmd/installer/cli/cidr.go
- cmd/installer/cli/cidr_test.go
- cmd/installer/cli/flags.go
- cmd/installer/cli/install.go
- cmd/installer/cli/proxy_test.go
> feat(v3): customize install command help output based on targets

- web/src/components/wizard/tests/ValidationStep.test.tsx
Flake in our CI - https://github.com/replicatedhq/embedded-cluster/actions/runs/15905824522/job/44860371051?pr=2337#step:6:508
CI test flake
It's a test :)
```release-note
NONE
```
NONE
> chore(test): fix web unit test flake

- web/src/components/common/Button.tsx
- web/src/components/wizard/InstallWizard.tsx
- web/src/components/wizard/StepNavigation.tsx
- web/src/components/wizard/completion/KubernetesCompletionStep.tsx
- web/src/components/wizard/completion/LinuxCompletionStep.tsx
- web/src/components/wizard/installation/KubernetesInstallationStep.tsx
- web/src/components/wizard/setup/KubernetesSetupStep.tsx
- web/src/components/wizard/setup/LinuxSetupStep.tsx
- web/src/components/wizard/tests/KubernetesCompletionStep.test.tsx
- web/src/components/wizard/tests/KubernetesInstallationStep.test.tsx
- web/src/components/wizard/tests/KubernetesSetupStep.test.tsx
- web/src/components/wizard/tests/LinuxCompletionStep.test.tsx
- web/src/components/wizard/tests/LinuxSetupStep.test.tsx
- web/src/components/wizard/tests/StepNavigation.test.tsx
- web/src/test/setup.tsx
- web/src/test/testData.ts
- web/src/types/index.ts
Adds the Kubernetes installation and completion pages
[SC-126013](https://app.shortcut.com/replicated/story/126013)
Yes
```release-note
NONE
```
NONE
> Add Kubernetes installation and completion pages

- kinds/Makefile
- operator/Makefile
- operator/charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
- operator/config/crd/bases/embeddedcluster.replicated.com_configs.yaml
- operator/config/crd/bases/embeddedcluster.replicated.com_installations.yaml
- operator/config/crd/bases/embeddedcluster.replicated.com_kubernetesinstallations.yaml
- pkg/crds/resources.yaml
update deps versions
```release-note
```
> chore(ci): controller-gen version v0.18.0

- .github/dependabot.yml
> chore: dependabot security group only patches

- .github/dependabot.yml
> chore: group dependabot actions

- cmd/installer/cli/install.go
Connects to k8s api-server to validate kubeconfig
```
$ ENABLE_V3=1 output/bin/embedded-cluster install --target kubernetes --license local-dev/license-e
than.yaml --admin-console-password password
ERROR: failed to connect to kubernetes api server: Get "http://localhost:8080/version?timeout=32s": dial tcp [::1]:8080: connect: connection refused
```
```release-note
```
> feat(kubernetes): validate kubeconfig

- operator/Makefile
- operator/charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
- operator/config/crd/kustomization.yaml
- pkg/crds/resources.yaml
> chore(ci): update kustomize to v5.7.0

- e2e/scripts/check-airgap-post-ha-state.sh
> chore(ci): fix ha test

- api/Makefile
With the restructure we stopped running integration tests in CI.
NA
NONE
```release-note
NONE
```
NONE
> fix(ci): run integration tests

- .gitignore
- CLAUDE.md
Adds CLAUDE.md file to improve the experience and accuracy of using claude in the repo.
NONE
```release-note
NONE
```
NONE
> Add CLAUDE.md file

- .github/workflows/ci.yaml
https://github.com/replicatedhq/embedded-cluster/actions/runs/16301745021/job/46037806631?pr=2480
```release-note
```
> chore(ci): github rate limits when running api integration tests

- web/src/components/common/FileInput.test.tsx
- web/src/components/common/FileInput.tsx
- web/src/components/wizard/config/ConfigurationStep.tsx
- web/src/vite.setup.ts
Adds file Config Item Type - Frontend File Input Component]
[SC-126681](https://app.shortcut.com/replicated/story/126681)
Yes
```release-note
NONE
```
NONE
> Add file Config Item Type - Frontend File Input Component

- api/internal/managers/app/config/config.go
Follow up to https://github.com/replicatedhq/embedded-cluster/pull/2491 - based on the feedback provided this reduces the number of helper methods used to build the config values from items and child items.
NA
NONE
```release-note
NONE
```
NONE
> chore(app-manager): cleanup of helper methods

- web/package-lock.json
- web/package.json
Reverts replicatedhq/embedded-cluster#2467
> Revert "build(deps-dev): bump vite from 6.3.5 to 7.0.4 in /web"

- api/pkg/template/engine.go
- api/pkg/template/engine_test.go
- api/pkg/template/license.go
- api/pkg/template/license_test.go
Support for LicenseDockerCfg template function
```release-note
```
> feat(api): LicenseDockerCfg template function support

- web/package-lock.json
- web/package.json
> chore(web): upgrade deps

- .github/workflows/dependencies.yaml
With the fix:
https://github.com/replicatedhq/embedded-cluster/pull/604/files
```release-note
```
> chore(ci): pin k0s upgrade automation to current minor

- api/internal/managers/app/config/config.go
- api/internal/managers/app/config/config_test.go
- e2e/kots-release-install-v3/config.yaml
Changes behavior of hidden required fields to block form submission.
```release-note
```
> feat(api): empty app config hidden required fields should return error

- web/vite.config.ts
Behold the best PR ever.
NONE
NONE
```release-note
NONE
```
NONE
> chore: remove extra `/n`

- .claude/.manifest
- .claude/agents/architecture-patterns.md
- .claude/agents/codebase-analyzer.md
- .claude/agents/codebase-locator.md
- .claude/agents/codebase-pattern-finder.md
- .claude/agents/go-developer.md
- .claude/agents/proposal-needed.md
- .claude/agents/proposal-writer.md
- .claude/agents/proposals-analyzer.md
- .claude/agents/proposals-locator.md
- .claude/agents/researcher.md
- .claude/agents/shortcut.md
- .claude/agents/testing.md
- .claude/agents/web-search-researcher.md
- .claude/commands/implement.md
- .claude/commands/proposal.md
Updated:
- agents/codebase-pattern-finder.md
- agents/architecture-patterns.md
- agents/web-search-researcher.md
- agents/go-developer.md
- agents/proposal-needed.md
- agents/proposals-locator.md
- agents/proposal-writer.md
- agents/shortcut.md
- agents/researcher.md
- agents/testing.md
- agents/proposals-analyzer.md
- agents/codebase-analyzer.md
- agents/codebase-locator.md
- commands/implement.md
- commands/proposal.md
Source: github.com/replicatedhq/.claude
> Update Claude agents and commands

- cmd/buildtools/k0s.go
This PR adds logic back that was mistakenly removed when adding support for 1.33 in order to fix CI failures happening in the k0s-1-31 branch. 
https://app.shortcut.com/replicated/story/127762/add-support-for-kubernetes-1-32-and-1-33-in-ec
```release-note
```
> Pin calico images to version 3.28.0 for k0s < 1.31

- pkg/netutils/nets.go
- pkg/netutils/nets_test.go
my cidr was invalid and i was really confused
```release-note
```
> chore: better error message for non-canonical cidr

- .github/workflows/image-deps-updater.yaml
- .github/workflows/update-addons.yaml
- cmd/buildtools/openebs.go
- cmd/buildtools/utils.go
- cmd/buildtools/velero.go
- e2e/version_test.go
- pkg/addons/openebs/static/metadata.yaml
- pkg/helm/images.go
> chore: use securebuild for openebs images

- cmd/buildtools/k0s.go
- cmd/buildtools/utils.go
- pkg/config/static/metadata-1_31.yaml
- pkg/config/static/metadata-1_32.yaml
- pkg/config/static/metadata-1_33.yaml
> chore: use securebuild for k0s core images

- web/src/components/wizard/InstallWizard.tsx
- web/src/components/wizard/config/ConfigurationStep.tsx
- web/src/components/wizard/installation/UpgradeStep.tsx
- web/src/components/wizard/installation/tests/UpgradeStep.test.tsx
- web/src/components/wizard/tests/ConfigurationStep.test.tsx
- web/src/utils/api-base.ts
Implements V3 Frontend Upgrade App Preflights Step
[SC-129016](https://app.shortcut.com/replicated/story/129016)
Yes
```release-note
NONE
```
NONE
> V3 Frontend Upgrade App Preflights Step

- .github/workflows/ci.yaml
- .github/workflows/distros.yaml
- .github/workflows/image-scan.yaml
- .github/workflows/kinds.yaml
- .github/workflows/release-prod.yaml
- .github/workflows/utils.yaml
The .claude directory is centrally managed elsewhere and does not require another CI review. Ignore .claude directory.
NONE
```release-note
NONE
```
NONE
> ignore .claude in ci
