- Dockerfile
- Makefile
- README.md
- cmd/helmbin/main.go
- go.mod
- inttest/Makefile
- pkg/cli/install.go
- pkg/cli/kubeconfig.go
- pkg/cli/kubectl.go
- pkg/cli/run.go
- pkg/cli/version.go
- pkg/controller/helm.go
- pkg/controller/k0scontroller.go
- pkg/controller/server.go
Now that this repository ownership has been moved to `replicatedhq` org we have to rename all import paths replacing `emosbaugh` by`replicatedhq`.
No functional change has been introduced here.
> chore: renaming imports and project path

- .github/workflows/release.yaml
- .gitignore
- .goreleaser.yaml
Using goreleaser to release. Taking inspiration on what is being used for `troubleshoot` [releases](https://github.com/replicatedhq/troubleshoot/blob/main/deploy/.goreleaser.yaml).
> chore: enable goreleaser.

- pkg/cli/run.go
- pkg/controller/kotsrelease.go
Start to process the embed kots release. The kots release is embed inside the `helmbin` binary as a `tar.gz` file, we need to extract it and create a config map called `kotsadm-application-metadata` in the `default` namespace, this config map contains the kots application CR and is used as means of interface customisation by the kotsadm pod.
Everything here is a no-op if the kots release bundle is not embed inside the binary. This depends on https://github.com/replicatedhq/airgap/pull/113.
> feat: process embed kots release

- cmd/helmvm/install.go
- cmd/helmvm/upgrade.go
- pkg/addons/adminconsole/adminconsole.go
- pkg/addons/applier.go
- pkg/infra/infra.go
With `--no-prompt` command line flag user can control if the installer should or not ask for confirmations. This is specially useful for when we start deploying this as part of the compatibility matrix.
> feat: adding --no-prompt flag

- pkg/addons/adminconsole/adminconsole.go
- pkg/addons/adminconsole/customize.go
- pkg/addons/applier.go
- pkg/addons/openebs/openebs.go
To keep backward compatibility with the previous version of `helmbin` we need to inspect the binary to see if there is any kind of kotsadm customization and if found apply them.
> feat: applying kotsadm customization

- .github/workflows/release-prod.yaml
Bumps all actions to their latest version and parse the tag before pushing the image.
> chore: fix docker build and push github action

- cmd/helmvm/install.go
if k0sctl kubeconfig fails we can't overwrite the kubeconfig file with the error message returned. this commit solves it.
> bug: do not overwrite kubeconfig on error

- .github/workflows/e2e.yaml
- Makefile
- e2e/cluster/cluster.go
- e2e/install_test.go
- e2e/utils.go
> chore: adding more end-to-end tests

- e2e/embed_test.go
- e2e/install_test.go
- e2e/scripts/deploy-with-pvc.sh
improved tests so we can validate openebs is working after the deployment. we now create a deployment mounting a pvc and check it rolls out.
> chore: adding pvc mount test

- .github/workflows/e2e.yaml
- e2e/version_test.go
- pkg/addons/adminconsole/adminconsole.go
- pkg/addons/adminconsole/customize.go
- pkg/addons/applier.go
`helmvm version` should work even without having access to a cluster. prior to this commit version command required a kubernetes client to work properly, this is not a requirement.
> bug: version command should work without cluster access

- .github/workflows/release-prod.yaml
tag_name is not properly processed, we need env.tag_name.
> chore: fixed helmvm builder docker build process

- .github/workflows/release-prod.yaml
this is not mandatory and we are not sure we want to keep developing this. as the push is failing (as far as i could read due to org level permissioning) this commit removes the helmvm builder image build and publish job from the github action.
we can enable it again in the future if we decide this is a goal we want to pursuit.
> chore: disable builder image generation

- Makefile
- cmd/helmvm/install.go
bumps k0s version to kube v1.27.5.
> chore: bump k0s version to kube v1.27.5

- .github/workflows/e2e.yaml
- cmd/helmvm/install.go
- cmd/helmvm/upgrade.go
- cmd/helmvm/version.go
- e2e/embed_test.go
- e2e/install_test.go
- e2e/scripts/addons-only.sh
- e2e/scripts/install-with-disabled-addons.sh
- pkg/addons/applier.go
- pkg/addons/custom/custom.go
- pkg/addons/options.go
- pkg/hembed/hembed.go
to prepare helmvm for kots regression testing we need to give users the ability to deactivate add-on installations. this feature will enable kots to bypass the add-on installation during regression tests. they can then install their current development branch over a clean helmvm setup to conduct their tests.
> feat: allow disabling add-ons

- go.mod
- pkg/defaults/defaults.go
- pkg/defaults/provider.go
- pkg/defaults/provider_test.go
- pkg/ssh/ssh.go
- pkg/ssh/ssh_test.go
This is an ongoing effort. This PR implements unit tests for both `defaults` and `ssh` packages. As I move forward I will be opening new PRs for different packages.
> chore: implementing some unit tests

- cmd/helmvm/install.go
- cmd/helmvm/token.go
- cmd/helmvm/upgrade.go
- pkg/addons/adminconsole/adminconsole.go
- pkg/config/config.go
- pkg/infra/infra.go
it is weird to have logrus warn messages being printed during the installs. this pr replaces them with fmt.print calls.
> feat: replace warn calls with print

- Dockerfile
- go.mod
since go 1.21 we need to specify also the minor go version: https://github.com/golang/go/issues/62278
without it dependabot is failing with:
```
Dependabot encountered the following error:
go: downloading go1.21 (linux/amd64)
go: download go1.21 for linux/amd64: toolchain not available
```
> chore: setting the specific version in go.mod

- .github/workflows/release-dev.yaml
- .github/workflows/release-prod.yaml
bump go to 1.21 on github release actions.
> chore: bump go version on release actions

- cmd/helmvm/install.go
- pkg/config/config.go
- pkg/config/host.go
this commit makes upload binary option to be true only in air gap environments and removes a --force flag reminiscent from a test.
> feat: stop forcing installs and upload binary

- Makefile
- pkg/goods/goods.go
- pkg/preflights/preflights.go
we are including support-bundle binary from now on. this commit also renames the `preflight` binary to `kubectl-preflight` so it properly behaves as a kubectl plugin (same for support-bundle binary).
> feat: including support-bundle binary

- go.mod
- go.sum
- pkg/addons/adminconsole/adminconsole.go
- pkg/addons/adminconsole/customize.go
if a license exists inside the binary we configure admin console to use it. if no license was found deploys admin console as we used to (without license).
> feat: deploying admin console with the embedded license

- Makefile
use `git describe --tags` to set a proper version on development builds (builds from `main` branch).
> chore: sets a version on development build

- .github/workflows/e2e.yaml
- e2e/embed_test.go
- e2e/install_test.go
- e2e/scripts/addons-only.sh
- e2e/scripts/embed-and-install.sh
- e2e/scripts/install-with-disabled-addons.sh
we were not running `apt update` before attempting to install packages and we need to change the way we pull the memcached helmchart (https://github.com/bitnami/charts/issues/19599).
> chore: fix end to end tests

- .github/workflows/e2e.yaml
- e2e/embed_test.go
- e2e/install_test.go
- e2e/scripts/addons-only.sh
- e2e/scripts/embed-and-install.sh
- e2e/scripts/install-with-disabled-addons.sh
apt is not suited for scripting, we must use apt-get instead.
> chore: using apt-get instead of apt

- go.mod
Reverts replicatedhq/helmvm#96
Apparently this has changed in go 1.21
> Revert "go.mod versions cannot specify the patch, only minor"

- e2e/scripts/addons-only.sh
- e2e/scripts/embed-and-install.sh
- e2e/scripts/embedded-preflight.sh
- e2e/scripts/install-with-disabled-addons.sh
- e2e/scripts/multi-node-install.sh
- e2e/scripts/single-node-install.sh
- e2e/scripts/wait-for-ready-nodes.sh
- pkg/defaults/provider.go
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
> store things following XDG standards

- pkg/config/config.go
allows users to bypass providing a ssh key if it has already been loaded / is managed by the ssh agent.
> feat: allow for ssh-agent key management

- go.mod
- go.sum
- pkg/addons/adminconsole/adminconsole.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/host.go
- pkg/config/testdata/override-change-name.yaml
- pkg/config/testdata/override-enable-telemetry.yaml
- pkg/config/testdata/override-setting-ip-forward.yaml
- pkg/config/testdata/override-zero-out-sans-list.yaml
- pkg/customization/customization.go
- pkg/metrics/reporter.go
- pkg/metrics/sender.go
parses and applies the embedded unsupported overrides.
> feat: apply embedded unsupported overrides

- cmd/helmvm/install.go
- pkg/config/config.go
- pkg/config/config_test.go
allow users to provide through the --overrides flag a path to a file containing an embedded cluster configuration object. the file is then read and its unsupported overrides are used to overrides the generated config.
> feat: allow users to provide an embedded cluster config path

- cmd/helmvm/install.go
overrides is a flag that is not supposed to be used often but only in extreme cases. this commit makes it a hidden option.
> feat: hide --overrides flag

- .github/workflows/e2e.yaml
- cmd/helmvm/join.go
- e2e/install_test.go
short tokens are easier and better looking, this pr introduces them into the regular node join workflow.
we do a request to kotsadm passing in the short token and receive back the actual token + some other information, we then write down the token and run the k0s install command.
> feat: using short token instead of k0s token

- pkg/addons/adminconsole/adminconsole.go
This PR switches the yaml marshaller used when reading in the kots license so that it will embed correctly.
> fix admin-console license embedding

- pkg/addons/adminconsole/adminconsole.go
so far kotsadm is only available over http, not https.
> bug: fix wrong url protocol for kotsadm access

- pkg/addons/adminconsole/adminconsole.go
if the timeout is reached but no error happen inside the func lasterr will be nil but err will have the timeout. on this scenario lasterr should be the actual timeout error.
> chore: fix 'timed out waiting for admin console: <nil>'

- pkg/metrics/sender.go
- pkg/metrics/sender_test.go
the old endpoint isn't going to work anymore.
> chore: change metrics endpoint path

- cmd/embedded-cluster/install.go
- e2e/install_test.go
- e2e/scripts/embed-and-install.sh
- e2e/scripts/embedded-preflight.sh
- e2e/scripts/install-with-disabled-addons.sh
- e2e/scripts/single-node-install.sh
- e2e/scripts/zz-scripts.go
during our co-working session this feature has been lost so the command
```
systemctl restart embedded-cluster
```
was failing because the systemd unit file wasn't being created anymore. this commit brings the feature back while also adding it to our e2e tests so we don't loose it anymore.
> bug: bring systemd unit file installation back

- .github/workflows/dependencies.yaml
fetches latest version for all embedded stuff and update them in the makefile. creates a pr at the end.
> chore: create workflow to update makefile dependencies

- .github/workflows/release-dev.yaml
- .github/workflows/release-prod.yaml
- cmd/embedded-cluster/version.go
- pkg/goods/goods.go
whenever a release is built we now publish a metadata json file with a content similar to this:
```json
{
"Versions": {
"AdminConsole": "v1.104.3",
"EmbeddedClusterOperator": "v0.4.1",
"Installer": "v1.28.4+ec.0-dirty",
"Kubernetes": "v1.28.4+k0s.0",
"OpenEBS": "v3.9.0"
},
"K0sSHA": "926bcb68478f0eb5bb8479bf01d39524102346d9f24b9f536aeddf71fdd5a975"
}
```
a new hidden topic has been added to the version topic, this is how we generate the version (or release) metadata:
```
$ embedded-cluster version metadata
{
"Versions": {
"AdminConsole": "v1.104.3",
"EmbeddedClusterOperator": "v0.4.1",
"Installer": "v1.28.4+ec.0-dirty",
"Kubernetes": "v1.28.4+k0s.0",
"OpenEBS": "v3.9.0"
},
"K0sSHA": "926bcb68478f0eb5bb8479bf01d39524102346d9f24b9f536aeddf71fdd5a975"
}
$
```
> feat: start publishing release metadata json file

- pkg/config/host.go
this would save install time when installing on a different host than the embedded-cluster binary, but that is not currently supported
> do not require downloading k0s binaries from the internet

- Makefile
- cmd/embedded-cluster/version.go
- pkg/defaults/defaults.go
if we are using an alternative k0s binary for a release we need to expose this as part of the release metadata. without this we can't make upgrades use the right binary.
the idea here is: if for a given release we need to replace the k0s binary we will create a branch for it and make sure that the makefile points to the right location on the branch. we can then create a tag on such branch and get a release that points to a different location.
for instace: let's suppose we want to override the k0s binary for the next release, we could add a value for K0S_BINARY_SOURCE_OVERRIDE in the makefile, push and tag. this is not optimal as we need to remember to remove the value from K0S_BINARY_SOURCE_OVERRIDE for subsequent releases hence the idea of making this in a tag.
relates to …
> feat: publish alternative k0s url in release metadata

- .github/workflows/pull-request.yaml
- .github/workflows/release-dev.yaml
- .github/workflows/release-prod.yaml
- Makefile
- README.md
- pkg/defaults/provider.go
we are driving far away from the "ssh based installation" so this pr speeds things up by dropping the release of darwin binaries.
> feat: stop building darwin binaries

- cmd/embedded-cluster/join.go
- pkg/config/config.go
- pkg/config/host.go
- pkg/config/testdata/override-change-name.yaml
- pkg/config/testdata/override-enable-telemetry.yaml
- pkg/config/testdata/override-setting-ip-forward.yaml
- pkg/config/testdata/override-zero-out-sans-list.yaml
this PR enables dynamic config. 
The k0s dynamic config feature loads the initial config into the cluster as a `clusterconfig` object. 
https://docs.k0sproject.io/head/dynamic-configuration/
this gives us the following benefits:
- config is no longer centralised 
- can manipulate the config from in-cluster
- k0s config reconciler will enact any config changes made in-cluster without the need to reboot
this enables us to add/update helm charts installed as extensions by bumping thier chart version in the `clusterconfig` object.
> Enable dynamic config

- pkg/config/config.go
- pkg/config/testdata/override-change-name.yaml
- pkg/config/testdata/override-enable-telemetry.yaml
- pkg/config/testdata/override-setting-ip-forward.yaml
- pkg/config/testdata/override-zero-out-sans-list.yaml
make sure we are overriding everything from `k0s` property of the k0sctl config inwards.
> feat: support for unsupported config overrides

- cmd/embedded-cluster/version.go
- pkg/addons/adminconsole/adminconsole.go
- pkg/addons/applier.go
- pkg/addons/custom/custom.go
- pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
- pkg/addons/openebs/openebs.go
This is to inform the embedded-cluster-operator which helm values it's not allowed to override with our defaults when upgrading addons.
> feat: add protected helm values to release metadata

- e2e/scripts/unsupported-overrides.sh
- pkg/addons/applier.go
This will probably break upgrades, but we really shouldn't be placing kotsadm and the operator in the same namespace. As such, the sooner we make the change the better, and I should have done this weeks ago.
> feat: install kotsadm in default namespace, not embedded-cluster

- Makefile
Reverts replicatedhq/embedded-cluster#295
This is to ensure we have an update to test with in the near future
> Revert "Update Makefile versions"

- pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
we don't want to let chart updates overwrite the binary name
> feat: protect binary name

- cmd/embedded-cluster/reset.go
`k0sctl` and `embedded-cluster node join` install k0s binary on /usr/local/bin/k0s. k0s binary is also not accessible for regular users (only root can run it).
> feat: reset should be run as root + k0s path

- cmd/embedded-cluster/reset.go
if kubeclient hasn't been initialised and the user is running with --force we need to report it as an error. we were segfaulting.
> feat: return error if kube client is not initialised

- .github/workflows/pull-request.yaml
- .github/workflows/release-dev.yaml
- .gitignore
- cmd/embedded-cluster/install.go
- cmd/embedded-cluster/join.go
- cmd/embedded-cluster/node.go
- cmd/embedded-cluster/reset.go
- cmd/embedded-cluster/shell.go
- e2e/cluster/cluster.go
- e2e/sudo_test.go
- e2e/utils.go
the following commands now require uid 0 to run:
- install
- shell
- node
the apply command was removed and the version command works just fine as a regular user (uid != 0).
> feat: require uid 0 for install, shell and node commands

- .github/workflows/pull-request.yaml
- .github/workflows/release-dev.yaml
- cmd/embedded-cluster/install.go
- e2e/install_test.go
- e2e/scripts/single-node-install-without-root.sh
now that we only allow installations with root the ssh installation method became a huge problem. we can only install if ssh access is allowed for the root user using a ssh key.
while we work on moving ourselves out of the ssh based installation we need to at least provide the users with valid information on how to work around this issue.
this pr does exactly that, upon finding an "invalid" ssh config this is what is printed on the terminal:
```
rmarasch@ec:~$ sudo ./embedded-cluster install
PermitRootLogin config is set to 'no' in /etc/ssh/sshd_config
This will prevent embedded-cluster from installing.
You can temporarily enable root login by changing the
PermitRootLogin config to 'without-password' and restarting
the sshd service. Once the installation is finished you can
restore the …
```
> feat: check sshd config before starting the install

- pkg/addons/adminconsole/adminconsole.go
- pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
embeddedClusterID should not be overwritten during upgrades or operator reconcile cycles.
> feat: protect embeddedClusterID

- .gitignore
- cmd/embedded-cluster/install.go
- cmd/embedded-cluster/join.go
- pkg/preflights/preflights.go
- pkg/progressbar/progressbar.go
- pkg/progressbar/progressbar_test.go
- add progress bar close with error capabilities.
- print actions to screen instead of to the progress bar.
- add missing entry to .gitignore.
- removed function that used to run preflights remotely (ssh).
- remove duplicated function.
> feat: fix join command output

- e2e/cluster/cluster.go
- e2e/proxy_test.go
this does not do much at this stage other than laying down the pieces needed to create an infra behind a proxy. i have used this infra to test if the installation was sending any telemetry data out of the environment.
makes sense to land this as eventually we gonna start working on airgap and proxy support.
> feat: add proxy infra support on e2e tests

- .github/workflows/release-prod.yaml
https://github.com/replicatedhq/embedded-cluster/actions/runs/7907096603/job/21583366051
this make command doesn't exist anymore, instead there's the full `embedded-cluster-linux-amd64` command
> fix prod release builds

- cmd/embedded-cluster/install.go
- cmd/embedded-cluster/join.go
- go.mod
- go.sum
- pkg/logging/logging.go
- put a better user feedback in place in case of multiple attempts to run install or join on a machine.
- add color capabilities to our screen logging.
- make sure warnings are directed also to the screen and not only to the log.
- limit the max number of log files to 100.
- changes the log file name so we don't include `-` or `:` into it.
> feat: improve user feedback upon reinstall

- pkg/addons/adminconsole/adminconsole.go
if the context has been cancelled return immediately with the proper error.
> feat: observe context while waiting for kots deployment

- e2e/scripts/check-installation-state.sh
- e2e/scripts/check-postupgrade-state.sh
- pkg/addons/adminconsole/adminconsole.go
This PR adds `kotsApplication` to the list of protected values for the admin console add-on to prevent it from being overwritten during reconciliation. This fixes an issue where the admin console was missing application branding after the initial cluster install.
Added validation for branding to `check-installation-state.sh`. Example failure: https://github.com/replicatedhq/embedded-cluster/actions/runs/7965716798/job/21745820483?pr=393#step:4:9597
> fix missing admin console branding

- pkg/addons/applier.go
maps dont guarantee we are going to read the properties in the same order they are created. use an slice of add-ons instead.
> feat: ensure we always process add-ons the same order

- .github/workflows/release-dev.yaml
- e2e/scripts/vandoor-prepare.sh
Addresses an issue where the workflow running on main would fail during the "download embedded-cluster" step: https://github.com/replicatedhq/embedded-cluster/actions/runs/8194465936/job/22441201694
> promote pre-minio-removal in release-dev workflow too

- cmd/embedded-cluster/install.go
- cmd/embedded-cluster/join.go
- pkg/helpers/fs.go
- pkg/helpers/fs_test.go
go rename's function does not support moving files across different filesystems. implement our own 'move' function.
> bug: fix moving files across different filesystems

- cmd/embedded-cluster/uninstall.go
TL;DR
-----
Simplifies resetting a node iwth a reboot flag
Details
-------
Encourages better behavior by making it easier to reboot a node after resetting it. Instead of having to run two commands to assure a clean reset:
```
$ sudo ./embedded-cluster reset
$ sudo reboot
```
you just have to
```
$ sudo ./embedded-cluster reset --reboot
```
to do the same.
My implementation shells out to the `reboot` command which takes a little longer than making the minimum required syscalls (`sync(2)` and `reboot(2)`) because of the niceties it brings along like sending a wall message and signaling processes more gracefully.
My first implementation just made the syscalls and it was a lot faster but I decided it probably makes more sense to play nice. I could be convinced it's not needed since the node …
> Adds a reboot flag to `reset`

- cmd/local-artifact-mirror/artifact.go
- cmd/local-artifact-mirror/main.go
- cmd/local-artifact-mirror/pull.go
- cmd/local-artifact-mirror/serve.go
- go.mod
- go.sum
- pkg/defaults/defaults.go
- pkg/defaults/provider.go
- pkg/goods/goods.go
- pkg/tgzutils/tgz.go
the artifact puller pulls assets from a remote registry and store them locally under `/var/lib/embedded-cluster`. this command works hand in hand with an installation object as the latter provides the source from where the first pulls the artifacts.
the idea is that we will have a job that will run the following command:
```
local-artifact-mirror pull binaries <installation name>
local-artifact-mirror pull images <installation name>
local-artifact-mirror pull helmcharts <installation name>
```
the artifact puller will then read the installation `<installation name>` and fetch the artifacts, storing them in the right place under `/var/lib/embedded-cluster`.
this is an example of an installation object that provides source for such artifacts:
```yaml
apiVersion: …
```
> feature: implement artifact puller

- e2e/install_test.go
- e2e/local-artifact-mirror_test.go
- e2e/reset_test.go
- e2e/support-bundle_test.go
- e2e/unsupported-overrides_test.go
RunCommanOnNode already logs stdout and stderr in case of failures.
> chore: remove duplicated log lines

- cmd/embedded-cluster/install.go
- cmd/embedded-cluster/uninstall.go
- cmd/local-artifact-mirror/serve.go
- e2e/local-artifact-mirror_test.go
- pkg/defaults/defaults.go
- pkg/defaults/provider.go
- pkg/goods/systemd/local-artifact-mirror.service
if the binary has changed the mirror should stop so systemd can restart it using the new binary.
> feat: restart mirror on binary change

- pkg/addons/applier.go
- pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
if we are deploying in an airgap environment the installation airgap property must be set to true. setting it to true changes the operator behavior.
> feat: create installation object with airgap set

- .github/workflows/pull-request.yaml
- cmd/embedded-cluster/install.go
- cmd/embedded-cluster/version.go
- e2e/scripts/check-installation-state.sh
- e2e/scripts/single-node-install.sh
- pkg/addons/applier.go
- pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
- pkg/addons/options.go
during install we should create a config map in the embedded cluster operator namespace containing the version metadata (add-on versions, values, images, etc). this is specially useful for airgap environments.
> feat: create version metadata config map

- e2e/scripts/single-node-install.sh
- pkg/goods/goods.go
as part of the installation we also want to copy the binary to the default location so we can later on serve it to other nodes wishing to join the cluster.
by placing it the standard location we can also guarantee it will be upgraded by the local-artifact-mirror binary everytime a cluster upgrade is executed.
> feat: make a copy of the binary under /var/lib/embedded-cluster

- pkg/addons/adminconsole/adminconsole.go
Fixes:
```
sudo ./gitea-mastodon install -l license.yaml --airgap-bundle ./gitea-mastodon.airgap
✔  Host files materialized
? Enter a new Admin Console password: ******
? Confirm password: ******
✔  Node installation finished
✔  Storage is ready!
✔  Registry is ready!
✔  Embedded Cluster Operator is ready!
✔  Finalizing
panic: send on closed channel
goroutine 1 [running]:
github.com/replicatedhq/embedded-cluster/pkg/spinner.(*MessageWriter).Debugf(...)
/home/runner/work/embedded-cluster/embedded-cluster/pkg/spinner/spinner.go:67
github.com/replicatedhq/embedded-cluster/pkg/addons/adminconsole.(*AdminConsole).Outro(0xc0479082c0, {0x24a14e38, 0xc0005fa380}, {0x24a1e4e0, 0xc04765db00})
/home/runner/work/embedded-cluster/embedded-cluster/pkg/addons/adminconsole/adminconsole.go:290 +0x8ab …
```
> log kots install cmd before close on failure

- .github/workflows/release-dev.yaml
It seems that `${{ github.head_ref == 'main' && 'master' || github.head_ref }}` was evaluating to an empty string when running in the on-merge workflow. Since this workflow only runs on the main branch, we can safely set this to the master testim branch.
Example failure: https://github.com/replicatedhq/embedded-cluster/actions/runs/8557269930/job/23449207021#step:4:265
> fix on-merge testim branch

- .github/workflows/pull-request.yaml
This PR updates the download link comment on PRs to include the correct version label. Additionally, it adds a command to download the airgap installer.
> fix version label and add airgap command

- pkg/airgap/materialize.go
instead of setting the mode to 0755 we should preserve the mode present in the tgz file. here we also set a more restrictive permissions to the directory we create.
> chore: preserve charts and images file mode

- pkg/airgap/materialize.go
this way the filename after upgrade is consistent with the filename upon initial installation
> rename k0s image file from 'install.tar' to 'images-amd64.tar'

- pkg/spinner/options.go
- pkg/spinner/spinner.go
- pkg/spinner/spinner_test.go
we should be able to create new spinners based on what is being printed on the screen. this is useful when we want to create multiple spinners while running commands like `kots install`.
> feat: add 'new line' capability to spinner

- pkg/spinner/spinner.go
- pkg/spinner/spinner_test.go
when we break the line for a new message we need to flag the previous as success and not the current one. this commit addresses it.
> bug: show success in the previous step instead of current

- pkg/goods/support/host-support-bundle.yaml
let's just make this very specific. i have just seen a case where /usr/loca/bin isn't in the root's path.
> chore: use k0s full path when collecting bundle

- cmd/embedded-cluster/uninstall.go
we need to remove the k0s binary when resetting the server.
> chore: remove /usr/local/bin/k0s on reset

- pkg/addons/velero/velero.go
This PR adds the `credentials.name` [value](https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml#L487) to the Velero add-on to specify the secret name used for backup storage location credentials. Without this set, it will fall back to a secret named `velero`, which does not work with KOTS as the credentials secret name there is expected to be `cloud-credentials` ([reference](https://github.com/replicatedhq/kots/blob/v1.108.9/pkg/snapshot/store.go#L51)).
> specify velero credentials secret name

- .github/actions/e2e/action.yml
- e2e/cluster/cluster.go
- e2e/install_test.go
- e2e/scripts/collect-support-bundle.sh
- e2e/scripts/validate-support-bundle.sh
- e2e/support-bundle_test.go
This PR adds logic for generating host and cluster support bundles for e2e tests. If the test fails, bundles will be generated and uploaded as GH artifacts. The goal is to provide easier debugging of failed e2e tests (failed install, upgrade, etc).
Example failed test: https://github.com/replicatedhq/embedded-cluster/actions/runs/8896887451/job/24430845285?pr=541#step:4:495
> generate support bundles in e2e tests

- pkg/goods/support/host-support-bundle.yaml
gather and analyses the amount of network interfaces with ipv4. generates an error if no ipv4 interfaces are found.
> chore: capture and analyse ipv4 interfaces

- pkg/kubeutils/kubeutils.go
In order to reduce the chance that we go from `1/3 charts` to `waiting for additional components`, we should check the status more often. (really we should use a watch, but this is a lot simpler to get in!)
> check for installation updates every second instead of every 5 seconds

- pkg/addons/velero/velero.go
(also it was in the wrong place and not applied, so this makes sure no one will 'fix' it in the future)
> remove the 'restic' backup setting in velero as we are moving forward with kopia

- cmd/embedded-cluster/restore.go
- pkg/addons/applier.go
- pkg/kubeutils/kubeutils.go
Reverts replicatedhq/embedded-cluster#623, but runs in the background so that display is unchanged except in case of errors
> feat: wait for coredns and metrics-server, mk2

- .github/workflows/release-prod.yaml
- cmd/embedded-cluster/restore.go
and do not require the v prefix to match when comparing backups to restore
> allow releases without the v prefix

- cmd/embedded-cluster/materialize.go
- pkg/goods/goods.go
- pkg/goods/materializer.go
allow for materialize subcommand to accept a prefix so all materialized binaries will be placed under the provided directory.
this pr does not introduce any functional change. functions were moved to a struct and helper functions were created so no other changes in the source code is necessary (similar to what is made in the `defaults` package).
> feat: allow materialize with a prefix

- cmd/embedded-cluster/restore.go
This PR unmasks the access key ID input during the CLI restore process as this piece of data is not considered sensitive and doing this make the experience consistent with the UI.
Part of: https://app.shortcut.com/replicated/story/105248/various-quick-dr-fixes
> unmask access key id input during restore

- .github/workflows/pull-request.yaml
- .github/workflows/release-dev.yaml
- e2e/install_test.go
- e2e/playwright/tests/deploy-airgap-upgrade/test.spec.ts
- e2e/restore_test.go
- e2e/scripts/check-postupgrade-state.sh
- e2e/scripts/playwright.sh
test airgap upgrades that don't bump the k0s version. this ensures the new airgap bundle (infra) is read and loaded into k0s's containerd.
> chore: add e2e test for airgap upgrades using the same k0s version

- .github/workflows/pull-request.yaml
- .github/workflows/release-dev.yaml
This PR updates the on-merge test code to make the same set of releases as the on-pr test code does.
> release three airgap versions in on-merge tests as well as on-pr

- cmd/embedded-cluster/install.go
- cmd/embedded-cluster/join.go
- cmd/embedded-cluster/restore.go
- cmd/embedded-cluster/uninstall.go
Fixes this issue when resetting then reinstalling on the same machine:
```bash
unable to create systemd unit files: symlink /etc/systemd/system/k0sworker.service /etc/systemd/system/embedded-cluster.service: file exists
```
> Clean up existing embedded cluster systemd service before creating symlink

- cmd/embedded-cluster/uninstall.go
- e2e/install_test.go
warn about removing the antepenultimate (third to last) controller node if ha is enabled.
loom [recording](https://www.loom.com/share/27d17d62c79d45c299120023dc250675?sid=4f23cf96-eb7c-4a6b-8dbf-552e6d9bdba7).
> feat(ha): print warning on control plane node reset

- .github/workflows/pull-request.yaml
- .github/workflows/release-dev.yaml
- scripts/create-previous-k0s-release.sh
- scripts/create-upgrade-release.sh
This is blocking work on new upgrade feature as wrong version is set in the new chart.
> fix: metadata has wrong ec version

- .github/workflows/dependencies.yaml
we now have a different job that updates these add ons while also mirroring helm charts in our registry.
> chore: remove job to update upstream add ons

- cmd/embedded-cluster/install.go
- cmd/embedded-cluster/join.go
- cmd/embedded-cluster/restore.go
- go.mod
- pkg/preflights/preflights.go
After preflights complete, installing k0s would start. This code path that installs k0s did not have progress output which made the UI look slightly odd. This PR adds code that starts the spinner immediately after preflights complete to indicate the start of node installation. We additionally, attach appropriate status progress messages to the spinner.
Below are recordings of some sample outputs
In these recordings, note that we now have `Installing <application> node` progress output right after preflights complete.
**Original implementation where after preflights complete, there would be a moment of no progress output**
https://github.com/replicatedhq/embedded-cluster/assets/681087/ce8e60f5-5fc0-4b2f-a129-322ca4c55143
**Spinner with default host preflights. The preflights run is quite …
> fix: add spinner to show installation of k0s

- Makefile
- pkg/addons/adminconsole/adminconsole.go
Tests are currently failing with error:
> Jul 09 13:39:11 ethanm-testim-1 k0s[17319]: time="2024-07-09 13:39:11" level=error msg="Reconciler error" Chart="{k0s-addon-chart-admin-console kube-system}" component=extensions_controller controller=chart controllerGroup=helm.k0sproject.io controllerKind=Chart error="can't update or install chart: can't reconcile installation for \"k0s-addon-chart-admin-console\": can't locate chart `oci://proxy.replicated.com/anonymous/registry.replicated.com/library/admin-console-2024.7.8-0e7299-nightly`: proxy.replicated.com/anonymous/registry.replicated.com/library/admin-console:2024.7.8-0e7299-nightly: not found" name=k0s-addon-chart-admin-console namespace=kube-system reconcileID="\"18f050e0-1b45-436f-b8aa-833a421517ad\"" …
> fix(ci): add back LDFLAGS for kots regression tests

- pkg/preflights/host-preflight.yaml
This prevents a situation where an airgaped cluster install can be left hanging waiting for calico to initialize.
> Add host-preflight to check for default route

- cmd/embedded-cluster/install.go
- cmd/embedded-cluster/join.go
- cmd/embedded-cluster/restore.go
- cmd/embedded-cluster/uninstall.go
- Adds `--admin-console-password` flag to `install`
- Alphabetizes CLI flags in help menus
- Updates descriptions for some CLI flags
- Updates wording for password prompt to make it clear you're setting the Admin Console password
> CLI flag and password prompt improvements

- cmd/embedded-cluster/main.go
Example:
```
alex@alex-ec-pr:~$ sudo ./embedded-cluster-smoke-test-staging-app instal
No help topic for 'instal'. Did you mean "install"?
```
> Make suggestions if typo in command name

- Makefile
- deploy/images/local-artifact-mirror/apko.tmpl.yaml
- deploy/images/utils/apko.tmpl.yaml
- deploy/packages/local-artifact-mirror/melange.tmpl.yaml
The default in the make target gets overridden by the version at the top of the file
> fix(ci): VERSION var collision

- pkg/goods/support/host-support-bundle.yaml
Fixes: https://app.shortcut.com/replicated/story/108807/analyzers-in-default-spec-not-compatible-with-k0s-deployments
Demo: https://asciinema.org/a/jX7izIBEaFbWZP9pTUiWvvmap
> chore: Add hostname mismatch support bundle check

- .github/actions/e2e/action.yml
- .github/workflows/ci.yaml
- e2e/install_test.go
- e2e/restore_test.go
- e2e/scripts/check-postupgrade-state.sh
- e2e/scripts/common.sh
- e2e/utils.go
- pkg/addons/embeddedclusteroperator/static/metadata.yaml
- pkg/addons/embeddedclusteroperator/static/values.yaml
Fixes airgap k8s upgrade and adds tests.
Related:
https://github.com/replicatedhq/embedded-cluster-operator/pull/265
> Ensure k8s version matches the target version after upgrades

- pkg/kubeutils/kubeutils.go
Ignores installation crd not yet installed error.
```
ethan@ethanm-ec-1:~$ sudo ./embedded-cluster reset
unable to get installation: unable to list installations: no matches for kind "Installation" in version "embeddedcluster.replicated.com/v1beta1"
```
> fix(reset): handle crd installation not installed error

- cmd/embedded-cluster/uninstall.go
Draining and leaving etcd cluster can cause issues for reset of a single node and is not needed.
> fix(reset): do not drain node if only one in the cluster

- cmd/embedded-cluster/install.go
- cmd/embedded-cluster/join.go
- cmd/embedded-cluster/list_images.go
- cmd/embedded-cluster/metadata.go
- cmd/embedded-cluster/restore.go
- pkg/addons/adminconsole/adminconsole.go
- pkg/addons/applier.go
- pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
- pkg/addons/openebs/openebs.go
- pkg/addons/options.go
- pkg/addons/registry/registry.go
- pkg/addons/seaweedfs/seaweedfs.go
- pkg/addons/velero/velero.go
- pkg/config/config.go
- pkg/helpers/parse.go
This sets the computed value of service-node-port-range in the installation object for later use in the join command from the defaults taking into account the unsupported overrides from both the spec and the install flag.
This fixes an issue that could cause node joins to use a different value for the service-node-port-range than on the original node.
> fix: pass service node port range to installation for join

- cmd/embedded-cluster/uninstall.go
```
$ sudo ./embedded-cluster-smoke-test-staging-app reset
This will remove this node from the cluster and completely reset it, removing all data stored on the node.
Do not reset another node until this is complete.
? Do you want to continue? Yes
error: fork/exec /usr/local/bin/k0s: no such file or directory
An error occurred while trying to reset this node.
Continuing may leave the cluster in an unexpected state.
? Do you want to continue anyway? Yes
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x15ac69c]
goroutine 1 [running]:
github.com/replicatedhq/embedded-cluster/pkg/kubeutils.NumOfControlPlaneNodes({0x25733168, 0xc000068080}, {0x0, 0x0}) …
```
> fix(reset): fix panic

- pkg/preflights/host-preflight.yaml
Checking for absolute paths breaks these host preflights on systems that don't conform to Ubuntu's binary locations. 
i.e: Alpine and RHEL don't keep `mount` and `umount` in `/usr/bin`
> Bug: Don't check absolute paths for mount binaries

- e2e/scripts/collect-support-bundle-cluster.sh
If the operator install fails the support bundle spec is not available in the cluster and collection fails. This change includes the url as well for debugging purposes.
> fix(e2e): collect cluster support bundle if ec install fails

- Makefile
- cmd/embedded-cluster/install.go
- e2e/materialize_test.go
- fio/Dockerfile
- pkg/defaults/defaults.go
- pkg/preflights/host-preflight.yaml
- pkg/preflights/preflights.go
- pkg/preflights/preflights_test.go
Includes statically linked fio in the binary.
Runs fio preflight on installation.
Adds about 30 seconds to the installation time.
Will fail if disk does not meet threshold.
tested in bookwork-slim image
```
root@ethanm-ec-1:/home/ethan# docker run --rm -it -v `pwd`:/wrk -w /wrk debian:bookworm-slim bash
root@e9dd75129439:/wrk# ./embedded-cluster-smoke-test-staging-app install run-preflights --license license.yaml
✗  6 host preflights failed
+--------+-----------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| STATUS | TITLE                       | MESSAGE …
```
> feat(troubleshoot): add filesystem latency check

- cmd/embedded-cluster/install.go
- cmd/embedded-cluster/network.go
- cmd/embedded-cluster/proxy.go
- cmd/embedded-cluster/restore.go
This way the default value shows up in the CLI help menu, making it easier for users to know whether they need to update it.
> Set default value for pod/service CIDRs with flag

- .github/workflows/release-prod.yaml
https://github.com/replicatedhq/embedded-cluster/actions/runs/10605611609/job/29394826595
```release-note
```
> fix(ci): operator release fails with "no rule to make target 'build-chart'"

- .github/workflows/release-prod.yaml
https://github.com/replicatedhq/embedded-cluster/actions/runs/10605907954/job/29395716361
```release-note
```
> fix(ci): operator release fails with "buildtools: No such file or directory"

- Makefile
- local-artifact-mirror/Makefile
Uses make to cache static assets
```release-note
```
> chore(ci): speed up build with static make cache

- .github/workflows/ci.yaml
- cmd/embedded-cluster/install.go
- go.mod
- go.sum
- kinds/go.mod
- pkg/logging/logging.go
Dependabot builds are failing due to the new imports needing newer go. 
https://github.com/replicatedhq/embedded-cluster/pull/1051
This provides newer go.
```release-note
```
> bump go to 1.23.0

- .github/workflows/kinds.yaml
This changes the kinds CI final task to `validate-success-kinds`, so as not to fulfill the required check for `validate-success` on the main CI workflow
```release-note
```
> rename the kinds CI validate-success task to 'validate-success-kinds'

- utils/go.mod
go get fails with
```
ethan@Ethans-MacBook-Pro-2 replicated-app % go get github.com/replicatedhq/embedded-cluster/utils@main
go: downloading github.com/replicatedhq/embedded-cluster v1.29.5-0.20240904165046-f3364d7f56b7
go: downloading github.com/replicatedhq/embedded-cluster/utils v0.0.0-20240904165046-f3364d7f56b7
go: github.com/replicatedhq/embedded-cluster/utils@main (v0.0.0-20240904165046-f3364d7f56b7) requires github.com/replicatedhq/embedded-cluster/utils@v0.0.0-20240904165046-f3364d7f56b7: parsing go.mod:
module declares its path as: github.com/replicatedhq/embedded-cluster-utils
but was required as: github.com/replicatedhq/embedded-cluster/utils
```
```release-note
```
> fix(utils): change module path and update go version

- e2e/cluster/cluster.go
- e2e/proxy_test.go
- e2e/restore_test.go
- e2e/utils.go
This changes our test code to not use 10.0.0.0/8 etc as our noproxy addresses, and instead only pass the VM IPs there.
```release-note
```
> test with a noproxy that doesn't include every private IP

- kinds/apis/v1beta1/config_types.go
- operator/charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
- operator/config/crd/bases/embeddedcluster.replicated.com_configs.yaml
- operator/config/crd/bases/embeddedcluster.replicated.com_installations.yaml
For vendoring into kots
```release-note
```
> chore(kinds): add binaryOverrideUrl and metadataOverrideUrl

- .github/workflows/release-prod.yaml
ttl.sh image is ending up in the release metadata
```
"proxy.replicated.com/anonymous/ttl.sh/replicated/ec-utils@sha256:ce82b0dd0b8816d87d26d4ebec0f95cdca964a5e092739903150943a9621aa47"
```
```release-note
```
> fix(ci): release using ttl.sh image

- cmd/embedded-cluster/proxy_test.go
- e2e/cluster/cluster.go
- pkg/defaults/defaults.go
These DNS addresses should not be passed to no_proxy and should have no consequences but are unnecessary.
```release-note
```
> fix(proxy): do not pass unnecessary values to no-proxy

- .github/workflows/image-scan.yaml
CI is failing 
```
chmod: cannot access './output/bin/buildtools': No such file or directory
```
https://github.com/replicatedhq/embedded-cluster/actions/runs/10852115430/job/30117607691
```release-note
```
> fix(ci): image-scan workflow missing buildtools

- README.md
> clarify that kots should be in the same parent directory, not a subdirectory

- Makefile
> Fix downloading KOTS bin for versions with build suffix

- fio/Dockerfile
use the --disable-native option so it does not optmize for the cpu.
```release-note
```
> bug: fix fio build so it can be used on other cpus

- Makefile
- e2e/proxy_test.go
- e2e/restore_test.go
proxy installations are not supported on k0s < 1.29.
> chore: skip proxy tests on k0s < 1.29

- cmd/embedded-cluster/install.go
- pkg/preflights/app.go
- pkg/preflights/app_test.go
Sometimes additional chart values will be invalid yaml. This will prevent the installation from completing 5+ minutes later with very hard to debug error messages. We should check for this early.
```release-note
The 'install' command will check helm extension values for yaml validity before installation.
```
> check if chart values parse as yaml before installing application

- cmd/buildtools/utils.go
Prior to this change, for non list type manifests we were ignoring architecture.
```release-note
```
> fix(ci): do not override digest for wrong architecture

- .github/workflows/ci.yaml
- README.md
- cmd/embedded-cluster/install.go
- cmd/embedded-cluster/join.go
- cmd/embedded-cluster/preflights.go
- cmd/embedded-cluster/proxy.go
- cmd/embedded-cluster/proxy_test.go
- cmd/embedded-cluster/restore.go
- e2e/proxy_test.go
- kinds/apis/v1beta1/installation_types.go
- operator/charts/embedded-cluster-operator/charts/crds/templates/resources.yaml
- operator/config/crd/bases/embeddedcluster.replicated.com_installations.yaml
- pkg/netutils/ips.go
- pkg/netutils/ips_test.go
With no no-proxy set:
```
no-proxy was not set, adding the default interface's subnet "172.17.0.0/16" to the no-proxy
? Set the Admin Console password:
```
With an insufficient no-proxy set:
```
The provided no-proxy "10.0.0.0/24" does not cover the local IP "172.17.0.2", adding the default interface's subnet "172.17.0.0/16" to the no-proxy we will use
? Set the Admin Console password:
```
When joining a node that is not included in the cluster's no-proxy:
```
no-proxy config "localhost,127.0.0.1,.cluster.local,.svc,10.0.0.2,10.244.0.0/16,10.96.0.0/12" does not allow access to local IP "10.0.0.3"
```
```release-note
Installations using a proxy will automatically have the default interface's subnet supplied as a no-proxy if the provided no-proxy does not cover the instance IP address.
```
> automatically detect node ip during install for noproxy

- pkg/preflights/host-preflight.yaml
This simplifies client debugging by specifying the static IP addresses of proxy.replicated.com and replicated.app when connectivity checks to those domains fail.
We may want to consider adding these as compile time variables, but they really shouldn't be changing on our end either.
```release-note
```
> hardcode proxy.replicated.com and replicated.app static IPs in troubleshoot output

- dev/distros/dockerfiles/almalinux-8.Dockerfile
- dev/distros/dockerfiles/debian-bookworm.Dockerfile
- dev/distros/dockerfiles/ubuntu-jammy.Dockerfile
Fixes an issue where joined worker nodes in the dev env do not become ready.
NONE
```release-note
NONE
```
NONE
> Fix joining worker nodes in dev env

- cmd/embedded-cluster/install.go
- cmd/embedded-cluster/join.go
- cmd/embedded-cluster/preflights.go
- cmd/embedded-cluster/restore.go
- pkg/config/config.go
- pkg/netutils/ips.go
- Automatically determines the network interfaces on join.
- Fixes an issue where the internal node IP wasn't set from the user-specified network interface.
```release-note
```
NONE
> feat: determine network interface / IP on join

- Makefile
- cmd/embedded-cluster/flags.go
- cmd/embedded-cluster/install.go
- cmd/embedded-cluster/join.go
- cmd/embedded-cluster/restore.go
- cmd/embedded-cluster/util.go
- cmd/local-artifact-mirror/serve.go
- dev/dockerfiles/operator/Dockerfile.ttlsh
- e2e/install_test.go
- e2e/local-artifact-mirror_test.go
- e2e/scripts/default-install.sh
- e2e/scripts/restore-multi-node-airgap-phase1.exp
- operator/controllers/installation_controller.go
- operator/pkg/artifacts/upgrade.go
- operator/pkg/charts/charts.go
- pkg/addons/adminconsole/adminconsole.go
- pkg/addons/adminconsole/static/metadata.yaml
- pkg/addons/applier.go
- pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
- pkg/addons/options.go
- pkg/defaults/defaults.go
- pkg/helm/values.go
- Adds the ability to override the Admin Console port (default 30000) on installation using the flag `--admin-console-port`
- Adds the ability to override the Local Artifact Mirror port (default 50000) on installation using the flag `--local-artifact-mirror-port`
- Adds the ability to override the Local Artifact Mirror port (default 50000) on restore using the flag `--local-artifact-mirror-port`
```release-note
- Adds the ability to override the Admin Console port (default 30000) on installation using the flag `--admin-console-port`
- Adds the ability to override the Local Artifact Mirror port (default 50000) on installation using the flag `--local-artifact-mirror-port`
- Adds the ability to override the Local Artifact Mirror port (default 50000) on restore using the flag …
```
> feat: ability to override admin console and lam host ports

- pkg/metrics/sender.go
- pkg/metrics/sender_test.go
This makes it dramatically easier to figure out what version of embedded cluster is throwing errors.
```release-note
```
> report embedded cluster and k8s versions with metrics object

- .github/workflows/image-scan.yaml
Apko is no longer needed as image is now built in a container.
```release-note
```
> fix(ci): remove unnecessary apko install

- .github/workflows/image-deps-updater.yaml
- .github/workflows/update-addons.yaml
We now build ECO at time of release and no longer need to update it periodically.
```release-note
```
> chore: eco is built at release time and is no longer needed in auto updates

- cmd/embedded-cluster/reset.go
- e2e/cluster/cluster.go
- e2e/install_test.go
- e2e/preflights_test.go
- e2e/restore_test.go
- e2e/scripts/default-route-through-proxy.sh
- pkg/preflights/host-preflight.yaml
Checks if all needed ports are available on the server prior to start the installation.
> feat: add host preflights for all needed ports

- cmd/embedded-cluster/join.go
- cmd/embedded-cluster/preflights.go
- pkg/netutils/ips.go
Fixes an issue where joining nodes failed with `unable to get network interface for address`.
[SC-112735](https://app.shortcut.com/replicated/story/112735)
```release-note
* Fixes an issue where joining nodes failed with `unable to get network interface for address`.
```
NONE
> fix: unable to get network interface for address when joining nodes

- e2e/scripts/install-and-configure-squid.sh
While working on updating the `http` collector in Troubleshoot to detect a mitm proxy, I encountered: 
``` # troubleshoot 
I0924 19:29:37.934112   83567 run.go:142] Collecting support bundle: http/https-replicated-proxy
I0924 19:29:37.934361   83567 http.go:145] Request: GET / HTTP/1.1
Host: replicated.app
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip
Response: <nil>
I0924 19:29:37.942216   83567 http.go:154] Request failed: proxyconnect tcp: tls: failed to verify certificate: x509: certificate relies on legacy Common Name field, use SANs instead
```
``` # squid logs
1727205940.640      0 10.128.0.9 NONE_NONE/000 0 - error:transaction-end-before-headers - HIER_NONE/- -
1727206177.942      0 10.128.0.9 NONE_NONE/000 0 - error:transaction-end-before-headers - HIER_NONE/- -
```
Ensure …
> chore(e2e): make sure squid proxy generates a cert containing SANs

- operator/controllers/installation_controller.go
- operator/pkg/metrics/metrics.go
- pkg/metrics/events.go
- pkg/metrics/reporter.go
This adds the following items to reporting:
1. all cli-level 'event' items now include the embedded cluster version generating the event.
2. node events sent from the operator now include the embedded cluster version.
3. upgrade events sent from the operator now include the initial and target embedded cluster versions.
4. initial installation events include the app channel ID and app version string (when relevant)
```release-note
```
> add additional reporting info

- .github/workflows/distros.yaml
- Makefile
- dev/distros/Makefile
- dev/distros/README.md
Publishes EC distro images to Dockerhub so they can be used for testing without having to build them in CI to avoid flakiness.
[113140](https://app.shortcut.com/replicated/story/113140)
NONE
```release-note
NONE
```
NONE
> Publish dev/test EC distros to dockerhub

- cmd/embedded-cluster/install.go
- pkg/preflights/host-preflight.yaml
- pkg/preflights/template.go
when on arm64 we don't want to run the x84-64-v2 preflight.
```release-note
```
> chore: make preflight pass on arm64

- Makefile
Hopefully this will fix the following flakiness in ci.
```
make[1]: Leaving directory '/home/runner/work/embedded-cluster/embedded-cluster/local-artifact-mirror'
cp local-artifact-mirror/bin/local-artifact-mirror-linux-amd64 pkg/goods/bins/local-artifact-mirror
touch pkg/goods/bins/local-artifact-mirror
curl: (22) The requested URL returned error: 403
curl: (22) The requested URL returned error: 403
make output/bins/fio--amd64
make[1]: Entering directory '/home/runner/work/embedded-cluster/embedded-cluster'
mkdir -p output/bins
docker build -t fio --build-arg FIO_VERSION=amd64 --build-arg PLATFORM=linux/ fio
```
https://github.com/replicatedhq/embedded-cluster/actions/runs/11150994226/job/30993411700?pr=1238
```release-note
```
> fix(ci): retry failure to get latest fio version

- dev/distros/dockerfiles/centos-9.Dockerfile
- dev/distros/dockerfiles/debian-bullseye.Dockerfile
Adds centos-9 and debian-bullseye distros to the dev/test images
NONE
```release-note
NONE
```
NONE
> Add centos-9 and debian-bullseye distros

- cmd/embedded-cluster/install.go
- cmd/embedded-cluster/install_test.go
Make sure we validate the admin console password length requiring it to be at least 6 characters, similar to what already [happens in KOTS](https://github.com/replicatedhq/kots/blob/dab9434bb24c13ffb5f37b528c515121b31db089/pkg/util/password_prompt.go#L22-L25)
https://app.shortcut.com/replicated/story/104936/admin-console-minimum-password-length-inconsistent
I've added a test to the password validation function and was trying to see if there's a way that we could test the `maybeAskAdminConsolePassword` method, but since it relies on input prompts I'm unsure what would be the best mechanism to do so 🤔 open to suggestions.
Meanwhile I've also run a couple of manual tests in the local dev env:
```
root@node0:/replicatedhq/embedded-cluster# output/bin/embedded-cluster install --license …
```
> fix: validate admin console password length

- deploy/images/utils/apko.tmpl.yaml
add wget to utils image so we don't need to drag in another image to use as a goldpinger client
```release-note
```
> Add wget to utils image

- dev/distros/dockerfiles/almalinux-8.Dockerfile
- dev/distros/dockerfiles/centos-9.Dockerfile
- dev/distros/dockerfiles/debian-bookworm.Dockerfile
- dev/distros/dockerfiles/debian-bullseye.Dockerfile
- dev/distros/dockerfiles/ubuntu-jammy.Dockerfile
Masks systemd getty@tty1.service as it's flaky in CI and doesn't apply in containers
NONE
```release-note
NONE
```
NONE
> Mask systemd getty@tty1.service as it's flaky and doesn't apply in containers

- operator/charts/embedded-cluster-operator/troubleshoot/cluster-support-bundle.yaml
fix the labels used by the openebs pods and adds a log analyzer for a known error string.
> feat: fix openebs log collector + adds log analyzer

- operator/charts/embedded-cluster-operator/templates/embedded-cluster-operator-clusterrole.yaml
- operator/controllers/installation_controller.go
- operator/pkg/charts/detection.go
- operator/pkg/charts/helm_test.go
- operator/pkg/charts/reconcile.go
- operator/pkg/charts/reconcile_test.go
- operator/pkg/cli/root.go
- operator/pkg/upgrade/upgrade.go
it's irritating digging through the operator logs to figure out what happened when. We should record events instead.
```
Events:
Type    Reason             Age                    From                     Message
----    ------             ----                   ----                     -------
Normal  NodeAdded          4m39s                  installation-controller  Node node0 has been added
Normal  PendingHelmCharts  3m25s (x6 over 4m28s)  installation-controller  Pending helm charts [admin-console ingress-nginx goldpinger]
Normal  PendingHelmCharts  2m25s (x3 over 2m36s)  installation-controller  Pending helm charts [ingress-nginx goldpinger]
Normal  PendingHelmCharts  2m4s (x2 over 2m4s)    installation-controller  Pending helm charts [goldpinger]
Normal  AddonsUpgraded     83s (x4 …
```
> record events in the installation object

- cmd/embedded-cluster/install.go
- cmd/embedded-cluster/join.go
- cmd/embedded-cluster/preflights.go
- cmd/embedded-cluster/restore.go
This reverts commit 8309d3c14126a2c6fb797d411c0db32525de2f10.
> chore: revert prevent the use of symlinks

- operator/charts/embedded-cluster-operator/templates/embedded-cluster-logs-collector.yaml
Currently we run daemonsets to collect journalctl logs for k0scontroller and k0sworker in the `default` namespace. This PR changes those to run in `embedded-cluster` instead, and also changes the `k0sworker` collector to collect logs for the worker service instead of controller again.
```release-note
```
> run the daemonsets to collect k0s controller/worker logs in the embedded-cluster namespace

- .github/workflows/release-k0s-patch.yaml
If we overwrite the existing k0s binary, sha256sums will not match. We should not do this.
```release-note
```
> do not overwrite existing custom k0s builds

- dev/distros/dockerfiles/almalinux-8.Dockerfile
- dev/distros/dockerfiles/centos-9.Dockerfile
- dev/distros/dockerfiles/debian-bookworm.Dockerfile
- dev/distros/dockerfiles/debian-bullseye.Dockerfile
- dev/distros/dockerfiles/ubuntu-jammy.Dockerfile
- dev/distros/entrypoint.sh
- dev/distros/timesyncd-override.conf
A unique machine ID is required for multi-node clusters in k0s <= v1.29. This PR addresses that problem in order to fix multi-node HA upgrades in the dev and new testing env.
NONE
```release-note
NONE
```
NONE
> Dev / testing: ensure a unique machine ID for each node

- pkg/preflights/host-preflight.yaml
data directory can't be a symlink, we have decided to fail if this is the case. this pr adds a preflight check for that.
> feat: check if data-dir is a symlink

- .github/workflows/release-k0s-patch.yaml
fix missing quotes in aws command.
> chore: fix missing quotes in aws command

- dev/distros/dockerfiles/almalinux-8.Dockerfile
- dev/distros/dockerfiles/centos-9.Dockerfile
- dev/distros/dockerfiles/debian-bookworm.Dockerfile
- dev/distros/dockerfiles/debian-bullseye.Dockerfile
- dev/distros/dockerfiles/ubuntu-jammy.Dockerfile
Removes KUBECONFIG env var in distro images as it's not necessary.
NONE
```release-note
NONE
```
NONE
> Remove KUBECONFIG env var in distro images

- pkg/preflights/host-preflight.yaml
Add Host DNS Wildcard preflight check
Demo: https://asciinema.org/a/F2BtS3GLpIz0K4CqoaPpnyZeI
NONE
NONE
NONE
> feat(preflights): add host dns wildcard check

- cmd/buildtools/main.go
- cmd/buildtools/utils.go
- pkg/helm/client.go
- pkg/helm/images.go
[Seaweedfs](https://artifacthub.io/packages/helm/seaweedfs/seaweedfs) changed their app version in the helm chart without changing the helm chart version. This does not play well with our shrinkwrapped releases and now we have cves in the seaweed image.
https://github.com/replicatedhq/embedded-cluster/actions/runs/11060070387/job/30733862137
Right now im just warning but i think we need to handle this somehow.
```
WARN[0004] dst tag exists but app versions do not match (src: 3.73, dst: 3.71) 
```
```release-note
```
> fix(ci): buildtools handle helm chart app version change

- cmd/embedded-cluster/install.go
- e2e/install_test.go
Related https://github.com/replicatedhq/embedded-cluster/pull/1327
This is still happening here https://github.com/replicatedhq/embedded-cluster/actions/runs/11350327808/job/31568962727
The test fails 4 seconds after k0s api starts. Perhaps we are just not waiting long enough?
```
Oct 15 17:24:44 node-dc4d1-03 k0s[3487]: time="2024-10-15 17:24:44" level=info msg="Started successfully, go nuts pid 3532" component=k0s-control-api
```
```
Tue, 15 Oct 2024 17:24:48 GMT
unable to wait for node: unable to get status: exit status 1: Error: status: can't get "status" via "/run/k0s/status.sock": Get "http://localhost/status": dial unix /run/k0s/status.sock: connect: connection refused
```
```release-note
```
> fix: install flake waiting for k0s

- operator/charts/embedded-cluster-operator/troubleshoot/cluster-support-bundle.yaml
the uri field was pointing to the old repository.
> bug: fix wrong link to upstream support bundle url

- Makefile
The current `e2e-test` script uses go's `-run` flag which interprets the provided name as a regex, this means that similar test names will execute. E.g.
```
make e2e-test (...) TEST_NAME=TestResetAndReinstall
go test -timeout 60m -ldflags="(...)" -v ./e2e -run TestResetAndReinstall
=== RUN   TestResetAndReinstall
=== PAUSE TestResetAndReinstall
=== RUN   TestResetAndReinstallAirgap
=== PAUSE TestResetAndReinstallAirgap
```
After the change
```
make e2e-test (...) TEST_NAME=TestResetAndReinstall
go test -timeout 60m -ldflags="(...)" -v ./e2e -run ^TestResetAndReinstall$
=== RUN   TestResetAndReinstall
=== PAUSE TestResetAndReinstall
=== RUN   TestResetAndReinstallAirgap
=== PAUSE TestResetAndReinstallAirgap
```
NONE
```release-note
NONE
```
NONE
> chore(makefile): fix the e2e single test execution

- cmd/embedded-cluster/install.go
- cmd/embedded-cluster/join.go
- cmd/embedded-cluster/reset.go
- cmd/embedded-cluster/restore.go
I realized the air gap flags are still hidden, so I unhid those. I also alphabetized the CLI flags in the help menus so they're easier to read. The CIDR and proxy flags are from functions, so those didn't get alphabetized. Ultimately I'd like them to be alphabetized, but I didn't bother to rework those functions.
NONE
```release-note
Unhides the `--airgap-bundle` flag for the `install`, `join`, and `restore` commands.
```
NONE
> Unhide air gap and alphabetize flags

- e2e/cluster/docker/cluster.go
- e2e/cluster/lxd/cluster.go
- e2e/install_test.go
- e2e/scripts/check-airgap-installation-state.sh
- e2e/scripts/check-airgap-post-ha-state.sh
- e2e/scripts/check-installation-state.sh
- e2e/scripts/check-post-ha-state.sh
- e2e/scripts/check-postupgrade-state.sh
- e2e/scripts/common.sh
- operator/pkg/charts/charts.go
- pkg/kubeutils/kubeutils.go
- pkg/kubeutils/kubeutils_test.go
The seaweedfs data paths are incorrect because the values are set wrong (global.data.hostPathPrefix vs master.data.hostPathPrefix).
Additionally, fixes an issue that prevents data paths from being set correctly for upgrades from the pre-minio version.
Adds validation to e2e tests for data paths.
```release-note
Fixes an issue that causes the data paths to be set incorrectly for seaweedfs when cluster is converted to HA.
```
> bug(seaweedfs): fix data path, add validation in e2e tests

- e2e/install_test.go
- pkg/netutils/nets_test.go
as per pr comment this makes sure we are also validating the returned supernet.
ref: https://github.com/replicatedhq/embedded-cluster/pull/1324#discussion_r1806661271
> chore: unit test returned supernet

- cmd/embedded-cluster/admin_console.go
- cmd/embedded-cluster/k0s.go
- cmd/embedded-cluster/main.go
- e2e/install_test.go
- e2e/playwright/tests/login-with-custom-password/test.spec.ts
- e2e/playwright/tests/shared/login.ts
- e2e/scripts/playwright.sh
- pkg/helpers/command.go
- pkg/kotscli/kotscli.go
add a new command to reset the admin console password.
```release-note
Added command to reset Admin Console password.
```
> feat: add admin-console reset-password command

- cmd/embedded-cluster/flags.go
- cmd/embedded-cluster/install.go
- cmd/embedded-cluster/materialize.go
- cmd/embedded-cluster/preflights.go
- cmd/embedded-cluster/provider.go
- cmd/embedded-cluster/restore.go
Reset is failing on worker nodes after an upgrade because the cli is preferring the default data directory over the one discovered from the filesystem.
```release-note
```
> fix: reset fails on worker nodes after an upgrade

- e2e/install_test.go
simplify the regex matching on the e2e test.
```release-note
```
> chore: simplify regex on e2e test

- cmd/embedded-cluster/main.go
- cmd/embedded-cluster/support_bundle.go
- e2e/scripts/validate-support-bundle.sh
- e2e/support-bundle_test.go
- pkg/helpers/command.go
add support-bundle command. this command generates a support bundle using the in-cluster support bundle definitions and the local host support bundle definitions.
```release-note
Added the support-bundle command.
```
> feat: add support-bundle command

- .gitignore
I use direnv for setting environment variables, this ignores it's config file in the root folder to prevent me from checking in the tokens it sets for the dev environment.
> Ignore .envrc for dev environment setup

- e2e/scripts/check-postupgrade-state.sh
this seems like a transient error to me based on the cluster bundle
```
kotsadm            second-547bf4b58d-pskcj                         0/1     ImagePullBackOff   0             14s
```
```
"conditions": [
{
"type": "Available",
"status": "True",
"lastUpdateTime": "2024-10-22T19:45:07Z",
"lastTransitionTime": "2024-10-22T19:45:07Z",
"reason": "MinimumReplicasAvailable",
"message": "Deployment has minimum availability."
},
{
"type": "Progressing",
"status": "True",
"lastUpdateTime": "2024-10-22T19:45:07Z",
"lastTransitionTime": "2024-10-22T19:28:34Z",
"reason": "NewReplicaSetAvailable",
"message": "ReplicaSet \"second-547bf4b58d\" has successfully progressed."
}
]
```
https://github.com/replicatedhq/embedded-cluster/actions/runs/11466739613/job/31908613257?pr=1363
```release-note
```
> chore(ci): wait for app to deploy after upgrade

- operator/pkg/charts/reconcile_test.go
This allows changing chart values without also having to manually recalculate the desired values hash.
```release-note
```
> instead of hardcoding values hashes in unit testing build them from the expected values

- .github/workflows/automated-prs-manager.yaml
- .github/workflows/ci.yaml
Fixes an issue where the automated PRs manager workflow could not detect e2e jobs in CI runs because they were renamed to `E2E` instead of `e2e`.
NONE
```release-note
NONE
```
NONE
> Fix automated PRs manager detecting E2E CI jobs

- .github/workflows/automated-prs-manager.yaml
- .github/workflows/ci.yaml
Fixes an issue where the automated PRs manager workflow could not detect e2e jobs in CI runs because they were renamed to `Validate success` instead of `validate-success`.
NONE
```release-note
NONE
```
NONE
> Fix automated PRs manager detecting validate success branch protection job

- cmd/embedded-cluster/install.go
- cmd/embedded-cluster/network.go
- cmd/embedded-cluster/network_test.go
- pkg/preflights/host-preflight.yaml
- pkg/preflights/template.go
- pkg/preflights/template_test.go
Adds host preflight checks for the pod-cidr, service-cidr and cidr flags. If the `--pod-cidr`or `--service-cidr` checks are provided then those are the preflights that will be put in place, else we're gonna setup a preflight for wtv is provided through the `--cidr` flag.
This also fixes the current behaviour for CIDR flags where both service and a pod CIDR must be provided in order for us to use that VS the default CIDR flag.
https://app.shortcut.com/replicated/story/113111/new-preflight-check-to-detect-whether-cluster-network-might-conflict-with-enterprise-s-internal-network
Added a series of tests.
Plus some manual executions:
```
root@node0:/replicatedhq/embedded-cluster# output/bin/embedded-cluster install run-preflights --license local-dev/Joao.yaml --cidr 172.17.0.0/16
✔  Host files …
```
> feat(host-preflights): add cidr preflight checks

- operator/charts/embedded-cluster-operator/templates/embedded-cluster-lam-service-config.yaml
- pkg/goods/support/host-support-bundle.tmpl.yaml
Collect Local Artefact Mirror systemd service config in support bundle
NONE
```release-note
Collect local artefact mirror service config in support bundle
```
NONE
> chore: Collect LAM service config in support bundle

- operator/pkg/upgrade/installation.go
in the kots logs:
```
2024/10/23 20:56:19 Running upgrade command...
2024/10/23 20:56:19 Upgrade command output:
2024/10/23 20:56:19   Upgrade job creation started
2024/10/23 20:56:19   Preparing upgrade to installation 20241023205617 (k0s version 1.16.0+k8s-1.30)
2024/10/23 20:56:19   time="2024-10-23T20:56:19Z" level=info msg="Creating installation 20241023205617"
2024/10/23 20:56:19   Error: apply installation: update installation status: update installation status: Operation cannot be fulfilled on installations.embeddedcluster.replicated.com "20241023205617": the object has been modified; please apply your changes to the latest version and try again
```
This was when upgrading the app but leaving the version of embedded cluster constant - a new installation object was created, updated …
> retry setting installation state on conflict

- Makefile
- cmd/embedded-cluster/support_bundle.go
- e2e/scripts/validate-support-bundle.sh
- pkg/goods/support/host-support-bundle-remote.yaml
latest version of troubleshoot now supports bypassing errors when reading support bundle specs from the cluster (https://github.com/replicatedhq/troubleshoot/pull/1660). in the previous version it used to fail.
this pr also makes the `embedded-cluster support-bundle` command use the kubeconfig as an environment variable.
```release-note
```
> chore: bump troubleshoot to allow optional cluster specs

- cmd/embedded-cluster/support_bundle.go
- only sets kubeconfig environment variable if the kubeconfig file exists.
- print a better message if the support-bundle binary does not exist on disk.
- print the support bundle tar.gz file location.
> chore: improvements to support-bundle command

- pkg/kotscli/kotscli.go
> chore: remove spurious printf

- cmd/embedded-cluster/install.go
This fixes a panic when a `warn` preflight fails and prompts the customer to proceed. If the customer chooses to proceed we were trying to write to a closed channel we use to write to stdout.
https://github.com/replicated-collab/datastax-kots/issues/86
```release-note
Fix panic when customer gets prompted to act on a warning on preflight checks.
```
NONE
> fix(preflights): panic on preflight warnings

- operator/charts/embedded-cluster-operator/troubleshoot/cluster-support-bundle.yaml
The support bundles doesn't include some namespaces that are necessary to debug some failure condistion.
> Add additional namespaces for collection

- pkg/preflights/host-preflight.yaml
we require users to manually enable ip forwarding on their nodes before installing. this preflight checks if ip forwarding is enabled and fails if it is not.
```release-note
Added preflight for IP forwarding.
```
> feat: add preflight for ip forwarding

- pkg/defaults/cloudprovider.go
- pkg/defaults/defaults.go
AWS IMDSv2 required
```
ubuntu@ip-172-31-75-103:~$ sudo ./embedded-cluster-smoke-test-staging-app install --license license.yaml --skip-host-preflights
? Set the Admin Console password (minimum 6 characters): ********
? Confirm the Admin Console password: ********
✔  Host preflights skipped
✔  Node installation finished!
✔  Storage is ready!
✔  Embedded Cluster Operator is ready!
✔  Admin Console is ready!
✔  Additional components are ready!
Visit the Admin Console to configure and install embedded-cluster-smoke-test-staging-app: http://172.31.75.103:30000
```
GCP
```
ethan@ethanm-ec-1:~$ sudo ./embedded-cluster-smoke-test-staging-app install --license license.yaml
? Set the Admin Console password (minimum 6 characters): ********
? Confirm the Admin Console …
```
> feat: support for aws ec2 imdsv2

- operator/charts/embedded-cluster-operator/troubleshoot/cluster-support-bundle.yaml
Label is incorrect
```
"labels": {
"app": "docker-registry",
"pod-template-hash": "6b5bc4cc97",
"release": "docker-registry"
},
```
```release-note
Fixes an issue that causes registry logs to be missing from the support bundle.
```
> fix(registry): logs missing from support bundle

- operator/pkg/artifacts/upgrade_test.go
- pkg/defaults/cloudprovider.go
- pkg/defaults/cloudprovider_test.go
Cant retrieve standard sku address from instance metadata
https://learn.microsoft.com/en-us/answers/questions/7932/public-ip-not-available-via-metadata
```
azureuser@ethan-1:~$ sudo ./embedded-cluster-smoke-test-staging-app install --license license.yaml --skip-host-preflights
? Set the Admin Console password (minimum 6 characters): ********
? Confirm the Admin Console password: ********
✔  Host preflights skipped
✔  Node installation finished!
✔  Storage is ready!
✔  Embedded Cluster Operator is ready!
✔  Admin Console is ready!
✔  Additional components are ready!
Visit the Admin Console to configure and install embedded-cluster-smoke-test-staging-app: http://52.249.223.56:30000
```
```release-note
Fixes an issue when installing in Azure that caused the …
```
> fix: fail to discover azure standard sku public ip address

- dev/distros/dockerfiles/almalinux-8.Dockerfile
- dev/distros/dockerfiles/centos-9.Dockerfile
- dev/distros/dockerfiles/debian-bookworm.Dockerfile
- dev/distros/dockerfiles/debian-bullseye.Dockerfile
- dev/distros/dockerfiles/ubuntu-jammy.Dockerfile
- dev/distros/entrypoint.sh
- e2e/cluster/docker/container.go
Fixes clock sync flakiness for debian and ubuntu which occurs in both CI and dev env
NONE
```release-note
NONE
```
NONE
> Fix clock sync flakiness for docker-based clusters

- .github/workflows/ci.yaml
- .github/workflows/release-prod.yaml
This PR adds a online installation to our pre-release post-tag test suite.
```release-note
```
> run online ci tests against tagged releases

- pkg/cmd/install.go
- pkg/cmd/join.go
- pkg/cmd/restore.go
- pkg/release/release.go
> [!IMPORTANT]  
> for this to work we need to merge https://github.com/replicatedhq/vandoor/pull/6374 first.
vendor portal informs us (through the embedded channel release struct) if the binary was downloaded with or without an  airgap bundle.
if the binary was downloaded with an airgap bundle, we should warn the user we must warn the users if they attempt to install the binary without passing in the airgap bundle flag.
```release-note
Warn users if an online installation is executed with an air gap prepared installer binary.
```
> feat: warn if online installation is attempted on air gap

- scripts/ci-build-deps.sh
Was facing some local dev issues when creating an installation:
> unable to wait for installation to be ready: error waiting for installation: helm chart installation failed: failed to update helm charts:
embedded-cluster-operator: can't locate chart `oci://proxy.replicated.com/anonymous/ttl.sh/jgantunes/embedded-cluster-operator-1.18.0+k8s-1.30-11-g088bf8d5`: proxy.replicated.com/anonymous/ttl.sh/jgantunes/embedded-cluster-operator:1.18.0_k8s-1.30-11-g088bf8d5: not found
Seems like the metadata file generated for the operator was missing the `-<username>` suffix for the chart version. This should fix it.
NONE
```release-note
NONE
```
NONE
> chore(local-dev): fixes the metadata generation file for the operator version

- pkg/cmd/install.go
- pkg/cmd/join.go
- pkg/cmd/preflights.go
- pkg/cmd/reset.go
- pkg/cmd/restore.go
- pkg/configutils/runtime.go
- pkg/configutils/runtime_test.go
- pkg/goods/goods.go
- pkg/goods/materializer.go
- pkg/goods/materializer_test.go
- pkg/goods/static/99-embedded-cluster.conf
we are now enabling ip_forward on the node, this is required for the embedded-cluster to work properly. we are also disabling arp_ignore and arp_filter to make sure the system is prepared for calico.
```release-note
Auto configure system parameters for ip_forward, arp_filter and arp_ignore
```
We need to document that the installer now requires the `sysctl` command to be present on the target system. This command is found in the `procps` (Debian/Ubuntu) or `procps-ng` (Rocky Linux / RHEL) package.
> feat: enable ip_forward, disable arp_ignore arp_filter

- pkg/cmd/join.go
> chore: fix message when join node is not included in the no-proxy addresses

- pkg/cmd/install.go
Use the warn function so the text is yellow and makes the warning more clear to users.
NONE
```release-note
NONE
```
NONE
> Use warn function when doing online install after downloading air gap

- .github/workflows/distros.yaml
- dev/distros/dockerfiles/almalinux-8.Dockerfile
- dev/distros/dockerfiles/centos-9.Dockerfile
- dev/distros/dockerfiles/debian-bookworm.Dockerfile
- dev/distros/dockerfiles/debian-bullseye.Dockerfile
- dev/distros/dockerfiles/ubuntu-jammy.Dockerfile
- e2e/install_test.go
- e2e/unsupported-overrides_test.go
Includes `binutils` in EC distro images to avoid network flakiness
Example flakiness: https://github.com/replicatedhq/embedded-cluster/actions/runs/11843290988/job/33004470938?pr=1487#step:8:56
NONE
```release-note
NONE
```
NONE
> Include binutils in distro images to avoid network flakiness

- .github/workflows/release-prod.yaml
We don't want our vendors to use 'v' prefixes for their embedded cluster versions, so we shouldn't either in our prerelease testing.
```release-note
```
> do not use a 'v' prefix for the embedded cluster version in post-release testing

- pkg/cmd/join.go
Mention that HA can be enabled on or after 3rd node, not just on 3rd node. Also a slight reword for brevity/clarity.
NONE
```release-note
NONE
```
NONE
> Mention that HA can be enabled on or after 3rd node, not just on 3rd node

- pkg/preflights/host-preflight.yaml
Follow up to https://github.com/replicatedhq/embedded-cluster/pull/1500 we should use the already existing `sysctl` collector for the `ip_forwarding` check
NONE
I run a manual test locally, however it's hard to reproduce with the recent changes introduced in - https://github.com/replicatedhq/embedded-cluster/pull/1484. Instead I cherry picked the analyzer and collector and run them separately using the preflight binary:
After `sysctl net.ipv4.ip_forward=0`
```release-note
NONE
```
NONE
> chore(preflights): replace run collector with host sysctl for ip_forwarding

- e2e/kots-release-install/deployment-2.yaml
- e2e/kots-release-upgrade/deployment-2.yaml
- e2e/scripts/check-airgap-post-ha-state.sh
This PR adds a change to the airgap HA migration validation. Previously, we did not actually pull images from the registry post-migration before having kots push images to the registry again - which would work if we did not actually migrate registry data. Now, we scale a deployment that has a 'prefer not on the same node' scheduling restriction, and make sure that those pods reach a running state.
```release-note
```
> validate that the registry is still available for pulls after HA migration

- pkg/cmd/install.go
Updates the help for `--config-values`, and alphabetizes the CLI flags
NONE
```release-note
NONE
```
> Update config value help, and alphabetize flags

- e2e/install_test.go
- pkg/logging/logging.go
Prior to this change log.Warn and log.Error goes to stderr while info goes to stdout.
For example:
Vs after the change
```release-note
Error and warning logs from the CLI now go to stdout rather than stderr with the rest of the output.
```
> fix: cli warn and error should go to stdout like the lower levels

- pkg/cmd/install.go
- pkg/cmd/restore.go
After talking with Paige, make the air gap bundle warning messages more clear. Focus on the use of the air gap bundle over calling something an online or air gap install.
Also make it a warning.
NONE
```release-note
NONE
```
NONE
> Clarify air gap bundle warning

- .gitignore
Maybe this is a me thing but when developing preflights and testing them out locally it's easy to end up with a bunch of `preflightbundle*.tar.gz` files laying around. This just prevents committing them by accident.
NONE
```release-note
NONE
```
NONE
> chore(gitignore): ignore preflight bundles

- e2e/airgap.go
an update to the API code makes these requests fail fast if there is no airgap bundle built instead of allowing a 300mb download, so there was dramatically less time being spent in this function than before
```release-note
```
> increase maximum airgap bundle build wait from 10m to 20m, with shorter increments

- pkg/metrics/reporter.go
- pkg/metrics/reporter_test.go
- pkg/metrics/util.go
- pkg/metrics/util_test.go
Redact secrets sent through the metrics package through the flags parameter for installations. We do this by filtering the provided flags and, upon detecting predefined flags, redact the provided values and replace them by `"*****"`.
https://app.shortcut.com/replicated/story/116082/redact-secrets-from-embedded-cluster-bot-alerts-slack-channel
Automated tests added.
```release-note
Redact potential secret information sent to our metrics backend through the provided flag parameters
```
NONE
> fix(metrics): redact specific flags which might hold secrets

- pkg/runtimeconfig/runtimeconfig.go
Adds a comment about nil runtime config in old installation objects
NONE
```release-note
NONE
```
NONE
> Add comment about nil runtime config in old installation objects

- .github/workflows/ci.yaml
- common.mk
- dagger/main.go
- operator/deploy/apko.tmpl.yaml
- operator/deploy/melange.tmpl.yaml
- pkg/addons/adminconsole/adminconsole.go
- scripts/build-and-release.sh
- scripts/ci-build-bin.sh
- scripts/ci-build-deps.sh
- scripts/ci-embed-release.sh
- scripts/ci-release-app.sh
- scripts/ci-upload-binaries.sh
For more context see - https://replicated.slack.com/archives/C0499EGNPNY/p1732733447572059
With the latest `melange` changes through - https://github.com/chainguard-dev/melange/pull/1622 - our CI pipelines started failing with:
```
INFO error during command execution: failed to build image components: building layers: building layers: for arch "amd64": installing apk packages: installing packages: installing embedded-cluster-operator (ver:1.19.0+k8s-1.30-59-gf845a740-upgrade-r0 arch:x86_64): unable to update scripts.tar for pkg embedded-cluster-operator: unable to write scripts header for embedded-cluster-operator-1.19.0+k8s-1.30-59-gf845a740-upgrade-r0.Q17P2Pb+0fdYeQTtIVeyqFDm8XEYE=.melange.yaml: archive/tar: cannot encode header: Format specifies USTAR; and USTAR cannot encode …
```
> chore(ci): address melange's latest change

- cmd/installer/cli/join_runpreflights.go
Similar to - https://github.com/replicatedhq/embedded-cluster/pull/1567
Running join run-preflights (...) errors out because we're not defining the skip-host-preflights and ignore-host-preflights flag. E.g.
```
root@node1:/replicatedhq/embedded-cluster# output/bin/embedded-cluster join run-preflights 172.17.0.2:30000 HBA9OCthEHACKgtxIhYrHbfp
✗
Error: unable to get skip-host-preflights flag: flag accessed but not defined: skip-host-preflights
unable to get skip-host-preflights flag: flag accessed but not defined: skip-host-preflights
```
This PR should fix it.
https://app.shortcut.com/replicated/story/116682/join-run-preflights-cmd-is-currently-broken-due-to-missing-flags
I've added join capabilities to our dry run test framework in - …
> fix(cli): join run-preflights should define skip & ignore preflights flags with defaults

- Makefile
- cmd/installer/cli/install.go
- cmd/installer/cli/join.go
- cmd/installer/cli/restore.go
- pkg/goods/materializer.go
- pkg/goods/systemd/manager.service
- pkg/runtimeconfig/defaults.go
- pkg/websocket/server.go
Installs and enables the EC manager systemd service on install, join, and restore.
[SC-116592](https://app.shortcut.com/replicated/story/116592)
```release-note
NONE
```
NONE
> Install EC manager systemd service on install, join, and restore

- pkg/goods/support/host-support-bundle.tmpl.yaml
- pkg/support/materialize.go
Includes EC manager systemd service logs in support bundles
[SC-116692](https://app.shortcut.com/replicated/story/116692)
```release-note
NONE
```
NONE
> Include EC manager systemd service logs in support bundles

- cmd/installer/cli/install.go
- cmd/installer/cli/install_runpreflights.go
- cmd/installer/cli/join.go
- cmd/installer/cli/join_runpreflights.go
- pkg/dryrun/dryrun.go
- pkg/dryrun/kotsadm.go
- pkg/kotsadm/client.go
- pkg/kotsadm/interface.go
- pkg/kotsadm/types.go
- pkg/preflights/host-preflight.yaml
- pkg/preflights/template_test.go
- pkg/preflights/types/template.go
- tests/dryrun/join_test.go
- tests/dryrun/util.go
This PR adds support for checking for TCP connections provided by the newly added information to the join endpoint in KOTS - https://github.com/replicatedhq/kots/pull/5004 - we pickup the endpoints provided and create preflight checks based on it.
We also add support for `join` commands in our `dryrun` test utility (which we we use to test this logic).
https://app.shortcut.com/replicated/story/113015/preflight-remote-access-on-join
Yes we've added series of both unit tests and tests using the `dryrun` utility.
~~While working on testing this out locally I've hit - https://app.shortcut.com/replicated/story/116682/join-run-preflights-cmd-is-currently-broken-due-to-missing-flags - which I'm working on fixing through:~~
- ~~https://github.com/replicatedhq/embedded-cluster/pull/1568~~
- …
> feat(preflights): add support for TCP connection checks on the hpc template

- pkg/goods/support/host-support-bundle.tmpl.yaml
Adds `firewalld-cmd --list-all` so we can see what potential firewall rules are in place via `firewalld`
```release-note
```
> Add firewall-cmd --list-all to host support bundle

- cmd/installer/cli/install.go
This was added to install2, adding it in install. We need to set the cobra flag for install because the cobra command object is passed around in a few places.
We don't error and fail if we can't determine the best interface. This allow the current behavior to continue to be the fall through.
> Backport setting the best network interface to install

- .github/actions/scan-image/action.yml
- .trivyignore
- .trivyignore.yaml
CVE-2023-47108 is not in the code path for any Kubernetes component. It does not impact kube-proxy. This PR will silence the alerts about this CVE. See here for context:
https://kubernetes.slack.com/archives/CHGFYJVAN/p1722343995736019?thread_ts=1722343658.235969&cid=CHGFYJVAN
https://github.com/kubernetes/kubernetes/pull/121842
The Scan image job continuously flagged this high CVE, but it is a false positive.
no
no
no
> Accept CVE 2023 47108

- cmd/installer/cli/cidr.go
- cmd/installer/cli/install.go
- pkg/netutils/nets.go
- pkg/netutils/nets_test.go
When you pass a bad CIDR block, the output looks like a wrapped Go error. This isn't helpful to users. Now, the errors are clear sentences to help people fix the problem.
NONE
```release-note
NONE
```
NONE
Example:
```
root@node0:/replicatedhq/embedded-cluster# sudo ./output/bin/embedded-cluster install --cidr 16.0.0.0/16
The provided CIDR block (16.0.0.0/16) is not in a private IP address range (10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16)
```
> Don't wrap CIDR errors

- .github/actions/scan-image/action.yml
- .trivyignore
- .trivyignore.yaml
Looks like the trivyignore approach with the trivyignore yaml file [didn't work](https://github.com/replicatedhq/embedded-cluster/actions/runs/12279581825/job/34264596355). I believe this is because the [trivy github action](https://github.com/aquasecurity/trivy-action/blob/18f2510ee396bbf400402947b394f2dd8c87dbb0/entrypoint.sh#L11-L28) converts the *.yaml files into flat files. But trivy will only parse yaml files if they [end with a yaml or yml extension](https://trivy.dev/latest/docs/configuration/filtering/#by-finding-ids:~:text=When%20the%20extension%20of%20the%20specified%20ignore%20file%20is%20either%20.yml%20or%20.yaml%2C%20Trivy%20will%20load%20the%20file%20as%20YAML.%20For%20the%20.trivyignore.yaml%20file%2C%20you%20can%20set%20ignored%20IDs%20separately%20for%20vulnerabilities%2 …
> Using a flat irvyignore file to be compatible with GHA

- .github/workflows/ci.yaml
- .github/workflows/image-scan.yaml
- .github/workflows/release-prod.yaml
Fixes
```
Run curl -fsSL https://dl.dagger.io/dagger/install.sh | sh
sh debug downloading files into /tmp/tmp.bMCBLN2FOj
sh debug http_download https://dl.dagger.io/dagger/releases/0.1[5](https://github.com/replicatedhq/embedded-cluster/actions/runs/12304485085/job/34342009714?pr=1619#step:5:6).1/dagger_v0.15.1_linux_amd64.tar.gz
sh debug http_download https://dl.dagger.io/dagger/releases/0.15.1/checksums.txt
sh err hash_sha25[6](https://github.com/replicatedhq/embedded-cluster/actions/runs/12304485085/job/34342009714?pr=1619#step:5:7)_verify checksum for '/tmp/tmp.bMCBLN2FOj/dagger_v0.15.1_linux_amd64.tar.gz' did not verify 5230bfd932ecaa02266efd830c5cf[7](https://github.com/replicatedhq/embedded-cluster/actions/runs/12304485085/job/34342009714?pr=1619#step:5:8)93367433242aec2ff6b3c13323[ …
```
> chore(ci): fix dagger install, pin to 1.14.0

- pkg/goods/support/host-support-bundle.tmpl.yaml
Update hard coded paths of `mount`, `umount` and `modprobe` in support bundle analysers.
https://app.shortcut.com/replicated/story/117469/fix-hard-coded-path-host-preflight-checks-in-ec
NONE
```release-note
Update hard coded paths of mount, umount and modprobe in support bundle analysers.
```
> fix: Update hard coded paths of system binaries in support bundle analysers

- operator/controllers/installation_controller.go
Handles error
```
2024-12-18T20:19:03Z	ERROR	Reconciler error	{"controller": "installation", "controllerGroup": "embeddedcluster.replicated.com", "controllerKind": "Installation", "Installation": {"name":"20241218201903"}, "namespace": "", "name": "20241218201903", "reconcileID": "4ae2dd88-5eb6-4b9b-a4f8-d1d2d26d8400", "error": "failed to copy host preflight results: failed to create job: jobs.batch \"copy-host-preflight-results-node-027db-00\" already exists"}
```
```release-note
```
> fix: handle copy preflight results job already exists error

- pkg/preflights/host-preflight.yaml
Story details: https://app.shortcut.com/replicated/story/117743
I used less strict regex to validate IP address for readability.
> feat: [sc-117743] preflight check:  ensure valid nameservers in /etc/resolv.conf

- .github/workflows/ci.yaml
Removes the 5 node cluster test from the on pr suite and runs on merge only.
It’s not cover any scenarios that other tests aren’t testing other than to test scale and it is very flakey.
```release-note
```
> chore(ci): run TestFiveNodesAirgapUpgrade on main only

- cmd/installer/cli/restore.go
- pkg/disasterrecovery/backup.go
- pkg/disasterrecovery/backup_test.go
The creation timestamp represents the time at which the CR was created in the new restore cluster and does not reflect the creation timestamp of the backup. Revert the change to use prior Status.CompletionTimestamp field.
```release-note
```
> fix(dr): use Status.CompletionTimestamp for sorting backups

- cmd/installer/cli/restore.go
Improved dr should not restore the component app backup as well as the custom restore cr.
```release-note
```
> fix(dr): improved dr should not restore the component app backup

- kinds/apis/v1beta1/installation_types.go
- operator/controllers/installation_controller.go
- operator/pkg/charts/reconcile.go
- operator/pkg/cli/logging.go
- operator/pkg/cli/migrate_v2_pod.go
- operator/pkg/cli/migratev2/installation.go
- operator/pkg/cli/migratev2/installation_test.go
- operator/pkg/cli/migratev2/migrate.go
- operator/pkg/cli/migratev2/operator.go
- operator/pkg/cli/migratev2/operator_test.go
- pkg/kubeutils/kubeutils.go
Fixes an issue where the operator would not finish reconciling the installation before the migration runs leaving the upgrade in an unfinished state.
```release-note
```
> feat(ec): migration from v1 to v2 - fixes

- scripts/ci-upload-binaries.sh
Keeps the 'v' in the version when pushing the manager binary to s3 so it matches the version in the metadata file.
No
```release-note
NONE
```
NONE
> Keep 'v' when pushing manager binary to s3

- cmd/installer/cli/install2.go
- cmd/installer/cli/restore.go
- cmd/installer/cli/restore2.go
- e2e/scripts/resume-restore.exp
- operator/controllers/installation_controller.go
- operator/pkg/cli/upgrade.go
- operator/pkg/k8sutil/installation.go
- operator/pkg/upgrade/installation.go
- operator/pkg/upgrade/upgrade.go
- pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
- pkg/addons2/adminconsole/values.go
- pkg/addons2/highavailability.go
- pkg/dryrun/kubeutils.go
- pkg/extensions/install.go
- pkg/highavailability/enable.go
- pkg/kubeutils/interface.go
- pkg/kubeutils/kubeutils.go
> feat(v2): enable v2 restore

- operator/pkg/upgrade/upgrade.go
- pkg/extensions/upgrade.go
- pkg/extensions/upgrade_test.go
- pkg/extensions/util.go
- Respects ForceUpgrade
- Respects order
```release-note
```
> feat(v2): fix extensions apply

- e2e/kots-release-upgrade/cluster-config.yaml
- hack/test-installation.yaml
upgrade failed
https://github.com/replicatedhq/embedded-cluster/actions/runs/13165274805/job/36744352264?pr=1814
```
Error: upgrade extensions: upgrade extensions: install extension memcached: process extension: install: helm install: pull oci: download chart oci://registry-1.docker.io/bitnamicharts/memcached: failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/bitnamicharts/memcached/manifests/sha256:514981dbfb2df3d4a08b0e6622ae3fb569ead6d9da14580e5b66b668d3ddc68c: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```
```release-note
```
> fix(ci): proxy chart to avoid 429 errors

- operator/charts/embedded-cluster-operator/troubleshoot/cluster-support-bundle.yaml
seaweedfs-bucket-hook logs are missing
```
kubectl -n seaweedfs get pods --show-labels
NAME                          READY   STATUS    RESTARTS   AGE     LABELS
seaweedfs-bucket-hook-kc4bp   0/1     Error     0          3h31m   app.kubernetes.io/instance=seaweedfs,app.kubernetes.io/managed-by=Helm,batch.kubernetes.io/controller-uid=2ccab79d-52ba-435e-bbe7-1d3a21724c08,batch.kubernetes.io/job-name=seaweedfs-bucket-hook,controller-uid=2ccab79d-52ba-435e-bbe7-1d3a21724c08,job-name=seaweedfs-bucket-hook
seaweedfs-bucket-hook-lxmp5   1/1     Running   0          3h26m   app.kubernetes.io/instance=seaweedfs,app.kubernetes.io/managed-by=Helm,batch.kubernetes.io/controller-uid=2ccab79d-52ba-435e-bbe7-1d3a21724c08,batch.kubernetes.io/job-name=seaweedfs-bucket-hook,controller-uid=2ccab79d-52ba-435e- …
```
> fix(seaweedfs): collect logs from all pods in the namespace

- pkg/helm/client.go
rollback on installation makes things hard to debug as it deletes pods and i cannot get logs
```release-note
```
> fix(v2): disable atomic rollback on helm install addon

- pkg/addons/seaweedfs/install.go
fails with
```
unable to enable high availability: install seaweedfs: create prerequisites: create s3 service: create s3 service: Service "ec-seaweedfs-s3" is invalid: spec.clusterIPs: Invalid value: []string{"10.244.128.12"}: failed to allocate IP 10.244.128.12: provided IP is already allocated
```
```release-note
```
> fix(v2): retry enabling ha fails

- .github/workflows/ci.yaml
- e2e/restore_test.go
Instead of building a legacy-dr embedded cluster binary, use the normal binary and rely on replicated.app to embed the relevant app yaml files into it.
```release-note
```
> do not build a separate binary for the legacy-dr test suite

- pkg/addons/adminconsole/static/values.tpl.yaml
- pkg/helm/client.go
- pkg/helm/client_test.go
Fixes an issue when cleaning up helm values before install / upgrade where `[]map[string]interface{}` types weren't handled, which broke admin console upgrades in some scenarios.
```release-note
NONE
```
NONE
> Fix cleaning up helm values before install / upgrade

- cmd/installer/cli/install.go
resuming the restore process requires the `KUBECONFIG` env var to be set in order to read the restore state from the cluster at the beginning.
```release-note
NONE
```
NONE
> Fix ability to resume restores

- cmd/installer/cli/testing/assets/release-restore-newdr/restore.yaml
- e2e/kots-release-install-failing-preflights/restore.yaml
- e2e/kots-release-install-warning-preflights/restore.yaml
- e2e/kots-release-install/restore.yaml
- e2e/kots-release-unsupported-overrides/restore.yaml
- e2e/kots-release-upgrade/restore.yaml
- e2e/playwright/tests/deploy-upgrade/test.spec.ts
- e2e/playwright/tests/shared/app-state.ts
- e2e/playwright/tests/shared/deploy-app.ts
- e2e/playwright/tests/shared/deploy-ec18-app-version.ts
- e2e/playwright/tests/shared/index.ts
- e2e/playwright/tests/validate-restore-app/test.spec.ts
- e2e/restore_test.go
- Uses template function to rewrite image to local registry in restore hook for airgap
- Validates app and cluster state in browser after restore.
On restore hook image is not rewritten.
```
nginx-9665fb944-xckxt                 0/1     Init:ImagePullBackOff   0          113s
```
```
initContainers:
- command:
- /bin/ash
- -c
- echo -n "FOOBARBAZ" > /tmp/foobarbaz
image: proxy.replicated.com/anonymous/nginx:1.24-alpine
```
```release-note
```
> fix(ci): e2e app airgap restore image pull backoff

- pkg/addons/adminconsole/values.go
- pkg/addons/openebs/values.go
- pkg/addons/seaweedfs/values.go
- pkg/addons/velero/values.go
- pkg/helm/values.go
- pkg/helm/values_test.go
- tests/dryrun/install_test.go
Makes setting values mimic helm's --set-json argument.
```release-note
```
> fix: make helm.SetValue more robust

- pkg/extensions/util.go
- pkg/helm/client.go
- pkg/helm/client_test.go
- pkg/helm/images.go
- pkg/helm/values.go
Makes map conversion more resilient. No longer have to add new case statements for each type.
```release-note
```
> chore: fix generic map conversion

- cmd/installer/cli/install.go
- cmd/installer/cli/install_runpreflights.go
- cmd/installer/cli/join.go
- cmd/installer/cli/join_runpreflights.go
- cmd/installer/cli/restore.go
- pkg/configutils/runtime.go
- pkg/configutils/static/99-embedded-cluster.conf
- pkg/preflights/host-preflight.yaml
In Kubernetes environments, reverse path filtering can disrupt networking, particularly when communicating with cluster services from the host. This is because Kubernetes networking paths are not always seen as the "best reverse path" by the kernel.
This PR adds host preflights for `rp_filter` kernel parameter to ensure that it is disabled.
[SC-117729](https://app.shortcut.com/replicated/story/117729)
```release-note
Adds preflight checks to ensure that the following kernel parameters are set: `net.ipv4.conf.default.rp_filter = 0`, and `net.ipv4.conf.all.rp_filter = 0`.
```
NONE
> Add preflights for rp_filter kernel parameter

- pkg/configutils/static/99-embedded-cluster.conf
- pkg/preflights/host-preflight.yaml
Looks like Calico [doesn't rely on sysctls](https://github.com/projectcalico/calico/blob/v3.12.0/release-notes/v3.12.0-release-notes.md#other-changes) to determine RPF anymore, so setting it to `2` shouldn't be an issue and is what's recommended and common.
This PR makes it so that we try to set `rp_filter` to loose mode (`2`) instead of disabled (`0`), but if we can't, we only fail if `rp_filter` is set to strict mode (`1`).
[SC-117729](https://app.shortcut.com/replicated/story/117729)
```release-note
Adds preflight checks to ensure that reverse path filtering (rp_filter) is either disabled (0) or set to loose mode (2) for both default and all interfaces via kernel parameters `net.ipv4.conf.default.rp_filter` and `net.ipv4.conf.all.rp_filter`.
```
NONE
> Default rp_filter to loose mode (2) instead of disabled (0)

- pkg/preflights/host-preflight.yaml
Adds an SELinux host preflight check that fails if SELinux is running in `enforcing` mode.
```bash
[salah@salah-selinux ~]$ getenforce
Enforcing
[salah@salah-selinux ~]$ sudo ./embedded-cluster-smoke-test-staging-app install run-preflights --license license.yaml
✗  1 host preflight failed
•  SELinux must be disabled or run in permissive mode. 
Please address this issue and try again.
[salah@salah-selinux ~]$ sudo setenforce 0
[salah@salah-selinux ~]$ getenforce
Permissive
[salah@salah-selinux ~]$ sudo ./embedded-cluster-smoke-test-staging-app install run-preflights --license license.yaml
✔  Host preflights succeeded!
Host preflights completed successfully
```
[SC-110719](https://app.shortcut.com/replicated/story/110719) …
> Add SELinux host preflight check

- cmd/installer/cli/install.go
- cmd/installer/cli/install_runpreflights.go
- cmd/installer/cli/join.go
- cmd/installer/cli/join_runpreflights.go
- cmd/installer/cli/restore.go
- pkg/configutils/runtime.go
- pkg/configutils/static/modules-load.d/99-embedded-cluster.conf
- pkg/configutils/static/sysctl.d/99-embedded-cluster.conf
This pr duplicates the [kernel configuration](https://github.com/k0sproject/k0s/blob/fb9fb09cdbea20afa64fbb0218c7eca0ac0a61c7/pkg/component/worker/kernelsetup_linux.go#L62-L82) from k0s as it is set using sysctl and is not persistent. It also duplicates the modprobe commands to enable and persist them.
It moves the call to ConfigureSysctl in the restore command to only run when this is a new restore, so as not to revert any settings that are set by installing k0s or extensions.
```release-note
```
> fix: configure kernel modules and settings per k0s

- pkg/preflights/host-preflight.yaml
install fails in dev env on docker for mac with
```
✗  4 host preflights failed
•  The 'overlay' kernel module is not loaded or loadable      
•  The 'ip_tables' kernel module is not loaded or loadable    
•  The 'br_netfilter' kernel module is not loaded or loadable 
•  The 'nf_conntrack' kernel module is not loaded or loadable 
Please address these issues and try again.
```
This is because of weirdness with linuxkit
```
root@node0:/replicatedhq/embedded-cluster# lsmod
Module                  Size  Used by
shiftfs                28672  -2
selfowner              28672  -2
rosetta                12288  -2
grpcfuse               12288  -2
fakeowner             122880  -2
```
```release-note
```
> fix(dev): skip kernel module preflight checks on docker for mac

- cmd/installer/cli/install.go
- cmd/installer/cli/join.go
- cmd/installer/kotscli/kotscli.go
Checks systemctl status of LAM after installing and starting before proceeding with the rest of the install.
```release-note
```
> fix(lam): wait for service after start

- cmd/installer/cli/join_runpreflights.go
- pkg/preflights/host-preflight.yaml
- pkg/preflights/run.go
- pkg/preflights/template_test.go
- pkg/preflights/types/template.go
- tests/dryrun/join_test.go
Removes cidr flags from instructions of join preflights as these flags aren't available.
```release-note
NONE
```
NONE
> Remove cidr flags from instructions of join preflights

- cmd/installer/goods/support/host-support-bundle.tmpl.yaml
- pkg/preflights/host-preflight.yaml
Pass if system clock is synced even if NTP is inactive as it might be managed by other protocols (e.g. PTP).
Example:
```
$ sudo pmc -u -b 0 'GET TIME_STATUS_NP'
sending: GET TIME_STATUS_NP
000000.fffe.000002-0 seq 0 RESPONSE MANAGEMENT TIME_STATUS_NP 
master_offset              239
ingress_time               1739906646275502611
cumulativeScaledRateOffset +0.000000000
scaledLastGmPhaseChange    0
gmTimeBaseIndicator        0
lastGmPhaseChange          0x0000'0000000000000000.0000
gmPresent                  true
gmIdentity                 000000.fffe.000001
$ timedatectl status
...
System clock synchronized: yes
NTP service: n/a
...
$ cat preflightbundle-2025-02-18T19_16_16/analysis.json
[
...
"detail": "NTP is inactive but the system clock is synchronized",
...
]
``` …
> Pass if clock is synced even if ntp is inactive

- Makefile
- go.mod
- go.sum
Updates troubleshoot with this change
https://github.com/replicatedhq/troubleshoot/pull/1741
```release-note
Fixes host preflight failures for kernel modules in environments where kernel modules are built in.
```
> fix(host-preflights): buildtin kernel modules file from wrong path

- pkg/configutils/runtime.go
- pkg/configutils/runtime_test.go
- pkg/preflights/host-preflight.yaml
This PR adds dynamic sysctl configuration to ensure proper system settings for the embedded cluster. It:
- Automatically configures `fs.inotify.max_user_instances` and `fs.inotify.max_user_watches sysctl` values.
- Generates a dynamic sysctl config file that only updates their values when they're below required minimums
- Adds preflight checks to ensure the values meets the required minimums
[SC-119426](https://app.shortcut.com/replicated/story/119426)
Yes - unit tests have been added to verify the dynamic sysctl configuration logic.
```release-note
The following kernel parameters are configured automatically: `fs.inotify.max_user_instances = 1024` and `fs.inotify.max_user_watches = 65536`.
```
NONE
> Ensure inotify settings meet the minimum requirements

- cmd/installer/cli/install.go
- cmd/installer/cli/join.go
Waits for both k0s and node to be ready before proceeding.
[SC-116308](https://app.shortcut.com/replicated/story/116308)
```release-note
* Enhances installation reliability by adding proper wait conditions for k0s and node readiness before proceeding with subsequent installation steps.
```
NONE
> Wait for k0s and node to be ready before proceeding

- Makefile
- cmd/installer/cli/install.go
- cmd/installer/cli/join.go
- e2e/preflights_test.go
- go.mod
- go.sum
- pkg/preflights/host-preflight.yaml
- pkg/runtimeconfig/runtimeconfig.go
This PR ensures that the k0s data directory and its parent directories have execute permissions. This is necessary for the k0s etcd user to execute the etcd binary. Without proper execute permissions, the etcd service will fail to start, causing cluster initialization failures.
Fixes:
- [SC-120515](https://app.shortcut.com/replicated/story/120515)
- [SC-120528](https://app.shortcut.com/replicated/story/120528)
```release-note
* Adds a preflight check to verify execute permissions on the data directory and its parent directories, preventing cluster startup failures due to etcd permission issues.
```
NONE
> Add preflight check for directory permissions to prevent etcd startup failures

- e2e/cluster/lxd/cluster.go
Tars directories before copying them to lxc container rather than copying files one at a time.
```release-note
```
> chore(ci): lxd copy dir tar

- cmd/installer/cli/install.go
- cmd/installer/cli/install_runpreflights.go
- cmd/installer/cli/metrics.go
- cmd/installer/cli/release.go
- cmd/installer/cli/restore.go
- pkg/metrics/interface.go
- pkg/metrics/reporter.go
- pkg/metrics/reporter_test.go
When we fully support custom domains we need to ensure we do not reach out to replicated.app
```release-note
```
> feat: ensure use of custom domains in metrics reporting

- cmd/installer/cli/proxy_test.go
- pkg/runtimeconfig/defaults.go
```release-note
The common cloud metadata service IP address "169.254.169.254" is now added to the NO_PROXY list by default.
```
> feat(customdomains): add metadata service to default no proxy list

- operator/charts/embedded-cluster-operator/troubleshoot/cluster-support-bundle.yaml
Removing the support bundle URI as it conflicts with the custom domains work.
```release-note
```
> feat(customdomains): disable support bundle uri

- .github/workflows/update-addons.yaml
Unpins seaweedfs chart version to update to latest version and get CVE fixes
```release-note
NONE
```
NONE
> Unpin seaweedfs chart version

- go.mod
- tests/dryrun/Dockerfile
- tests/dryrun/assets/cluster-config-nodomains.yaml
- tests/dryrun/assets/cluster-config.yaml
- tests/dryrun/assets/install-release.yaml
- tests/dryrun/install_test.go
- tests/dryrun/util.go
This adds a new dryrun test that runs without any custom domains set, and updates the default dryrun tests to have a EC config object with custom domains set.
It then checks that images (helm chart and k0s) use the correct repositories.
```release-note
```
> integration tests without custom domains

- .github/actions/e2e-troubleshoot/action.yml
Instruct users to use `sbctl shell` instead of `sbctl serve` in GitHub actions log. This was users do not have to create a new shell to run kubectl commands.
```release-note
NONE
```
> chore: print sbctl shell instead of sbctl serve in GitHub actions log

- cmd/installer/cli/join.go
- cmd/installer/cli/reset.go
Warn that you shouldn't join another node when a controller is being joined.
Also update other warns to use `logrus.Warn`.
https://app.shortcut.com/replicated/story/106755/warn-that-you-should-only-join-one-node-at-a-time
NONE
```release-note
When joining a controller node, warn that the user shouldn't join another node until the controller joins successfully.
```
https://github.com/replicatedhq/replicated-docs/pull/3126
> warn about joining controllers in parallel

- cmd/installer/cli/install.go
- cmd/installer/cli/join.go
- pkg/dryrun/kubeutils.go
- pkg/kubeutils/interface.go
- pkg/kubeutils/kubeutils.go
- pkg/runtimeconfig/runtimeconfig.go
- tests/dryrun/join_test.go
Waits for worker node to be ready when joining
```release-note
* Waits for worker nodes to be ready after joining the cluster.
```
NONE
> Wait for worker node to be ready when joining

- cmd/buildtools/embeddedclusteroperator.go
- operator/charts/embedded-cluster-operator/templates/embedded-cluster-troubleshoot-goldpinger.yaml
- operator/charts/embedded-cluster-operator/values.yaml.tmpl
- pkg/addons/embeddedclusteroperator/static/metadata.yaml
- pkg/addons/embeddedclusteroperator/static/values.tpl.yaml
Gets ECO's busybox and goldpinger images from Helm values so that custom domains get propagated to them.
```release-note
NONE
```
NONE
> Support custom domains for ECO's goldpinger support bundle spec

- cmd/installer/goods/support/host-support-bundle.tmpl.yaml
Add Windows Defender security tool in support bundle analyser
```release-note
Add Windows Defender security tool in support bundle analyser
```
> chore: add Windows Defender security tool in support bundle analyser

- .github/workflows/ci.yaml
- Makefile
- cmd/buildtools/k0s.go
- cmd/buildtools/utils.go
- deploy/images/envoy-distroless/apko.tmpl.yaml
- e2e/cluster/docker/cluster.go
- e2e/cluster/lxd/cluster.go
- e2e/install_test.go
- e2e/reset_test.go
- e2e/scripts/check-nllb.sh
- e2e/scripts/restore-installation-airgap.exp
- e2e/scripts/restore-installation.exp
- e2e/scripts/restore-multi-node-airgap-phase1.exp
- e2e/scripts/restore-multi-node-phase1.exp
- e2e/scripts/resume-restore.exp
- operator/pkg/upgrade/upgrade.go
- operator/pkg/upgrade/upgrade_test.go
- pkg/config/config.go
- pkg/config/images.go
- pkg/config/images_test.go
- pkg/config/static/metadata.yaml
Adds no local load balancing support for new installations.
Upgrades are not supported from previous versions of EC.
According to the [k0s docs](https://docs.k0sproject.io/head/nllb/).
> The k0s worker process on worker nodes that are already running must be restarted for the new configuration to take effect.
Adds a test that resets the first controller node and checks that a pod will still start on a worker node.
```release-note
For new installations, the control plane is now set up as highly available within the cluster, enabling the removal of controller nodes from multi-node clusters without affecting pod scheduling.
```
> feat(ha): node local loadbalancing

- pkg/preflights/host-preflight.yaml
```
ethan@ethanm-ec-3:~$ sudo netstat -tulpn | grep 7443
tcp        0      0 127.0.0.1:7443          0.0.0.0:*               LISTEN      449738/envoy
tcp        0      0 127.0.0.1:7443          0.0.0.0:*               LISTEN      449738/envoy
tcp        0      0 127.0.0.1:7443          0.0.0.0:*               LISTEN      449738/envoy
tcp        0      0 127.0.0.1:7443          0.0.0.0:*               LISTEN      449738/envoy
tcp        0      0 127.0.0.1:7443          0.0.0.0:*               LISTEN      449738/envoy
tcp        0      0 127.0.0.1:7443          0.0.0.0:*               LISTEN      449738/envoy
tcp        0      0 127.0.0.1:7443          0.0.0.0:*               LISTEN      449738/envoy
tcp        0      0 127.0.0.1:7443          0.0.0.0:*               LISTEN …
```
> fix(ec): 7443 only required on loopback interface

- .github/workflows/daily-container-scans.yml
- .github/workflows/scan-container-image.yml
- Adds new image scanning process
- Scan the actual public image on dockerhub
- Use Grype as the scanner
- Use Sarif format as attachment to the repo so it gets added to the code scan results
- Enrich the Sarif with properties we use for reporting purposes
- To determine the image tag we use the release version from this repo
- We scan the public image to ensure we are scanning what people are using. If we were to build the image and scan, we would actually be scanning a new image instead of the current release.
None
None
```release-note
NONE
```
No
> add jobs to scan released images

- operator/charts/embedded-cluster-operator/values.yaml.tmpl
- pkg/addons/openebs/static/values.tpl.yaml
- pkg/addons/registry/static/values-ha.tpl.yaml
- pkg/addons/registry/static/values.tpl.yaml
- pkg/addons/seaweedfs/static/values.tpl.yaml
- pkg/addons/velero/static/values.tpl.yaml
Only runs our components on controller nodes.
```release-note
* Ensures that Embedded Cluster components only run on control planes.
```
NONE
> Only run our components on controller nodes

- pkg/preflights/run.go
We're sending `PreflightsBypassed` even when the user doesn't bypass them.
I ran an install where preflights failed:
```
core@alex-ec-selinux:~$ sudo ./gitea-mastodon install -l license.yaml
? Set the Admin Console password (minimum 6 characters): ******
? Confirm the Admin Console password: *****
Passwords don't match. Please try again.
? Set the Admin Console password (minimum 6 characters): ******
? Confirm the Admin Console password: ******
✗  1 host preflight failed
•  SELinux must be disabled or run in permissive mode. To run SELinux in permissive mode, edit /etc/selinux/config, change the line
'SELINUX=enforcing' to 'SELINUX=permissive', save the file, and reboot. You can run getenforce to verify the change."
Please address this issue and try again.
``` …
> don't report preflights bypassed if they weren't

- cmd/installer/cli/join.go
- cmd/installer/cli/reset.go
install already has this
NONE
```release-note
Adds `-y` as an alias for `--yes` in the `join` and `restore` commands.
```
> add -y alias for --yes

- cmd/installer/cli/join.go
- cmd/installer/cli/reset.go
- e2e/install_test.go
- pkg/config/config.go
Today we say "controller node" when talking about HA clusters in the `join` and `reset` commands. Users won't know what a controller role is. This should either say the role name, if they're using roles, or just say "third node" if not.
`join` with node roles:
`reset` with node roles:
`join` without node roles:
`reset` without node roles:
https://app.shortcut.com/replicated/story/106752/better-ux-for-controller-role-name-when-prompting-about-ha
NONE
```release-note
Output from the `join` and `reset` commands no longer mentions "controller nodes," which is terminology users wouldn't be familiar with. The controller node role name is used if custom roles are defined in the Embedded Cluster Config.
```
NONE
> show controller role name in prompts

- cmd/installer/cli/logging.go
I was reading the debug logs for an install and noticed we don't log the version. We should log the version.
```release-note
Debug logs of the installation will now include the Embedded Cluster and k0s versions.
```
> chore: include the embedded cluster and k0s versions in the debug logs

- cmd/installer/cli/install.go
- cmd/installer/cli/join.go
- cmd/installer/cli/reset.go
- e2e/cluster/lxd/cluster.go
- e2e/install_test.go
If a host has a mixed case hostname, k0s will normalise the case to lowercase for the kubernetes node name, but we still check for the node by it's mixed-case name in several places. 
```release-note
Allow running clusters on nodes with hostnames that include uppercase letters.
```
> ToLower() hostnames where it'll be used to address nodes

- .github/actions/e2e/action.yml
- e2e/cluster/lxd/cluster.go
This should speed up the 'e2e' tests by ~5 minutes
```release-note
```
> skip LXD cleanup in e2e tests within CI

- pkg/addons/adminconsole/static/metadata.yaml
Updates from older versions are not showing the updated version as the current version in the ui. The ui in the e2e test screenshots after upgrade shows the old kots version.
What seems to happen is the reload happens before the new kotsadm deployment has rolled out
```
{"type":"resource-snapshot","snapshot":{"_frameref":"frame@5441e467a7cf5ac3316a41031f3638c2","_monotonicTime":321817.372,"startedDateTime":"2025-03-30T12:36:43.905Z","time":135.644,"request":{"method":"GET","url":"http://localhost:30003/main.685f6df444999cd96e8f.js",...
```
```
{
"type": "Progressing",
"status": "True",
"lastUpdateTime": "2025-03-30T12:36:57Z",
"lastTransitionTime": "2025-03-30T12:27:01Z",
"reason": "NewReplicaSetAvailable",
"message": "ReplicaSet \"kotsadm-86c7b98874\" has successfully progressed."
}
``` …
> fix(adminconsole): loads old ui after upgrade

- operator/pkg/upgrade/job.go
- operator/pkg/upgrade/job_test.go
Adds node affinity configuration to prefer scheduling upgrade jobs on control plane nodes, which are typically upgraded first in sequence. This reduces the likelihood of job failures when jobs get scheduled on nodes that haven't been upgraded yet, preventing the job from hitting its backoff limit and causing upgrades to fail.
```release-note
Fixes an issue that can cause cluster upgrades to fail when the upgrade job is scheduled on nodes that have yet to be upgraded by prioritizing control plane nodes, which are typically upgraded first.
```
> feat: add control plane node affinity for upgrade job

- cmd/installer/cli/reset.go
```
error: unable to leave etcd cluster: exit status 1: {"level":"warn","ts":"2025-04-05T12:39:27.465388Z","logger":"etcd-client","caller":"v3@v3.5.17/retry_interceptor.go:63","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000830000/127.0.0.1:2379","attempt":0,"error":"rpc error: code = Unavailable desc = etcdserver: server stopped"}
time="2025-04-05 12:39:27" level=error msg="Failed to delete node from cluster" peerID=314ee8343a8b0c36 peerURL="https://172.17.0.4:2380"
Error: etcdserver: server stopped
```
This isn't desirable.
```release-note
```
> add retries to leaveEtcdcluster

- e2e/kots-release-install-stable/cluster-config.yaml
- e2e/kots-release-unsupported-overrides/cluster-config.yaml
- e2e/scripts/unsupported-overrides.sh
- pkg/config/config.go
- pkg/config/config_test.go
if no worker profiles are set, the profile flag still gets applied but is empty. this causes some problems
```release-note
```
> [bug] don't set profiles flag if no profiles

- cmd/installer/cli/proxy.go
- cmd/installer/cli/proxy_test.go
- e2e/restore_test.go
- e2e/scripts/restore-installation-airgap.exp
- e2e/scripts/restore-multi-node-airgap-phase1.exp
- e2e/scripts/restore-multi-node-airgap-phase2.exp
Tools like `curl` use proxy env vars, but EC doesn't. This has led to confusion when a curl command worked but EC didn't.
https://app.shortcut.com/replicated/story/121571/respect-env-vars-for-http-proxy-https-proxy-and-no-proxy
Updated current tests
```release-note
Proxy information can be set with the `http_proxy`, `https_proxy`, and `no_proxy` environment variables. The corresponding CLI flags (e.g., `--http-proxy`) take precedence. Environment variables can be lowercase (`http_proxy`) or uppercase (`HTTP_PROXY`), but lowercase takes precedence.
```
Yes, tbd
> feat: [sc-121571] respect env vars for http proxy, https proxy, and no proxy

- cmd/installer/cli/adminconsole_resetpassword.go
- cmd/installer/cli/install.go
- cmd/installer/cli/join.go
- cmd/installer/cli/reset.go
- cmd/installer/cli/restore.go
- pkg/preflights/run.go
- pkg/prompts/decorative/decorative.go
- pkg/prompts/plain/plain.go
- pkg/prompts/prompts.go
> Ordinarily, when you type Ctrl-C, the terminal recognizes this as the QUIT button and delivers a SIGINT signal to the process, which terminates it. However, Survey temporarily configures the terminal to deliver control codes as ordinary input bytes. When Survey reads a ^C byte (ASCII \x03, "end of text"), it interrupts the current survey and returns a github.com/AlecAivazis/survey/v2/terminal.InterruptErr from Ask or AskOne. If you want to stop the process, handle the returned error in your code:
https://github.com/AlecAivazis/survey?tab=readme-ov-file#why-isnt-ctrl-c-working
```release-note
```
> fix: handle ctrl+c in prompts

- e2e/install_test.go
- operator/pkg/upgrade/upgrade.go
- operator/pkg/upgrade/upgrade_test.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/testdata/extract-respect-immutable-fields.yaml
- pkg/config/testdata/override-respect-immutable-fields.yaml
- pkg/k0s/install.go
This updates the upgrade code to reapply unsupported k0s overrides on upgrade, and adds a test that ensures worker profiles are properly added when upgrading (via unsupported overrides).
```release-note
```
> fix and test joining nodes with worker profiles after upgrading from previous EC versions

- e2e/helm-charts/nginx-app/Chart.lock
- e2e/kots-release-install-failing-preflights/nginx-app-helm-v1beta2.yaml
- e2e/kots-release-install-legacydr/nginx-app-helm-v1beta2.yaml
- e2e/kots-release-install-stable/nginx-app-helm-v1beta2.yaml
- e2e/kots-release-install-warning-preflights/nginx-app-helm-v1beta2.yaml
- e2e/kots-release-install/nginx-app-helm-v1beta2.yaml
- e2e/kots-release-unsupported-overrides/nginx-app-helm-v1beta2.yaml
- e2e/kots-release-upgrade/nginx-app-helm-v1beta2.yaml
the default replicated sdk image name / location changed to `registry.replicated.com/library/replicated-sdk-image`
```release-note
```
> Fix replicated-sdk chart image name

- cmd/local-artifact-mirror/main.go
- cmd/local-artifact-mirror/pull.go
- cmd/local-artifact-mirror/pull_binaries.go
- cmd/local-artifact-mirror/pull_binaries_test.go
- cmd/local-artifact-mirror/pull_helmcharts.go
- cmd/local-artifact-mirror/pull_images.go
- cmd/local-artifact-mirror/pull_images_test.go
- operator/pkg/artifacts/upgrade.go
In preparation for a better join experience, run the LAM jobs in online mode to update the binaries and artifacts on the host similar to how we do it for airgap.
```release-note
```
> feat(lam): support for pull binaries command in online mode

- pkg/addons/adminconsole/values.go
- tests/dryrun/install_test.go
Mounts the EC data directory into the kots deployment.
[SC-122562](https://app.shortcut.com/replicated/story/122562)
Yes
```release-note
NONE
```
NONE
> Mount the EC data directory into the kots deployment

- dev/dockerfiles/local-artifact-mirror/Dockerfile.ttlsh
- pkg/extensions/upgrade.go
- pkg/extensions/upgrade_test.go
Installs extension on upgrade if Helm release doesn't exist in the cluster.
[SC-122672](https://app.shortcut.com/replicated/story/122672)
Yes
```release-note
* Improves Helm extension upgrade behavior to automatically install extensions if they don't exist during an upgrade operation.
```
NONE
> Install extension on upgrade if doesn't exist

- .github/actions/scan-image/action.yml
- For sarif upload, use the image base name as the category instead of the full name and version
- THis will ensure gtihub can correctly manage the scan results over different image versions
NONE
NONE
```release-note
NONE
```
NONE
> use save_image_name in sarif upload category

- cmd/installer/cli/join.go
- pkg/preflights/run.go
Say "preflights passed" instead of "succeeded" because that's the terminology we usually use for Troubleshoot.
When prompting about HA while joining nodes, default answer is now yes.
NONE
```release-note
When prompted to enable high availability while joining a third or more controller node, the default response is now yes to encourage users to enable high availability.
```
> preflight pass wording and enable HA by default

- cmd/installer/cli/join.go
- cmd/installer/cli/join_runpreflights.go
- dev/dockerfiles/local-artifact-mirror/Dockerfile.ttlsh
- dev/dockerfiles/operator/Dockerfile.local
- dev/dockerfiles/operator/Dockerfile.ttlsh
- pkg/addons/adminconsole/static/metadata.yaml
- pkg/airgap/materialize.go
- pkg/dryrun/kotsadm.go
- pkg/kotsadm/client.go
- pkg/kotsadm/interface.go
- tests/dryrun/Dockerfile
- tests/dryrun/join_test.go
- tests/dryrun/util.go
Gets k0s images from KOTS and deprecates airgap bundle flag for node joins
[SC-122569](https://app.shortcut.com/replicated/story/122569)
[SC-122796](https://app.shortcut.com/replicated/story/122796)
Yes
```release-note
TBD
```
NONE
> Get charts and k0s images from KOTS and deprecate airgap bundle flag for node joins

- .github/actions/e2e/action.yml
- .github/workflows/ci.yaml
- .github/workflows/release-prod.yaml
- e2e/README.md
- e2e/airgap.go
- e2e/cluster/cmx/cluster.go
- e2e/cluster/interface.go
- e2e/install_test.go
- e2e/proxy_test.go
- e2e/restore_test.go
- e2e/shared.go
- e2e/sudo_test.go
Moves these airgap tests to CMX:
- TestMultiNodeAirgapUpgrade
- TestSingleNodeAirgapUpgrade
- TestSingleNodeAirgapUpgradeCustomCIDR
- TestSingleNodeAirgapUpgradeConfigValues
- TestMultiNodeAirgapUpgradeSameK0s
- TestMultiNodeAirgapUpgradePreviousStable
- TestMultiNodeAirgapHAInstallation
- TestFiveNodesAirgapUpgrade
[sc-122461](https://app.shortcut.com/replicated/story/122461)
Yes
```release-note
NONE
```
NONE
> Start moving airgap e2e tests to CMX

- e2e/cluster/lxd/cluster.go
On node reset, the node is rebooted. The LXC container is [exiting](https://github.com/replicatedhq/embedded-cluster/actions/runs/14800575601/job/41586765525?pr=1363#step:4:744) before the reset-installation.sh script exits and is returning a 143 error. This change ignores the error and lets the test proceed.
```release-note
```
> chore(ci): ignore 143 exit code on node reset

- .github/workflows/ci.yaml
Fixes host preflight failures on new actions runners
```
✗  2 host preflights failed
•  Analyzer Failed: analyze: failed to analyze sysctl output: failed to evaluate outcomes: failed to compare net.bridge.bridge-nf-call-iptables == 
0: kernel parameter "net.bridge.bridge-nf-call-iptables" does not exist on collected sysctl output                                              
•  The 'br_netfilter' kernel module is not loaded or loadable 
```
```release-note
```
> fix(ci): enable required kernel modules

- .github/workflows/ci.yaml
- .github/workflows/release-prod.yaml
- e2e/install_test.go
The recent move to CMX for this test exacerbated a bug in rqlite on upgrades which made our CI very flaky. This PR temporarily reverts this test back to LXD until we address the rqlite and/or CMX bug, then we can move back to CMX.
[SC-123136](https://app.shortcut.com/replicated/story/123136)
```release-note
NONE
```
NONE
> Revert TestMultiNodeAirgapHAInstallation back to LXD

- .github/workflows/release-prod.yaml
Replicated CLI is not installed and test fail
https://github.com/replicatedhq/embedded-cluster/actions/runs/14866855117/job/41746405167
```release-note
```
> chore(ci): fix release pipeline cmx tests

- scripts/ci-build-deps.sh
- scripts/common.sh
Speeds up builds by building the operator and LAM images in parallel.
```release-note
NONE
```
NONE
> Build LAM and operator in parallel

- e2e/cluster/cmx/cluster.go
The CMX VM gets marked as ready right after cloud-init scripts but it can take time after that for the services to start. This adds a wait until an actual fix is implemented in CMX.
```release-note
NONE
```
NONE
> Wait for a bit after creating VM and before getting SSH endpoint

- cmd/installer/cli/install_runpreflights.go
hide `install run-preflights` because it's not fully productized or documented yet.
```release-note
```
> hide install run-preflights command

- .github/workflows/release-prod.yaml
Automate the creation of release notes
Example PR on the docs repo: https://github.com/replicatedhq/replicated-docs/pull/3246
```release-note
```
> Automate EC Release Notes

- e2e/cluster/cmx/cluster.go
With the change to `exec.Command(...).Output()` we stopped combining the `stderr` into the resulting output. That will be added to a field `Stderr` for the `ExitError` instead. This PR addresses that. Example output of an error now:
```
cluster.go:82: failed to create nodes: create node 0: create node node0: exit status 1: stderr: Error: create vm: POST https://api.staging.replicated.com/vendor/v3/vm 500:
: stdout:
```
Open to changing the format if y'all prefer something else.
NA
NONE
```release-note
NONE
```
NONE
> chore(e2e): make sure we log stderr output from the API

- cmd/installer/cli/ca.go
- cmd/installer/cli/install.go
- cmd/installer/cli/restore.go
- pkg/addons/install.go
This is a precursor to deprecating the --private-ca flag and instead using the CA bundle from the host to inject into containers to support private CAs.
There is no functional change here and the product should continue to work as is.
```release-note
```
> feat: detect host ca bundle

- cmd/installer/goods/support/host-support-bundle.tmpl.yaml
Ensure Microsoft Defender Antivirus security tool is detected by the support bundle analysis.
NONE
```release-note
Ensure Microsoft Defender Antivirus security tool is detected by the support bundle analysis.
```
NONE
> chore: add Microsoft Defender Antivirus to the list of security tools

- operator/charts/embedded-cluster-operator/templates/embedded-cluster-operator-deployment.yaml
- pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go
- pkg/addons/embeddedclusteroperator/install.go
- pkg/addons/embeddedclusteroperator/install_test.go
- pkg/addons/embeddedclusteroperator/integration/hostcabundle_test.go
- pkg/addons/embeddedclusteroperator/upgrade.go
- pkg/addons/embeddedclusteroperator/values.go
- pkg/addons/embeddedclusteroperator/values_test.go
- pkg/addons/install.go
- pkg/addons/upgrade.go
- tests/dryrun/install_test.go
Pass the ca bundle detected from the host to the operator chart.
Mounts the CA into the operator container at path /certs/ca-certificates.crt and sets the SSL_CERT_DIR env var so that golang will use the certificate.
Adds extraVolumes and extraVolumeMounts keys to the helm values file to pass through to the operator deployment similar to the [velero helm chart](https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/templates/node-agent-daemonset.yaml#L86-L89).
Related https://github.com/replicatedhq/embedded-cluster/pull/2168
```release-note
```
> feat(operator): improved private ca support from host

- api/types/errors.go
- api/types/errors_test.go
Story: https://app.shortcut.com/replicated/story/124146/add-tests-to-api-error-types
Adds tests to `api/types/errors_test.go` and changes the Unauthorized API error to not expose the underlying `err.Error()` through `Message`.
```release-note
```
> chore(api-error): change unauthorized msg and add tests

- operator/charts/embedded-cluster-operator/values.yaml
- operator/charts/embedded-cluster-operator/values.yaml.tmpl
- operator/pkg/artifacts/upgrade.go
- operator/pkg/artifacts/upgrade_test.go
This PR adds host CA bundle support to upgrade artifacts jobs, bringing them in line with the recent changes made to other components
**Changes:**
- **Removes hardcoded ConfigMap approach**: Eliminates the hardcoded "private-cas" volume, mount, and SSL_CERT_DIR environment variable from the `copyArtifactsJob` template
- **Adds conditional host CA bundle support**: When `Installation.Spec.RuntimeConfig.HostCABundlePath` is configured, artifacts jobs now dynamically add:
- Host CA bundle volume (HostPath pointing to the configured path)
- Volume mount at `/certs/ca-certificates.crt` 
- `SSL_CERT_DIR=/certs` environment variable
- **Cleans up deprecated chart configuration**: Removes the `privateCAs` section from Helm chart values
**Why we need it:**
This aligns the artifacts upgrade …
> feat(operator): Mount CA into Upgrade Artifacts Job Container

- cmd/installer/cli/install.go
- cmd/installer/cli/install_runpreflights.go
- cmd/installer/cli/install_test.go
Installation fails if `--http-proxy` is set and `--https-proxy` is not set.
This PR adds the following confirmation prompt before proceeding with the installation:
```
"Typically --https-proxy should be set if --http-proxy is set. Installation failures are likely otherwise. Do you want to continue anyway?"
```
https://app.shortcut.com/replicated/story/121629/prompt-if-http-proxy-is-set-but-not-https-proxy
Unit tests have been added to verify:
- no proxy set
- `http_proxy` set without `https_proxy` and user **confirms** (inputs y) proceeding with installation
- `http_proxy` set without `https_proxy` and user **declines** (inputs n) proceeding with installation
- `http_proxy` set without `https_proxy` and `assumeYes` is true
- both proxy set
```release-note
Added confirmation prompt to …
```
> feat: add prompt to proceed if http proxy is set and https proxy unset

- e2e/cluster/cmx/cluster.go
Based on the following thread:
- https://replicated.slack.com/archives/C04T9AAMJUS/p1747707927071029
Seems like a lot of the E2E test flakiness and errors we've been getting with CMX can be addressed if instead of manually creating the network and each node in parallel we leverage the VM API and create all the required VMs in one go (which will be under the same network by default).
NA
NONE
```release-note
NONE
```
NONE
> chore(e2e): create multiple VMs in one go through the CLI

- cmd/installer/cli/install.go
Currently, when users run the install command with missing required flags (like --license), they may be prompted for optional values (like creating an admin console password if one was not provided through the --admin-console-password flag) before seeing validation errors. This creates a frustrating experience where users complete prompts unnecessarily.
This PR moves the`preRunInstall` call from cobra's `PreRunE` to `RunE` to get the following order of execution and give precedence to required flag errors
**Current Behavior**
PreRunE
preRunInstall (prompts happen here)
Cobra's flag validation
RunE
**New Behavior**
~~PreRunE~~ (removed, preRunInstall was the only thing in it)
Cobra's flag validation
RunE
preRunInstall (prompts happen here) …
> Fix prompts showing before required flag errors

- .gitignore
- operator/Makefile
Some local dev quality of life improvements:
- Adding some files created during tests to `.gitignore`
- Fixing `LD_FLAGS` usage in the operator Makefile
NONE
```release-note
NONE
```
NONE
> chore(local-dev): gitgnore and operator makefile improvements

- cmd/installer/goods/support/host-support-bundle.tmpl.yaml
**Enhancements to security tool detection:**
* Added a new collector `security-tools-packages` to detect specific security-related system packages for both Ubuntu and RHEL distributions.
* Extended the regex pattern in the `ps-detect-antivirus-and-security-tools` check to include `mdatp` for detecting additional security tools.
**Checks for installed security packages:**
* Introduced a new check `Detected Security Packages` to evaluate whether specific security packages are installed. Includes fail/pass outcomes with messages indicating potential interference with Kubernetes operation and recommending appropriate actions.
https://app.shortcut.com/replicated/story/124367/additional-security-tools-check-in-support-bundle-analysis
NONE
```release-note
Add additional security tools check in …
```
> chore: add additional security tools check in support bundle

- web/static.go
- web/static_test.go
Follow up to - https://github.com/replicatedhq/embedded-cluster/pull/2229. I was tricked by the cwd of `go test` which is the root of the package where the tests are running. This fix addresses it so that our tests still assert on the right thing and local dev works as expected.
Also run this locally using `EC_DEV_ENV=true` and without it.
NONE
```release-note
NONE
```
NONE
> chore(web): fix local web dev

- e2e/playwright/tests/deploy-upgrade/test.spec.ts
Increases preflight checks timeout on upgrade to 30 seconds
```release-note
NONE
```
NONE
> Increase preflight checks timeout on upgrade

- e2e/install_test.go
- e2e/scripts/check-airgap-installation-state.sh
- e2e/scripts/check-airgap-post-ha-state.sh
- e2e/scripts/check-installation-state.sh
- e2e/scripts/check-post-ha-state.sh
- e2e/scripts/check-postupgrade-state.sh
- e2e/scripts/common.sh
- pkg/addons/adminconsole/static/values.tpl.yaml
- pkg/addons/adminconsole/values.go
- tests/dryrun/install_test.go
Set `SSL_CERT_CONFIGMAP` so KOTS knows what configmap to use for the Replicated SDK. See here - https://github.com/replicatedhq/kots-helm/blob/main/templates/kotsadm-deployment.yaml#L108-L113. Without this, the SDK  doesn't work in proxied environments.
Also in this PR is an adjustment to our function which validates if there are unhealthy pods. Right now it doesn't account for pods which are stuck in `0/1 Running` like the SDK is currently in proxied environments
```release-note
```
> Set SSL Cert ConfigMap in KOTS and Improve Detection of Unhealthy Pods in Tests

- operator/pkg/artifacts/upgrade.go
Fixes an issue where k0s tries to pull images from LAM before it restarts on EC binary update which causes the upgrade to fail.
```release-note
* Fixes an issue where upgrades could fail due to a race condition leading to errors that look like this: `msg=\"Waiting for container images to be uploaded...\"\nError: failed to upgrade: distribute artifacts: autopilot copy airgap artifacts: wait for autopilot plan: autopilot plan failed: Upgrade apply has failed\n"`
```
NONE
> Fix upgrade flakiness upon LAM restart

- pkg/addons/registry/migrate/pod.go
- pkg/dryrun/kubeutils.go
- pkg/kubeutils/interface.go
- pkg/kubeutils/kubeutils.go
- pkg/kubeutils/kubeutils_test.go
https://github.com/replicatedhq/embedded-cluster/actions/runs/15541299543/job/43752497184?pr=2226
```
ha_test.go:275: 2025-06-09 18:15:45 [spinner] ○  Migrating data for high availability
ha_test.go:209: 
Error Trace:	/home/runner/work/embedded-cluster/embedded-cluster/tests/integration/kind/registry/ha_test.go:209
/home/runner/work/embedded-cluster/embedded-cluster/tests/integration/kind/registry/ha_test.go:134
Error:      	Target error should be in err chain:
expected: "context canceled"
in chain: "migrate registry data: run registry data migration: ensure pod: create pod: object is being deleted: pods \"registry-data-migration\" already exists"
"migrate registry data: run registry data migration: ensure pod: create pod: object is being deleted: pods \"registry-data-migration\" already …
```
> chore(ci): fix flakey test TestRegistry_EnableHAAirgap

- cmd/installer/cli/api.go
- cmd/installer/cli/install.go
- web/src/components/wizard/InstallationStep.tsx
Shows the installation error in the UI on failure.
https://github.com/user-attachments/assets/61519bf3-e9c2-4c8e-ad84-32be9560ce77
```release-note
```
> feat(ui): show install errors in the ui

- cmd/installer/cli/install.go
- cmd/installer/cli/install_runpreflights.go
User sees the prompt about a new available version after the prompt to go to the UI. 
This PR fixes that behavior and reorganizes similar prompts and checks to enhance the user experience.
New priority Order
1. Cobra's required flag validation (e.g. missing --license)
2. Prompts and checks on installation state, license file, airgap bundles, and releases
- Existing k0s installation (reinstall detected)
- Airgap bundle downloaded but not provided via CLI
- License/release version mismatch
- Airgap bundle/release version mismatch
- Outdated release version available
3. Proxy configuration prompt (HTTP proxy set without HTTPS)
4. Admin console password prompt
5. Display URL to the Manager Experience UI
https://app.shortcut.com/replicated/story/124485/user-sees-the-prompt-about-a-new-available …
> Fix "new version available" prompt appearing after manager experience URL

- web/src/components/wizard/InstallationStep.tsx
Changes the color of the Check Circle to match the blue of other elements
Removes the Last Updated timestamp
https://app.shortcut.com/replicated/story/124799/checkmark-when-install-is-done-is-blue-but-not-the-right-blue
https://app.shortcut.com/replicated/story/124720/last-updated-date-in-installation-progress-page-shows-2-31-1-5-00-04-pm-timestamp
NONE
```release-note
NONE
```
NONE
> bug: Remove lastUpdated timestamp and change CheckCircle icon color

- cmd/installer/cli/signal_test.go
See - https://github.com/replicatedhq/embedded-cluster/actions/runs/15614228889/job/43982767244?pr=2292#step:4:988 - we need to wait for the os exit function to have been called before making assertions on the state.
NA
It's a test fix
```release-note
NONE
```
NONE
>  chore(test): actually wait for the os exit signal function to be called before asserting

- web/src/components/wizard/SetupStep.tsx
You can't go back to the Welcome step because it just proceeds you to the Setup step if you're already logged in. So the button didn't do anything.
> Remove Back button from Setup page

- pkg/addons/openebs/static/values.tpl.yaml
New loki components should be disabled and is causing automation to fail to update openebs.
https://github.com/replicatedhq/embedded-cluster/actions/runs/15616993264/job/43992314591
```
failed to update openebs images: failed to update images: no component found for image docker.io/grafana/alloy:v1.8.1
```
```release-note
```
> fix(openebs): disable loki components

- api/client/install.go
- api/controllers/install/controller.go
- api/controllers/install/controller_test.go
- api/controllers/install/hostpreflight.go
- api/controllers/install/infra.go
- api/controllers/install/installation.go
- api/integration/hostpreflights_test.go
- api/integration/install_test.go
- api/internal/managers/infra/install.go
- api/internal/managers/infra/manager.go
- api/internal/managers/infra/manager_mock.go
- api/internal/managers/infra/util.go
- api/internal/managers/installation/config.go
- api/internal/managers/installation/config_test.go
- api/internal/managers/installation/manager.go
- api/internal/managers/installation/manager_mock.go
- api/internal/managers/preflight/hostpreflight.go
- api/internal/managers/preflight/hostpreflight_test.go
- api/internal/managers/preflight/manager.go
- api/internal/managers/preflight/manager_mock.go
- cmd/installer/cli/install.go
- pkg-new/k0s/k0s.go
- pkg/dryrun/k0s.go
We should no longer need to use the config. Everything is embedded in the runtime config. Pass the runtime config as an argument.
```release-note
```
> chore: runtime config as argument

- pkg-new/preflights/host-preflight.yaml
Some systems use an XFS filesystem that is configured with `ftype=0`, which is a requirement for `OverlayFS`. This causes problems for container runtimes like containerd, and can lead to failures during or after installation.
The failure and success (never shown) messages will be
```
FAIL: The XFS filesystem on /var/lib/embedded-cluster path is configured with ftype=0 which containers
cannot run on. Please reconfigure the filesystem or use a different data directory.
PASS: File system on /var/lib/embedded-cluster path is fit for use with containers
```
[sc-124752](https://app.shortcut.com/replicated/story/124752/add-preflight-check-for-xfs-with-ftype-0-to-prevent-container-runtime-issues)
NONE
```release-note
Add preflight to check for XFS filesystem with ftype=0
```
NONE
> feat: add preflight to check for XFS filesystem with ftype=0

- e2e/cluster/cmx/cluster.go
Using a bash script which creates VM's waits for a running status and then SSH's into them and runs uptime I was able to reproduce the banner exchange timeout issue that is faced when running e2e tests:
```
./scripts/vm-create-ssh.sh
=== Iteration 1 ===
Creating 3 VMs...
ID          NAME                           DISTRIBUTION    VERSION       STATUS        NETWORK      CREATED                           EXPIRES                           COST
c4c5a40d    eloquent_lumiere               ubuntu          24.04         running       8cb35c5f     2025-06-20 14:58 PDT              2025-06-20 15:59 PDT              $0.60
0a8cc730    eloquent_lumiere               ubuntu          24.04         running       8cb35c5f     2025-06-20 14:58 PDT              2025-06-20 15:59 PDT              $0.60 …
```
> fix(e2e): Set sshArgs to mostly defaults

- api/controllers/install/controller_test.go
- api/internal/statemachine/statemachine.go
- api/internal/statemachine/statemachine_test.go
Complement to #2356, adds tests to the failure scenarios fixed in it by checking if the state machine is locked or not after the controller methods are executed.
Unit tests will fail as expected until the changes in #2356 are introduced.
Follow up to #2356 and #2334 
These are tests
```release-note
NONE
```
NONE
> chore: validate state machine lock in tests

- Makefile
- cmd/installer/cli/api.go
- cmd/installer/cli/install.go
- web/src/components/wizard/setup/LinuxSetup.tsx
- web/src/components/wizard/tests/SetupStep.test.tsx
- web/src/contexts/ConfigContext.tsx
- web/src/contexts/WizardModeContext.tsx
- web/src/global.d.ts
- web/src/test/setup.tsx
- web/src/test/testData.ts
- web/static.go
Adds a flag target which as of now only controls the text on the welcome screen in the browser UI.
```release-note
```
> chore(web): text on welcome string reflects install target

- api/internal/statemachine/event_handler.go
- api/internal/statemachine/interface.go
- api/internal/statemachine/statemachine.go
- api/internal/statemachine/statemachine_test.go
This PR relates to https://github.com/replicatedhq/embedded-cluster/pull/2337. Where, in order to support our reporting strategy we introduce event handlers that are triggered when successful transitions happen on the state machine. This has the added benefits of:
- All the reporting logic can be aggregated under the same code area
- No potential for drift between reported state VS actual state
- Managers become entirely independent/unaware of the metrics reporting mechanism
- Potential to easily extend the events we report in future.
- Potential to extend with other reporting mechanisms in the future.
https://app.shortcut.com/replicated/story/125431/spike-evaluate-setting-up-reporting-handlers-as-part-of-state-machine-transitions-in-new-manager-api
Yes, added
```release-note
NONE
``` …
> chore: add statemachine event handlers

- cmd/installer/cli/cidr.go
- cmd/installer/cli/cidr_test.go
- cmd/installer/cli/flags.go
- cmd/installer/cli/install.go
- cmd/installer/cli/install_runpreflights.go
- cmd/installer/cli/proxy.go
- cmd/installer/cli/proxy_test.go
- cmd/installer/cli/restore.go
Adds `--kubeconfig` flag for `--target kubernetes`
Adds additional flags for configuring the kubernetes client borrowed from helm.
Uses helm EnvSettings to construct a kubernetes client from the flags or the environment.
```release-note
```
> feat(kubernetes): support for kubeconfig flag and from env

- api/api.go
- api/controllers/linux/install/hostpreflight.go
- api/handlers.go
- api/routes.go
The documented interface is awkward without exposing the type
https://pkg.go.dev/github.com/replicatedhq/embedded-cluster@v1.29.5-0.20250624191231-4e416be8b36e/api
```release-note
```
> chore(api): export and document for more clear interface

- api/controllers/linux/install/controller.go
- api/controllers/linux/install/controller_test.go
- api/controllers/linux/install/hostpreflight.go
- api/controllers/linux/install/infra.go
- api/controllers/linux/install/installation.go
- api/controllers/linux/install/reporting_handlers.go
- api/controllers/linux/install/statemachine.go
- api/controllers/linux/install/statemachine_test.go
- api/integration/install_test.go
- api/internal/managers/preflight/hostpreflight.go
- api/internal/managers/preflight/hostpreflight_test.go
- api/internal/managers/preflight/manager.go
- api/internal/store/store_mock.go
- cmd/installer/cli/install.go
- pkg/metrics/reporter_mock.go
This ended up tackling a bit more than intended as we started digging through the state transitions and we spotted that:
- The lack of some states complicated our overall flow and reporting
- Some transitions were not happening or just wrong (e.g. we were conflating the PreflightsFailed state).
The bulk of this PR is around adding new states and fixing the ones that we have as well the transition mechanisms. This mermaid diagram illustrates the final graph:
```mermaid
graph TD
%% Initial & config states
StateNew -->|Success| StateInstallationConfigured
StateNew -->|Fail| StateInstallationConfigurationFailed
StateInstallationConfigurationFailed -->|Retry| StateInstallationConfigured
StateInstallationConfigurationFailed -->|Retry| StateInstallationConfigurationFailed …
```
> feat(reporting): add metrics reporting to the new manager experience

- cmd/installer/main.go
Fixes bug where app slug is not being used for the cli help menu
https://app.shortcut.com/replicated/story/125645/use-app-slug-in-the-cli-help-menu-not-the-binary-name
NONE
```release-note
NONE
```
NONE
> bug: Use app slug in cli help menu

- api/controllers/linux/install/controller_test.go
We cannot assert the intermediate state because it may finish before it context switches back to the current thread.
```release-note
```
> chore(ci): fix unit test race condition

- cmd/installer/cli/install.go
- cmd/installer/cli/install_test.go
TL;DR
-----
Supports the `SKIP_HOST_PREFLIGHTS` environment variable to skip the preflight checks. This is not documented and not for general use.
Details
-------
Offers a "hidden" way to skip preflight checks by setting the environment variable `SKIP_HOST_PREFLIGHTS`. I'm adding the flag to support our Instruqt labs, since the Instruqt environment require a wildcard DNS entry that causes the host preflights to fail.
I decided on this approach to avoid teaching any bad habits by telling the user to use `--ignore-host-preflights` when teaching them about the Embedded Cluster. I wanted instead to avoid the checks on their behalf without them realized it. This variable is not deliberately not documented to avoid similar encouragement of bad habits.
> Adds a secret skip preflight environment variable

- api/README.md
Documents Architecture Decision: Kubernetes as a Subset of Linux
[SC-125322](https://app.shortcut.com/replicated/story/125322)
NONE
```release-note
NONE
```
NONE
> Document Architecture Decision: Kubernetes as a Subset of Linux

- cmd/installer/cli/flags.go
- cmd/installer/cli/install.go
- cmd/installer/cli/update.go
- e2e/scripts/install-and-configure-squid.sh
The `ENABLE_V3` environment variable is more flexible because we're able to change the format of the help menu and things like that. Whereas the `--manager-experience` flag can only change the behavior of the install. Now that we have the environment variable, the flag is duplicative, and we can just use the environment variable to control how the install functions. 
Make `--target` flag required with no default if `ENABLE_V3 == 1`
```release-note
```
> feat: use ENABLE_V3 env var instead of flag

- cmd/installer/cli/install.go
- cmd/installer/cli/install_runpreflights.go
- cmd/installer/cli/restore.go
https://app.shortcut.com/replicated/story/125973/the-installer-prompts-that-you-did-not-provide-an-airgap-bundle-when-you-did
https://app.shortcut.com/replicated/story/125975/prompt-to-update-to-current-app-release-does-not-not-work-when-a-proxy-is-provided-with-flags
```release-note
```
> fix: parse flags before prompting, do not prompt in flag parsing code

- .github/dependabot.yml
```
Errored with the message "Dependabot can't resolve your Go dependency files"
```
```release-note
```
> chore: dependabot does not work with dagger

- web/src/components/wizard/completion/KubernetesCompletionStep.tsx
- web/src/components/wizard/completion/LinuxCompletionStep.tsx
- web/src/components/wizard/tests/KubernetesCompletionStep.test.tsx
- web/src/contexts/KubernetesConfigContext.tsx
- web/src/test/setup.tsx
Adds the installation command (for Kubernetes target) in the UI Completion step, allowing users to access the KOTS admin console
https://app.shortcut.com/replicated/story/126071/install-kots-into-a-cluster-with-a-provided-kubeconfig-make-visit-the-admin-console-link-work
Tests were updated to account for the copy box of the installation command
```release-note
None
```
None
> feat: Add adm install command to k8s target UI

- web/src/components/common/Input.tsx
- web/src/components/wizard/config/ConfigurationStep.tsx
- web/src/components/wizard/tests/ConfigurationStep.test.tsx
Adds support for the radio config item type
[SC-126346](https://app.shortcut.com/replicated/story/126346)
Yes
```release-note
NONE
```
NONE
> Support the radio config item type

- api/controllers/kubernetes/install/app.go
- api/controllers/kubernetes/install/controller_mock.go
- api/controllers/linux/install/app.go
- api/controllers/linux/install/controller_mock.go
- api/internal/managers/app/config/config.go
- api/internal/managers/app/config/config_test.go
- api/internal/managers/app/config/manager.go
- api/internal/managers/app/config/manager_mock.go
Only returns items with when != "false" to the ui.
Filters values for items with when == "false"
```release-note
```
> feat(api): handle config item "when" attribute

- web/src/contexts/AuthContext.tsx
Fixes an incorrect request for the linux installation config in kubernetes target installations. 
There is `/console/available-network-interfaces` if we wanted to use that instead.
```release-note
```
> fix(ui): use installation target from initial state in authcontext

- web/src/components/wizard/installation/shared/LogViewer.test.tsx
- web/src/components/wizard/installation/shared/LogViewer.tsx
It was impossible to scroll back through installation logs during an install, because every time a new log line was added, it would scroll you back to the bottom.
With this change, we only auto-scroll if you're already at the bottom.
NONE
```release-note
```
NONE
> only auto scroll if at bottom of logs

- .github/workflows/ci.yaml
E2E tests do not yet test the new V3 manager experience yet we run them on all changes. This change skips E2E tests when there are only changes to the ./api directory.
```release-note
```
> chore(ci): conditionally run e2e tests

- api/integration/kubernetes/install/app_test.go
- api/integration/linux/install/app_test.go
- api/internal/managers/app/config/config.go
- api/internal/managers/app/config/config_test.go
This PR adds actual support for the config item file type, validating the its value and setting the correct `Filename` property based on pre-existing values or the parent item filename.
Closes https://app.shortcut.com/replicated/story/126680/add-file-config-item-type-backend-foundation
Yes
```release-note
NONE
```
NONE
> feat(app): add support for the file type item

- cmd/installer/cli/install.go
If you specify a relative path to the embedded cluster installer's `--data-dir` flag, the install will fail when starting the LAM service. we should resolve the path given to us to an absolute path to avoid ever dealing with relative paths. 
```release-note
Fixed an issue where specifying a relative path to the installer's --data-dir flag would cause the installation to fail when starting the LAM service. Paths provided to --data-dir are now resolved to absolute paths, avoiding problems related to relative directory references.
```
> try to resolve relative data dir paths

- web/src/components/common/HelpText.tsx
- web/src/components/common/Label.tsx
- web/src/components/common/tests/HelpText.test.tsx
Fixes rendering of markdown new paragraphs and line breaks for Label and Help Text components
https://app.shortcut.com/replicated/story/126828/fix-markdown-handling-of-new-paragraphs-and-line-breaks
Tests were updated
```release-note
NONE
```
NONE
Screenshots post changes:
> bug: Fix markdown paragraph and line breaks

- api/pkg/template/engine.go
- api/pkg/template/engine_test.go
This PR implements a dependency tree tracking system in the template engine to optimize performance by avoiding unnecessary reprocessing of config items. Previously, all config items were recomputed on every template execution. Now, the engine tracks dependencies between config items and only invalidates cached values when the item itself or any of its dependencies have changed.
The optimization works by:
- Building a dependency tree during template resolution to track which config items depend on others
- Caching resolved values with a "processed" flag to track execution state
- Using cache invalidation logic that recursively checks if an item or any of its dependencies have changed
- Only recomputing values when necessary, significantly improving performance for large config template …
> Support repl templates - Optimize template performance

- api/pkg/template/engine.go
- api/pkg/template/engine_test.go
Adds support for ConfigOptionFilename and ConfigOptionNotEquals template functions
```release-note
```
> feat(api): config template function support

- api/pkg/template/engine.go
- api/pkg/template/static.go
- api/pkg/template/static_test.go
- go.mod
Support for 
| Now |
| NowFmt |
| ToLower |
| ToUpper |
| TrimSpace |
| Trim |
| UrlEncode |
| Base64Encode |
| Base64Decode |
| Split |
| RandomBytes |
| RandomString |
| Add |
| Sub |
| Mult |
| Div |
| ParseBool |
| ParseFloat |
| ParseInt |
| ParseUint |
| HumanSize |
| YamlEscape |
```release-note
```
> feat(api): static template function support

- web/src/components/wizard/WelcomeStep.tsx
- web/src/components/wizard/tests/WelcomeStep.test.tsx
- Changed the password error copy to match the mockup
- Show error for empty password
- Distinguish between 401 and other errors
- Do not retry incorrect password attempts
- Tests
Loom:
- https://www.loom.com/share/dce97fa3d78a42abb0ef66268c29aeec?sid=7081667d-e745-4c58-81ce-b2697850abbb
https://app.shortcut.com/replicated/story/126447/highlight-missing-password-on-welcome-page
Yes
```release-note
NONE
```
NONE
> fix(ui): show error message for empty password in UI

- .github/workflows/image-scan.yaml
Right now, our CI builds on main are all red, but we release in spite of that because there errors are "expected" and should go away when we utilize fully SecureBuild images.
Having a red pipeline all the time makes it hard to determine if it's okay to release or not, and messes up with other reporting metrics around our CI.
This PR temporarily makes it so that our CI doesn't fail for image scans.
NONE
```release-note
NONE
```
NONE
> Do not fail image scan workflows until we fully utilize SecureBuild images

- e2e/cluster/cmx/cluster.go
This handles an expected error from the CMX node rebooting as part of the EC reset process.  In CI exit code 143 sometimes occurs, for example: Reference: https://github.com/replicatedhq/embedded-cluster/actions/runs/15742928677/job/44373346807?pr=2340#step:8:139
Exit status 143 indicates SIGTERM, looking at `reset-installation.sh` the EC reset command is ran which calls [reboot](https://github.com/replicatedhq/embedded-cluster/blob/3fac95992bbebc33e4e2e482ca07c054cfa37a84/cmd/installer/cli/reset.go#L212) and then the ssh connection that's running the command is terminated early before response.  I think it's a chance you'll get 255 which is just a connection closed error which is already being handled OR you'll get SIGTERM like in this case, I think handling both is the right call.  This …
> chore(ci): Handle exit code 143 during reset within CMX

- api/internal/managers/linux/infra/install.go
- cmd/installer/kotscli/kotscli.go
Skips running KOTS app preflights when the manager experience installer is enabled 
https://app.shortcut.com/replicated/story/127247/pass-the-skip-preflights-flag-to-kots-install
NONE
```release-note
NONE
```
NONE
> feat: skip KOTS app preflights when manager experience installer is enabled

- e2e/kots-release-install-v3/config.yaml
Fix duplication of Label type config items when switching between groups in the configuration step UI caused by Label config items sharing the same name.
https://app.shortcut.com/replicated/story/127414/label-config-items-duplicate-when-switching-tabs
NONE
```release-note
NONE
```
NONE
> bug: Fix label config item duplication

- cmd/installer/cli/restore.go
- go.mod
- go.sum
Sanitize is failing because the v1 sdk is no longer supported
https://github.com/replicatedhq/embedded-cluster/actions/runs/16730864281/job/47358362701?pr=2620
```release-note
```
> chore(deps): migrate to go aws sdk v2

- .github/workflows/archive-instances.yaml
- .github/workflows/cleanup-resources.yaml
- scripts/archive-instances.sh
- scripts/demote-channel-releases.sh
The replicated-sdk is timing out when starting due to api load. this is likely because of all the channel releases and instances in the e2e test account. This change adds a scheduled job that runs every 12 hours and cleans up resources in the api.
```release-note
```
> chore(ci): clean up account, archive old channel releases and instances

- web/src/components/wizard/tests/LinuxValidationStep.test.tsx
web unit tests are failing
```
FAIL  src/components/wizard/tests/LinuxValidationStep.test.tsx > LinuxValidationStep > enables Start Installation button when allowIgnoreHostPreflights is true and preflights fail
TestingLibraryElementError: Unable to find an element with the text: Host Requirements Not Met. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.
```
```
<div
class="ml-3"
>
<h4
class="text-sm font-medium text-gray-900"
>
Unable to complete system requirement checks
</h4>
<p
class="mt-1 text-sm text-red-600"
>
fetch failed
</p>
</div>
```
from cursor:
The Problem
The test was failing because it was looking for the text "Host Requirements Not Met" but the component was …
> chore(ci): fix web unit test

- cmd/installer/cli/join.go
- pkg-new/config/network_interface.go
- pkg-new/config/network_interface_test.go
- pkg/dryrun/dryrun.go
- pkg/dryrun/network_interface.go
- pkg/netutils/ips.go
- pkg/netutils/ips_test.go
- tests/dryrun/join_test.go
Fix for support issue - https://github.com/replicated-collab/cisco-replicated/issues/13
Had to make a couple of changes to the net* packages to be able to mock some behaviours to accurately test this using `dryrun`.
https://app.shortcut.com/replicated/story/127689/join-subcommand-doesn-t-rely-on-network-interface-flag
Yes
```release-note
Fix for `join` sub-command where the host interface name wasn't being used when joining a new node
```
NONE
> fix(join): use local network interface and provided flag

- api/controllers/app/install/controller.go
- api/controllers/linux/install/controller_test.go
- api/integration/app/install/config_test.go
- api/internal/managers/linux/infra/install_test.go
Config rendering fails with the following error when using the `LicenseDockerCfg` template function.
```
time="2025-08-12T13:45:19-07:00" level=error msg="failed to template app config" error="execute config template: template execution error: template config items: template value for license_docker_cfg: execute template: template: template:1:7: executing \"template\" at <LicenseDockerCfg>: error calling LicenseDockerCfg: license is nil" method=POST path=/linux/install/app/config/template
```
```release-note
```
> fix(api): fix LicenseDockerCfg template function

- e2e/kots-release-upgrade/cluster-config.yaml
- e2e/scripts/check-postupgrade-state.sh
- e2e/scripts/common.sh
- hack/test-installation.yaml
Moves off of bitnami hosted chart to free one for test.
```release-note
```
> chore(ci): move away from bitnami charts

- .github/workflows/ci.yaml
- e2e/cluster/cmx/cluster.go
- e2e/install_test.go
Adds a test that uses CMX network reports to verify that all requests go to expected destinations during an app install.
The first iteration of this just prints out the IPs reached and any domains used in the connection if available. Follow ups will assert that the connections made are limited to the expected destinations for the EC install process.
https://app.shortcut.com/replicated/story/127479/setup-testing-for-network-reporting-in-ec
NONE
```release-note
NONE
```
NONE
> tests: add test that reports network events while deploying an EC app

- api/controllers/app/install/controller.go
- api/controllers/kubernetes/install/controller.go
- api/controllers/linux/install/controller.go
- api/integration/kubernetes/install/appinstall_test.go
- api/integration/linux/install/appinstall_test.go
- api/internal/managers/app/install/install.go
- api/internal/managers/app/install/install_test.go
- api/internal/managers/app/install/manager.go
- api/internal/managers/app/install/status.go
- api/internal/managers/app/install/util.go
- api/internal/managers/app/release/template.go
- api/internal/managers/app/release/util.go
- proposals/helm_direct_install.md
- proposals/helm_direct_install_research.md
- proposals/v3_app_deployment_transition.md
Installs Helm charts directly without relying on the KOTS CLI
[SC-128045](https://app.shortcut.com/replicated/story/128045)
Yes
```release-note
NONE
```
NONE
> feat(v3): install Helm charts directly without KOTS CLI

- .gitignore
- Makefile
- local-artifact-mirror/Makefile
- operator/Makefile
- scripts/ci-build-deps.sh
- scripts/ci-upload-binaries.sh
i was having issues with ttl.sh. this allows for the following:
```
export OPERATOR_IMAGE_NAME=docker.io/emosbaugh/operator
export LOCAL_ARTIFACT_MIRROR_IMAGE_NAME=docker.io/emosbaugh/lam                    
make initial-release
```
```release-note
```
> chore(ci): allow for specifying alternative image repo for dev env

- cmd/installer/cli/install.go
- cmd/installer/cli/install_test.go
- tests/dryrun/install_test.go
Add a new `--ignore-app-preflights` flag to ignore app preflights with failures and warning for V2 EC installations
Changes the wording of the success message for headless installations
https://app.shortcut.com/replicated/story/127100/add-support-for-skipping-app-preflights-on-warning-failure
https://app.shortcut.com/replicated/story/128033/change-visit-the-admin-console-wording-if-a-headless-install-is-done
Tests for the new ignore-app-preflights flag were added
```release-note
NONE
```
NONE
> Add flag to ignore app preflights for V2 installs and update success message

- api/internal/managers/app/install/install.go
- api/internal/managers/app/install/install_test.go
Call the kots install cli command before we install the app's helm charts to process the app airgap bundle and create the image pull secrets.
Tested end to end:
Using the test app the charts were deployed. The regular yaml files were not.
EC does not inject global replicated values so replicated-sdk is crashing.
```
root@node0:/replicatedhq/embedded-cluster# kubectl logs -n nginx-app          replicated-7fc8f67688-ndf42
Error: either license in the config file or integration license id must be specified
```
```release-note
```
> feat(v3): rely on kots to process the app airgap bundle and create the image pull secrets

- web/src/components/common/HelpText.tsx
- web/src/components/common/Label.tsx
- web/src/components/common/Markdown.tsx
Fix rendering issues with the code blocks in markdown.
Printscreen fix:
Before:
https://app.shortcut.com/replicated/story/126837/markdown-code-blocks-have-the-wrong-background-color
It's a visual change only unfortunately, hard to test IMO and doing so through CSS classes can be messy.
```release-note
Fix markdown rendering issues for code blocks for V3
```
NONE
> fix(web): code block rendering in markdown

- api/pkg/template/config.go
- api/pkg/template/config_test.go
- api/pkg/template/execute_test.go
- e2e/kots-release-install-v3/config.yaml
- web/src/components/wizard/config/ConfigurationStep.tsx
- web/src/components/wizard/tests/ConfigurationStep.test.tsx
- web/src/types/index.ts
- web/static.go
Displays the correct filename when navigating back and forth through the installer
Fixes an issue where the user cannot clear the value (or file) if a value is set in the config
```release-note
```
> fix(v3): names of uploaded files are not displayed correctly

- api/internal/managers/app/install/install.go
- api/internal/managers/app/install/util.go
- e2e/kots-release-install-v3/nginx-app-helm-v1beta2.yaml
- web/src/components/wizard/installation/phases/AppInstallationPhase.tsx
- web/src/components/wizard/installation/tests/AppInstallationPhase.test.tsx
- web/src/types/index.ts
Adds charts as steps with progress and logs to the app installation page similar to the infra installation page.
```release-note
```
> feat(v3): update the app installation page to show charts being installed with progress

- web/src/components/common/Markdown.tsx
Differences in styling for code blocks in markdown. Prints below are for Labels and Help text respectively.
https://app.shortcut.com/replicated/story/126837/markdown-code-blocks-have-the-wrong-background-color
NONE
```release-note
Differences in markdown styling of code blocks for config items on V3.
```
NONE
> chore(web): standardise styling for code blocks across components

- cmd/buildtools/openebs.go
- cmd/buildtools/velero.go
https://github.com/replicatedhq/embedded-cluster/actions/runs/17600356736/job/50001228715
```
failed to update openebs images: failed to update images: no component found for image docker.io/openebs/kubectl:1.25.15
```
https://github.com/replicatedhq/embedded-cluster/actions/runs/17614698156/job/50044981255
```
failed to update velero images: failed to update images: no component found for image docker.io/bitnamilegacy/kubectl:1.33
```
Fix:
https://github.com/replicatedhq/embedded-cluster/actions/runs/17614860986/job/50045527043
```release-note
```
> chore(ci): fix update addons openebs and velero new kubectl image

- .github/workflows/ci.yaml
fixes TestMultiNodeAirgapUpgradePreviousStable and TestSingleNodeUpgradePreviousStable use the wrong previous version with k0s version n-2 resulting in error "Before you can update to this version, you need to update to an earlier version that includes the required infrastructure update."
```release-note
```
> chore(ci): fix previous stable version e2e tests

- .github/workflows/ci.yaml
- pkg/addons/openebs/upgrade.go
- pkg/addons/openebs/upgrade_test.go
- tests/integration/kind/openebs/upgrade_hook_cleanup_test.go
- tests/integration/util/kind.go
Openebs pre-upgrade hook has delete policy "hook-succeeded". Subsequent upgrade attempts after a failure can fail with the following error:
```
2025/09/17 10:20:02 INFO updating status for rolled back release for openebs component=helm
Error: upgrade addons: upgrade addons: addon Storage: upgrade addon: helm upgrade: helm upgrade: release openebs failed, and has been rolled back due to atomic being set: pre-upgrade hooks failed: warning: Hook pre-upgrade openebs/templates/pre-upgrade-hook.yaml failed: 1 error occurred:
* serviceaccounts "openebs-pre-upgrade-hook" already exists
```
This change deletes the hook resources if they exist before performing the upgrade.
```release-note
Fixes an issue that can cause upgrades to fail when upgrading the OpenEBS add-on with error 'serviceaccounts …
```
> fix(openebs): delete leftover pre-upgrade hook resources before upgrade

- web/src/index.css
- web/tailwind.config.js
Fixes recent issues with typography styling introduced by #2851. Plugin setup is now different in v4, e.g. https://github.com/tailwindlabs/tailwindcss-forms?tab=readme-ov-file#installation
https://app.shortcut.com/replicated/story/129289/it-seems-like-our-markdown-support-regressed-and-isn-t-working-well-now
We need visual regression tests to pick up this kind of stuff.
```release-note
Fix styling issues in markdown for the v3 installer
```
NONE
> fix(web): styling issues for typography in v3

- e2e/kots-release-install-v3/config.yaml
- web/src/components/common/Select.tsx
- web/src/components/wizard/config/ConfigurationStep.tsx
- web/src/components/wizard/tests/ConfigurationStep.test.tsx
- web/src/types/index.ts
This PR implements Config Resource frontend parity for Embedded Cluster V3, adding support for
missing config item types to match KOTS functionality. Specifically:
1. **Dropdown config type** - Renders dropdown menus for selecting from predefined options
2. **Select_one config type** - Backward compatibility alias that renders as radio buttons
3. **Heading config type** - Visual section dividers for organizing config items
4. **Readonly field support** - Prevents editing of read-only configuration fields
These additions allow vendors to migrate their existing KOTS applications to EC V3 without 
modifying their config schemas.
**Technical implementation:**
- Refactored Select component to use `forwardRef` and `HelpText` for consistency with other form 
components
- Added dropdown, …
> feat(ui): add support for dropdown, heading, and readonly
